%% List of all reference, biasing and fixation blocks
% R-chamber: []

%% Biasing sessions with entry no, points to session folder/run. Typically run 0 contains orientation map, run >=1 contains biasing experiment
entryNo=1; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250318';
datastruct(entryNo).run='5';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=1;
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=2; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250320';
datastruct(entryNo).run='1';
datastruct(entryNo).baselineTS='9';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=1;
datastruct(entryNo).referenceBlockNo=1;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[44 46];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Pepper/Pepper20250318/run8/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[127 117];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=3;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=3; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250328';
datastruct(entryNo).run='3';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=1;
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=4; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250403';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L30OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=5; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250403';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=4;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[44 31];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[120 122];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=1;

entryNo=6; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250404';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='6';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=4;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[5 5];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L50OD20'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(5).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[118 118];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=7; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250417';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L20OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=8; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250423';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L25OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=9; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250423';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=8;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[10 9];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(8).date '/run3/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[135 140];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=10; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250429';
datastruct(entryNo).run='3';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L25OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=11; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250429';
datastruct(entryNo).run='6';
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=10;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[6 7];%[13 15];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(10).date '/run5/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[123 113];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=12; % B without dichroic;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250501';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=10;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[12 15];
datastruct(entryNo).sensitivity=.1*10^-5;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(12).date '/run3/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[129 119];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=13; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250501';
datastruct(entryNo).run='6';
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=10;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[6 6];
datastruct(entryNo).sensitivity=.1*10^-5;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(12).date '/run3/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[128 121];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;