%% List of all reference, biasing and fixation blocks
%{
% Best L-chamber: 81, 74, 62
% L-chambers: [120:122 116:118 112:114 109 108* 105* 104 101 100, 93 92 90 89 88 87 84 83 81 79 78 74 73 72 67 66 65 64 62 59 51 50];  *denotes reduced power
%       - With combined baseline: [72 67 66 65 64 62];
%       - Power series
%       - 20col: [120:122 116:118 112:114 108:109 89 84 83 68 58]
%       - 1col: [104:105 100:101 ]
%       - Fixation only: [110* 106 102] *denotes 20-column
%          sort([83 82 81 79 78 77 76 74 73 72 67 66 65 64 62 59 58 51 50],'ascend'); 
%          fliplr([43 44 45 47 48, 52 53 54 57 58 59 62 63 64 65 66]); 
%
% R-chamber: [12 14 15 17 19 20 21 23 24 26 29 31 32 34 37 40]; %17; %10 excluded because baseline different
%}


%% Biasing sessions with entry no, points to session folder/run. Typically run 0 contains orientation map, run >=1 contains biasing experiment
entryNo=1; %VSD
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220727';
datastruct(entryNo).run='0';
datastruct(entryNo).modality='VSD';

entryNo=2; %first decent
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220831';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=3; %higher power
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220901';
datastruct(entryNo).run='5'; %0
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=4; %higher power
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220909';
datastruct(entryNo).run='1'; %0
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=5; % Recent good
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220920';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=6;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221013';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=7;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221017';
datastruct(entryNo).run='1';%0
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=8;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221025';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

%% Start of biasing sessions
entryNo=9; % O;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221028';
datastruct(entryNo).run='0'; %0
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).blueLED='L45OD13'; 
entryNo=10; % B; 1st biasing
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221028';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L50OD13'; 
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gridSize=32;
datastruct(entryNo).adaptthresh=99;
datastruct(entryNo).sensitivity=NaN;
datastruct(entryNo).gammaCorrFactor=5;
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;
datastruct(entryNo).alignmentBlockNo=9;
datastruct(entryNo).referenceBlockNo=9;
datastruct(entryNo).temporalmultiplex=20/50;

entryNo=11; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221031';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).blueLED='L45OD13'; 
entryNo=12; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221031';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=11;
datastruct(entryNo).referenceBlockNo=11;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).adaptthresh=99;
datastruct(entryNo).sensitivity=NaN;
datastruct(entryNo).gammaCorrFactor=5;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;
datastruct(entryNo).blueLED='L50OD13'; % check file
datastruct(entryNo).adaptthresh=99;
datastruct(entryNo).sensitivity=NaN;
datastruct(entryNo).gammaCorrFactor=5;
datastruct(entryNo).temporalmultiplex=20/50;

entryNo=13; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221104';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).blueLED='L60OD13'; % check file
entryNo=14; % B; 1st biasing both patterns, with calibration
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221104';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=13;
datastruct(entryNo).referenceBlockNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;
datastruct(entryNo).blueLED='L50OD13'; % check file
datastruct(entryNo).adaptthresh=99;
datastruct(entryNo).sensitivity=NaN;
datastruct(entryNo).gammaCorrFactor=50;
datastruct(entryNo).temporalmultiplex=20/50;

entryNo=15; % B; first biasing with previous bitmap, 20221104 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221109';
datastruct(entryNo).run='4';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=13;
datastruct(entryNo).referenceBlockNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).greenImgID=1;
datastruct(entryNo).blueLED='L50OD13'; % check file
datastruct(entryNo).adaptthresh=99;
datastruct(entryNo).sensitivity=NaN;
datastruct(entryNo).gammaCorrFactor=35;
datastruct(entryNo).temporalmultiplex=20/50;

entryNo=16; % O
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221111';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).blueLED='L50OD13'; % check file
entryNo=17; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221111';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=16;
datastruct(entryNo).referenceBlockNo=16;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;
datastruct(entryNo).blueLED='L50OD13'; % check file
datastruct(entryNo).adaptthresh=99;
datastruct(entryNo).sensitivity=NaN;
datastruct(entryNo).gammaCorrFactor=40;
datastruct(entryNo).temporalmultiplex=20/50;

entryNo=18;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221115';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=19; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221122';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=19;
datastruct(entryNo).referenceBlockNo=13; %originally said 16, discrepancy with ImagingLog
datastruct(entryNo).gridSize=32;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='0';
datastruct(entryNo).greenImgID=1;
datastruct(entryNo).blueLED='L50OD13'; % check file
datastruct(entryNo).adaptthresh=99;
datastruct(entryNo).sensitivity=NaN;
datastruct(entryNo).gammaCorrFactor=40;
datastruct(entryNo).temporalmultiplex=20/50;

entryNo=20; % B; -?
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221123';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=20;
datastruct(entryNo).referenceBlockNo=16;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=45; % !65 and 45!
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';%'4';
datastruct(entryNo).greenImgID=1;
datastruct(entryNo).blueLED='L50OD13'; % check file
datastruct(entryNo).adaptthresh=99;
datastruct(entryNo).sensitivity=NaN;
datastruct(entryNo).gammaCorrFactor=40;
datastruct(entryNo).temporalmultiplex=20/50;

entryNo=21; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221130';
datastruct(entryNo).run='2';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=20;
datastruct(entryNo).referenceBlockNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).greenImgID=1;

entryNo=22; %?
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221202';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=23; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221206';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=20;
datastruct(entryNo).referenceBlockNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=35;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;

entryNo=24; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221207';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=20;
datastruct(entryNo).referenceBlockNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='0';
datastruct(entryNo).greenImgID=1;

entryNo=25;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221208';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=26; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221208';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=20;
datastruct(entryNo).referenceBlockNo=25;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;

entryNo=27;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221208';
datastruct(entryNo).run='2';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=28;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221216';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=29; % B; -
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221216';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=28;
datastruct(entryNo).referenceBlockNo=28;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=80;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;

entryNo=30; % O;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221221';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=31; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221221';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=28;
datastruct(entryNo).referenceBlockNo=28;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=80;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;

entryNo=32; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221222';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=28;
datastruct(entryNo).referenceBlockNo=28;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=80;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='0';
datastruct(entryNo).greenImgID=1;

%{
entryNo=31;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221223';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
%}

entryNo=33;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221228';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=34; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221228';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=28;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=70;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;

entryNo=35;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230103';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=36;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230113';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=37; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230113';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=36;
datastruct(entryNo).referenceBlockNo=36;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).greenImgID=1;

entryNo=38;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230120';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=39; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230124';
datastruct(entryNo).run='12';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=40; % B;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230125';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=36;
datastruct(entryNo).referenceBlockNo=39;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=50/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L100OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).gaussianResponse=NaN;
datastruct(entryNo).gaussianContourLevel=[NaN NaN]; %max
datastruct(entryNo).gaussianContourLevelMax=NaN;
datastruct(entryNo).gaussianCond=NaN;
datastruct(entryNo).baselineTS='0';
datastruct(entryNo).greenImgID=2;

entryNo=41; % Alignment
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230209';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

%% === Chip-L chamber === 
entryNo=42; % O; Good orientation map, PCAexplvar=82.2%
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230721';
datastruct(entryNo).run='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).blueLED='L12OD10?'; % 12-15%
entryNo=43; % B; BL
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230721';
datastruct(entryNo).run='3';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=42;
datastruct(entryNo).referenceBlockNo=42;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L50OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];

entryNo=44; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230802';
datastruct(entryNo).run='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=42;
datastruct(entryNo).blueLED='L15OD13';
entryNo=45; % B;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230802';
datastruct(entryNo).run='3';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=42;
datastruct(entryNo).referenceBlockNo=44;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=50; %40
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=10/50; %ON-OFF timing
datastruct(entryNo).blueLED='L15OD13'; % check file
datastruct(entryNo).orangeLED='L50OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];

entryNo=46; % O; PCAexplvar=82.2
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230803';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).blueLED='L15OD13'; %15% or 20%
entryNo=47; % B;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230803';
datastruct(entryNo).run='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=46;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=60; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=10/50; %ON-OFF timing
datastruct(entryNo).blueLED='L8OD13';
datastruct(entryNo).orangeLED='L50OD0'; %ON-OFF timing
datastruct(entryNo).nColumnsWanted=[20 20];

entryNo=48; % B;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230804';
datastruct(entryNo).run='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=46;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=120; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L8OD13';
datastruct(entryNo).orangeLED='L50OD0';
datastruct(entryNo).nColumnsWanted=[20 20];

% ***First gaussian fit***
entryNo=49; % O; PCAvar=85%;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230809';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).blueLED='L12OD16';
datastruct(entryNo).orangeLED='L50OD0';
entryNo=50; % B; wrong angle for optostim dichroic
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230809';
datastruct(entryNo).run='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=49;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=40; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=50/50; %ON-OFF timing
datastruct(entryNo).blueLED='L12OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230809/run99/Data_vdaqlog.mat';
datastruct(entryNo).gaussianCond=3; %1deg
datastruct(entryNo).gaussianContourLevel=[4 4];%of10
datastruct(entryNo).gaussianContourLevelMax=10;
datastruct(entryNo).nColumnsWanted=[0 0];
entryNo=51; % Bx ; wrong angle for optostim dichroic
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230809';
datastruct(entryNo).run='3';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=49;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=40; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=50/50; %ON-OFF timing
datastruct(entryNo).blueLED='L12OD16';
datastruct(entryNo).orangeLED='L100OD0'; 
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230809/run99/Data_vdaqlog.mat';
datastruct(entryNo).gaussianCond=3; %1deg
datastruct(entryNo).gaussianContourLevel=[6 6]; %of10
datastruct(entryNo).gaussianContourLevelMax=10;
datastruct(entryNo).nColumnsWanted=[0 0];

entryNo=52; % B; blurry
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230810';
datastruct(entryNo).run='3';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=49;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=50/50; %ON-OFF timing
datastruct(entryNo).blueLED='L14OD16';
datastruct(entryNo).orangeLED='L40OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230810/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).gaussianContourLevel=[48 38];%48(3);%45(5-6);%19(33);%38(11-12);%of 50
datastruct(entryNo).gaussianContourLevelMax=50;
entryNo=53; % B; truncated blurry
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230810';
datastruct(entryNo).run='4';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=49;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=12; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=50/50; %ON-OFF timing
datastruct(entryNo).blueLED='L13OD16';
datastruct(entryNo).orangeLED='L40OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230810/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).gaussianContourLevel=[42 48]; %48(3);%42(8-11); %of 50
datastruct(entryNo).gaussianContourLevelMax=50; 
entryNo=54; % B; truncated blurry
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230810';
datastruct(entryNo).run='5';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=49;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=35; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=50/50; %ON-OFF timing
datastruct(entryNo).blueLED='L13OD16';
datastruct(entryNo).orangeLED='L40OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230810/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).gaussianContourLevel=[30 42 48]; %48(3);%42(8-11); %of 50
datastruct(entryNo).gaussianContourLevelMax=50; 
entryNo=55; % B; truncated blurry 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230810';
datastruct(entryNo).run='6';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=49;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=50/50; %ON-OFF timing
datastruct(entryNo).blueLED='L13OD16';
datastruct(entryNo).orangeLED='L40OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230810/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).gaussianContourLevel=[30 42 48]; %48(3);%42(8-11); %of 50
datastruct(entryNo).gaussianContourLevelMax=50; 

entryNo=56; % O; PCAvar=85% but lower d' (hole)
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230811';
datastruct(entryNo).run='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).blueLED='L14OD16'; %little high, go 12%
datastruct(entryNo).orangeLED='L40OD0';
entryNo=57; % B; good bi-pattern effect
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230811';
datastruct(entryNo).run='4';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=56;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=40; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L12OD16';
datastruct(entryNo).orangeLED='L40OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230811/run7/Data_vdaqlog.mat';
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).gaussianContourLevel=23; %48(3);%42(8-11); %of 50
datastruct(entryNo).gaussianContourLevelMax=50; 

entryNo=58; % B; N=20 %potential error, different session gaussian
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230812';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=56;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L12OD16';
datastruct(entryNo).orangeLED='L40OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230811/run7/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[23 23]; %48(3);%42(8-11); %of 50
datastruct(entryNo).greenImgID=2;
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20]; 
entryNo=59; % B; N=20 %same session gaussian
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230812';
datastruct(entryNo).run='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=56;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=10/50; %ON-OFF timing
datastruct(entryNo).blueLED='L12OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230812/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[23 23]; %48(3);%42(8-11); %of 50
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).greenImgID=3;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[18 16]; 
entryNo=60; % B; N=5 truncated
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230812';
datastruct(entryNo).run='3';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=46;
datastruct(entryNo).referenceBlockNo=49;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L12OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230812/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[35 35]; %11
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).greenImgID=3;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[5 5]; 

entryNo=61; % O; PCAvar=84.6%, no hole
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230815';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61; %realign
datastruct(entryNo).blueLED='L10OD16'; %little high, go 12%
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=62; % B; N=10
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230815';
datastruct(entryNo).run='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=61;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=120; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230815/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[29 29]; %10
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[10 11]; 
datastruct(entryNo).greenImgID=2;
entryNo=63; % B; N=5 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230815';
datastruct(entryNo).run='3';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=61;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=65; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=18/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230815/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[40 40];%5
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[5 5];
datastruct(entryNo).greenImgID=3;
entryNo=64; % B; N=3
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230815';
datastruct(entryNo).run='4';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=61;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=18;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;%.01*10^1.65;
datastruct(entryNo).powercycle=37/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230815/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[46 46];% 2-3
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).greenImgID=4; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[3 5];

entryNo=65; % B; N=4
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230816';
datastruct(entryNo).run='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=61;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=35; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=27/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230816/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[172 172];%[87 87];
datastruct(entryNo).gaussianContourLevelMax=200;%100;
datastruct(entryNo).greenImgID=2; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[5 5];
entryNo=66; % B; N=2
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230816';
datastruct(entryNo).run='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=61;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=10;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;%.01*10^1.65;
datastruct(entryNo).powercycle=27/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230816/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[177 177];%[190 187];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).greenImgID=2; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[2 3];

entryNo=67; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230817';
datastruct(entryNo).run='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=61;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;%.01*10^1.65;
datastruct(entryNo).powercycle=5/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230817/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[70 70]; % 2 col
datastruct(entryNo).gaussianContourLevelMax=200;%[200 200]; 
datastruct(entryNo).gaussianCond=3; % larger 2deg gaussian
datastruct(entryNo).nColumnsWanted=[34 34];
datastruct(entryNo).greenImgID=2; 
entryNo=68; % B; N=20 incomplete, trials/cond=6
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230817';
datastruct(entryNo).run='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=61;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;%.01*10^1.65;
datastruct(entryNo).powercycle=12/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230817/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[21 21]; % 20 col
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=3;


entryNo=69; % 0; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230818';
datastruct(entryNo).run='4';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=3;
entryNo=70; % 0; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230818';
datastruct(entryNo).run='5';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L100OD20';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=5;


entryNo=71; % 0; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230822';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
entryNo=72; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230822';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=71;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;%.01*10^1.65;
datastruct(entryNo).powercycle=9/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230822/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[20 23]; % 20 col
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[19 20];
datastruct(entryNo).greenImgID=2;

% First decoupled baseline
entryNo=73; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230823';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=71;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;%.01*10^1.65;
datastruct(entryNo).powercycle=9/50; %ON-OFF timing 9-31
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230823/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[20 22]; % 20 col
datastruct(entryNo).gaussianContourLevelMax=50; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[19 20];
datastruct(entryNo).greenImgID=[];
entryNo=74; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230823';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=71;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=5;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;%.01*10^1.65;
datastruct(entryNo).powercycle=18/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230823/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[187 187];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[3 6];
datastruct(entryNo).greenImgID=[];


entryNo=75; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230824';
datastruct(entryNo).run='0';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L8OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=76; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230824';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=75;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=1;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=31/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L8OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230824/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[194 194];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[3 2];
datastruct(entryNo).greenImgID=[];
entryNo=77; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230824';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=75;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=29/50; %ON-OFF timing
datastruct(entryNo).blueLED='L8OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230824/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[142 137]; %11
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[18 16];
datastruct(entryNo).greenImgID=[];

entryNo=78; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230825';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=75;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=1;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=35/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L8OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230825/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[195 196];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];%[2 1];
datastruct(entryNo).greenImgID=[];
entryNo=79; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230825';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=75;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=80; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=21/50; %ON-OFF timing
datastruct(entryNo).blueLED='L8OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230825/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[148 149]; %11
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[10 9];
datastruct(entryNo).greenImgID=[];


entryNo=80; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230829';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L9OD16'; %compensate to achieve 0.9% trial saturation
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=81; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230829';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2'; %[2, 4]
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=80;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=9/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230829/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[16 32]; %11
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[32 30];
datastruct(entryNo).greenImgID=[];

entryNo=82; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230830';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L9OD16'; %compensate to achieve 0.9% trial saturation
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=83; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230830';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=82;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=9/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230830/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[65 63];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];
entryNo=84; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230830';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=82;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=9/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230830/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[65 63];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=85; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230904';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L9OD16'; %compensate to achieve 0.9% trial saturation
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=86; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230905';
datastruct(entryNo).run='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L9OD16'; %compensate to achieve 0.9% trial saturation
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=87; % B; 5
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230905';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='3';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=86;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=1;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=35/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230905/run4/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[196 192];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];%[1 3];
datastruct(entryNo).greenImgID=2;
entryNo=88; % B; 5
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230905';
datastruct(entryNo).run='6';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=86;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;%.01*10^1.65;
datastruct(entryNo).powercycle=35/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230905/run4/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[119 130];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[10 10];
datastruct(entryNo).greenImgID=2;

entryNo=89; % B; 20
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230906';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=86;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=10/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230906/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[75 90];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];
entryNo=90; % B; 15
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230906';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=86;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=10/50; %ON-OFF timing
datastruct(entryNo).blueLED='L10OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230906/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[95 103];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[17 15];
datastruct(entryNo).greenImgID=[];

entryNo=91; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230907';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L9OD16'; %compensate to achieve 0.9% trial saturation
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=92; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230907';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2'; %[2, 4]
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=91;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=7/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230907/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[35 37]; %11
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[35 30];
datastruct(entryNo).greenImgID=2;
entryNo=93; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230907';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2'; %[2, 4]
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=91;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=150; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=7/50; %ON-OFF timing
datastruct(entryNo).blueLED='L9OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230907/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[35 37]; %11
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[35 30];
datastruct(entryNo).greenImgID=2;

%% Room 6
entryNo=94; % O; Check Fast data if this was run
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20231207';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).blueLED='L9OD16'; %compensate to achieve 0.9% trial saturation
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=95; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20231207';
datastruct(entryNo).run='1';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=61;
datastruct(entryNo).referenceBlockNo=75;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=1;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=35/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L8OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20230825/run0/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[195 196];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[2 1];
datastruct(entryNo).greenImgID=[];

% Baseline, Fixation
entryNo=97; % 12ort; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240105';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).blueLED='L5OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=98; % P;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240105';
datastruct(entryNo).run=5:9;
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=97;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=1;%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=35/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240105/run4/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[195 196];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=2;

% Baseline, Biasing (Two of 1x power, N=1), Fixation
entryNo=99; % 12ort;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240109';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).blueLED='L5OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=100; % O;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240109';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=99; %42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=[7 15];%1; %>60? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=18/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240109/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=2;
entryNo=101; % P; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240109';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=99;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=[7 15];%1; %>60? %x35; %x40  [5 7]
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=18/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240109/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=3;
entryNo=102; % P; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240109';
datastruct(entryNo).run=5:9;
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=99;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=15;%[7 15];%1; %>60? %x35; %x40  [5 7]
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=18/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=[mainPath 'Chip/Chip20240109/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=3;

% Baseline, Biasing (1x and 0.5x power, N=1), Fixation, PRF, SIRF
entryNo=103; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240112';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).blueLED='L5OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=104; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240112';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=103;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=15;%[8 15];%[8 15];%1; %>59? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=20/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240112/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=2;
entryNo=105; % B;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240112';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=103;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=[8 15];%[8 15];%1; %>59? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=10/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240112/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=2;
entryNo=106; % P; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240112';
datastruct(entryNo).run=[5 6 8 9];
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=103;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=15;%[15];%[8 15];%1; %>59? %x35; %x40 
datastruct(entryNo).sensitivity=1;%.01*10^1.65;
datastruct(entryNo).powercycle=10/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240112/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=2;

% Baseline, Biasing (1x and 0.5x power, N=20), Fixation, PRF
entryNo=107; % O; % D+1 after cleaning
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240118';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).blueLED='L5OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=108; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240118';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=107;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100;%[8 15];%1; %>59? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240118/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[67 69];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=109; % B;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240118';
datastruct(entryNo).run='10';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=107;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100;%[8 15];%1; %>59? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=4/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240118/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[67 69];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=110; % P;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240118';
datastruct(entryNo).run=5:9; % R4 TS.mat seems to be corrupted
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=107;%42;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=100;%[8 15];%1; %>59? %x35; %x40 
datastruct(entryNo).sensitivity=.01*10^-1;
datastruct(entryNo).powercycle=4/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L5OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240118/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[67 69];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

% Baseline, Biasing (1x and 0.5x power, N=20), Fixation, PRF
entryNo=111; % O; % D+1 after cleaning
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240126';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).blueLED='L6OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=112; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240126';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=111;%42;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=[75 80]; %[115 120]
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=4/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L6OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240126/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[74 64];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=3;
entryNo=113; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240126';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=111;%42;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=[75 80]; %[115 120]
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=1/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L6OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240126/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[74 64];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=3;
entryNo=114; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240126';
datastruct(entryNo).run='11';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=111;%42;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=[75 80]; %[115 120]
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=2/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L6OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240126/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[74 64];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=3;


% Baseline, Biasing (1x and 0.5x power, N=20), Fixation, PRF
entryNo=115; % O; % D+1 after cleaning
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240131';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=116; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240131';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=115;%42;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=55;
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=4/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240131/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[45 54];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=117; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240131';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=115;%42;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=55;
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=4/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240131/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[45 54];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=118; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240131';
datastruct(entryNo).run='6';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=115;%42;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=55;
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=1/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240131/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[45 54];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

% Baseline, Biasing (1x and 0.5x power, N=20), Fixation, PRF
entryNo=119; % O; % D+1 after cleaning
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240202';
datastruct(entryNo).run='0';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=120; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240202';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=119;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=[65 58];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=4/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240202/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[53 63];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=3;
entryNo=121; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240202';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=119;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=[65 58];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=2/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240202/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[53 63];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=3;
entryNo=122; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20240202';
datastruct(entryNo).run='6';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='1';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=97;
datastruct(entryNo).referenceBlockNo=119;
datastruct(entryNo).gridSize=16;%32;
datastruct(entryNo).gammaCorrFactor=[65 58];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=2/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16';
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Chip/Chip20240202/run1/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[53 63];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=3;