%% List of all reference, biasing and fixation blocks
% R-chamber: []
% Layer removals: 3/18, 7/1, 9/29 
%% Biasing sessions with entry no, points to session folder/run. Typically run 0 contains orientation map, run >=1 contains biasing experiment
entryNo=1; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250318';
datastruct(entryNo).run='5';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=1;
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=2; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250320';
datastruct(entryNo).run='1';
datastruct(entryNo).baselineTS='9';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=1;
datastruct(entryNo).referenceBlockNo=1;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[44 46];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse='Y:/Pepper/Pepper20250318/run8/Data_vdaqlog.mat';
datastruct(entryNo).gaussianContourLevel=[127 117];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=3;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=3; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250328';
datastruct(entryNo).run='3';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=1;
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=4; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250403';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L30OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=5; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250403';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=4;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[44 31];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[120 122];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=1;

entryNo=6; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250404';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='6';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=4;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[5 5];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L50OD20'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(5).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[118 118];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=7; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250417';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L20OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=8; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250423';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L25OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=9; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250423';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=8;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[10 9];
datastruct(entryNo).sensitivity=.1*10^-1;
datastruct(entryNo).powercycle=10/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(8).date '/run3/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[135 140];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=10; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250429';
datastruct(entryNo).run='3';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L25OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=11; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250429';
datastruct(entryNo).run='6';
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=10;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[6 7];%[13 15];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=8/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(10).date '/run5/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[123 113];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=12; % B without dichroic;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250501';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=10;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[12 15];
datastruct(entryNo).sensitivity=.1*10^-5;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(12).date '/run3/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[129 119];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=13; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250501';
datastruct(entryNo).run='6';
datastruct(entryNo).baselineTS='4';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=10;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[6 6];
datastruct(entryNo).sensitivity=.1*10^-5;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L7OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(12).date '/run3/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[128 121];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=14; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250604';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L30OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=15; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250605';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).referenceBlockNo=14;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[12 12];%[13 15];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=30/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L20OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(15).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[112 125];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=16; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250708';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=4;
datastruct(entryNo).blueLED='L40OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=17; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250710';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).blueLED='L30OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];

entryNo=18; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250710';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=16;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[60 55];%[39 35];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L15OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(18).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[109 130];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=19; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250711';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=16;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[50 55];%[39 35];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L12OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L50OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(19).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[117 130];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=20; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250711';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=16;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[38 31];%[39 35];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L12OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L50OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(19).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[120 142];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;




%% Start of glasses + non-matched ortmap flashed grating and OD task gabor (SF=2cpd, Size=2)
entryNo=21; % O; % Reference map 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250820';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).blueLED='L50OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=24; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250821';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=21;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[23 25];%[39 35];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L50OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L50OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(24).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[101 105];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

%% Start of glasses + matching ortmap flashed grating and OD task gabor (SF=3.8cpd, Size=4)
entryNo=25; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250822';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).blueLED='L50OD16'; 
datastruct(entryNo).orangeLED='L30OD0';
datastruct(entryNo).greenImgID=[];
entryNo=26; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250822';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=25;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[40 47]-15;%[39 35];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L50OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L40OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(26).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[101 100];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=27; % B;  Changed to gridsize 16
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250822';
datastruct(entryNo).run='5';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=25;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[40 47]-15;%[39 35];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L50OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L60OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(26).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[101 100];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=28; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250826';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=25;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[38 55];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L50OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(28).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[99 100];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=29; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250827';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=25;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[44 62];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L50OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(29).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[85 100];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=3;

entryNo=30; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250828';
datastruct(entryNo).run='1';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=25;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[35-6 43-5];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(30).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[100 100];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=31; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250829';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=25;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[27 37]-2;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(31).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[108 114];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=32; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250829';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=25;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[27 37]-2;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(31).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[108 114];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=33; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250904';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];
entryNo=34; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250904';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[28 29];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(34).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[119 126];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=35; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250904';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[28 29];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=25/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(34).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[119 126];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=36; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250905';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[26 34];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(36).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[117 126-14];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=37; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250910';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[20 33];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(37).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[117 110];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=38; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250910';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[20 33];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=38/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(37).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[117 110];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=39; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250911';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[22 34];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=25/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(38).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[117 110];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=40; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250911';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[22 34];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=38/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(38).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[117 110];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=41; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250912';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[28 39];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=38/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(41).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[101 105];
datastruct(entryNo).gaussianContourLevelMax=200; 
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=42; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250918';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[27 36];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=38/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L60OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(42).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[89 98];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=43; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250919';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[27 37];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=25/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(43).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[104 98];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=43; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250919';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[27 37];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(43).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[104 98];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=44; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250924';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[29 36];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(44).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[104 102];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=45; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20250924';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=33;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[29 36];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(44).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[104 102];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=46; % O; Reference map (removed layer 09/29)
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251001';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];
entryNo=47; % B: 2219-2244px (5.8-5.9%), 100%
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251001';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=46;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[28 41];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(47).date '/run1/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[108 118];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=48; % O; % Reference map, poor coreg with prior map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251021';
datastruct(entryNo).run='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];
entryNo=49; % B *adjusted eyetracker to better cover eye (eye was at the edge and too high)
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251021';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=48;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[28+4 41+6]+2;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(49).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[99 92];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=50; % 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251022';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=17;
datastruct(entryNo).referenceBlockNo=48;
%{
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[28+6 41+8]+2;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=15/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L70OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(50).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[89 97];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
%}

entryNo=51; % O; % Reference map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251023';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L1000OD0';
datastruct(entryNo).greenImgID=[];
entryNo=52; % B *recalibrate projector focus, peak light position, cam-proj alignment
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251023';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=48;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[28+11 41+6]+10;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(50).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[83 98];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=53; % B *recalibrate projector focus, peak light position, cam-proj alignment
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251023';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=48;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[28+11 41+6]+10;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=25/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(50).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[83 98];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=54; % B *recalibrate projector focus, peak light position, cam-proj alignment
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251024';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=48;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[25 41+6]+10;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L80OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[101 94];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];
entryNo=55; % B *recalibrate projector focus, peak light position, cam-proj alignment
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251024';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=48;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[25 41+6]+10;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=25/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L80OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[101 94];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];

entryNo=56; % B *Infection, cloudy chamber poor signals
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251029';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=48;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[25+10 41+1]+10;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[100 110];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=57; % B *Infection, cloudy chamber poor signals
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251029';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=48;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[25+10 41+1]+10;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=25/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16'; % lower to avoid hole in center
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[100 110];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;

entryNo=58; % O; % Reference map, poor coreg with prior map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251104';
datastruct(entryNo).run='3';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=3;

entryNo=59; % O; % Reference map, poor coreg with prior map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251106';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];

entryNo=60; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251107';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=59;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[18 28]-1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[119 116];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=62; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251107';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=59;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[23 28]-1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[119 106];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
datastruct(entryNo).orts=[45 135];

entryNo=63; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251111';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=59;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[22 27]+1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L90OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[108 111];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
entryNo=64; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251111';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).referenceBlockNo=59;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[26 26]+1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L90OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[108 107];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=2;
datastruct(entryNo).orts=[45 135];

entryNo=65; % O; % Reference map, poor coreg with prior map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251113';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];

entryNo=66; % Calib
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251114';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=66;
datastruct(entryNo).blueLED='L0OD16'; 
datastruct(entryNo).orangeLED='L40OD0';
datastruct(entryNo).greenImgID=[];
entryNo=67; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251114';
datastruct(entryNo).run='2';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=66;
datastruct(entryNo).referenceBlockNo=65;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[26 26]+1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[112 108];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];
datastruct(entryNo).orts=[45 135];
entryNo=68; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251114';
datastruct(entryNo).run='3';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=66;
datastruct(entryNo).referenceBlockNo=65;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[26 26]+1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[112 108];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];
datastruct(entryNo).orts=[45 135];
entryNo=69; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251114';
datastruct(entryNo).run='4';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=66;
datastruct(entryNo).referenceBlockNo=65;
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[26 26]+1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[112 108];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
datastruct(entryNo).greenImgID=[];
datastruct(entryNo).orts=[45 135];

entryNo=70; % O; % Reference map, poor coreg with prior map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251211';
datastruct(entryNo).run='3';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=51;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];

entryNo=71; % O; % Reference map, poor coreg with prior map
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251212';
datastruct(entryNo).run='0';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=71;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];

entryNo=72; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251216';
datastruct(entryNo).run='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=71;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];

entryNo=73;
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251218';
datastruct(entryNo).baselineTS='5';
datastruct(entryNo).run='6';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=71;
datastruct(entryNo).referenceBlockNo=72;
datastruct(entryNo).gridSize=64;
datastruct(entryNo).gammaCorrFactor=[8 8];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run3/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=2;

entryNo=74;
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20251219';
datastruct(entryNo).baselineTS='1';
datastruct(entryNo).run='2';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=71;
datastruct(entryNo).referenceBlockNo=72;
datastruct(entryNo).gridSize=64;
datastruct(entryNo).gammaCorrFactor=[8 5];
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=2;



entryNo=75; % B 
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20260115';
datastruct(entryNo).run='1';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP'; 
datastruct(entryNo).alignmentBlockNo=71;
datastruct(entryNo).blueLED='L100OD16'; 
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).greenImgID=[];
entryNo=76;
datastruct(entryNo).monkeyNo='32';
datastruct(entryNo).monkey='Pepper';
datastruct(entryNo).chamber='R';
datastruct(entryNo).date='20260115';
datastruct(entryNo).baselineTS='2';
datastruct(entryNo).run='3';
datastruct(entryNo).site='2';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentBlockNo=71;
datastruct(entryNo).referenceBlockNo=75;
datastruct(entryNo).gridSize=64;
datastruct(entryNo).gammaCorrFactor=[6 12];%-1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianResponse=['Y:/' datastruct(entryNo).monkey '/' datastruct(entryNo).monkey ... 
    datastruct(entryNo).date '/run0/Data_vdaqlog.mat'];
datastruct(entryNo).gaussianContourLevel=[200 200];
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[1 1];
datastruct(entryNo).greenImgID=3;
%{
datastruct(entryNo).gridSize=16;
datastruct(entryNo).gammaCorrFactor=[18 28]-1;
datastruct(entryNo).sensitivity=.1*10^-10;
datastruct(entryNo).powercycle=50/50; %31-20 ON-OFF timing
datastruct(entryNo).blueLED='L100OD16';
datastruct(entryNo).orangeLED='L100OD0';
datastruct(entryNo).gaussianContourLevel=[119 116]-50;
datastruct(entryNo).gaussianContourLevelMax=200;
datastruct(entryNo).gaussianCond=2;
datastruct(entryNo).nColumnsWanted=[20 20];
%}