%% Biasing sessions with entry no, points to session folder/run. Typically run 0 contains orientation map, run >=1 contains biasing experiment
entryNo=1; %VSD
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220727';
datastruct(entryNo).run='0';
datastruct(entryNo).modality='VSD';

entryNo=2; %first decent
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220831';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=3; %higher power
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220901';
datastruct(entryNo).run='5'; %0
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=4; %higher power
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220909';
datastruct(entryNo).run='1'; %0
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=5; % Recent good
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20220920';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=6;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221013';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=7;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221017';
datastruct(entryNo).run='1';%0
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=8;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221025';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

%% Start of biasing sessions
entryNo=9; % O;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221028';
datastruct(entryNo).run='0'; %0
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=10; % B; 1st biasing
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221028';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=11; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221031';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=12; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221031';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=11;
datastruct(entryNo).referenceSessionEntryNo=11;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=50;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=13; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221104';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=14; % B; 1st biasing both patterns, with calibration
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221104';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=13;
datastruct(entryNo).referenceSessionEntryNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=50;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=15; % B; first biasing with previous bitmap, 20221104 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221109';
datastruct(entryNo).run='4';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=13;
datastruct(entryNo).referenceSessionEntryNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=35;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=16; % O
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221111';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=17; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221111';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=16;
datastruct(entryNo).referenceSessionEntryNo=16;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=40;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=18;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221115';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=19; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221122';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=19;
datastruct(entryNo).referenceSessionEntryNo=16;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=40;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=20; % B; -?
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221123';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=20;
datastruct(entryNo).referenceSessionEntryNo=16;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=45; % !65 and 45!
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=21; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221130';
datastruct(entryNo).run='2';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=20;
datastruct(entryNo).referenceSessionEntryNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=22; %?
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221202';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=23; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221206';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=20;
datastruct(entryNo).referenceSessionEntryNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=35;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=24; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221207';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=20;
datastruct(entryNo).referenceSessionEntryNo=13;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing

entryNo=25;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221208';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=26; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221208';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=20;
datastruct(entryNo).referenceSessionEntryNo=25;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=20/50; %ON-OFF timing
entryNo=27;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221208';
datastruct(entryNo).run='2';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=28;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221216';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=29; % B; -
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221216';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=28;
datastruct(entryNo).referenceSessionEntryNo=28;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=80;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing

entryNo=30; % O;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221221';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=31; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221221';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=28;
datastruct(entryNo).referenceSessionEntryNo=28;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=80;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing

entryNo=32; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221222';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=28;
datastruct(entryNo).referenceSessionEntryNo=28;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=80;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing

%{
entryNo=31;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221223';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
%}

entryNo=33;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221228';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=34; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20221228';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=28;
datastruct(entryNo).referenceSessionEntryNo=33;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=70;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing

entryNo=35;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230103';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=36;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230113';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
entryNo=37; % B; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230113';
datastruct(entryNo).run='1';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=36;
datastruct(entryNo).referenceSessionEntryNo=36;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=40/50; %ON-OFF timing

entryNo=38;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230120';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=39; % O; 
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230124';
datastruct(entryNo).run='12';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';

entryNo=40; % B;
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230125';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
datastruct(entryNo).alignmentSessionEntryNo=36;
datastruct(entryNo).referenceSessionEntryNo=39;
datastruct(entryNo).gridSize=32;
datastruct(entryNo).gammaCorrFactor=30;
datastruct(entryNo).sensitivity=.01*10^-2;
datastruct(entryNo).powercycle=50/50; %ON-OFF timing

entryNo=41; % Alignment
datastruct(entryNo).monkeyNo='28';
datastruct(entryNo).monkey='Chip';
datastruct(entryNo).date='20230209';
datastruct(entryNo).run='0';
datastruct(entryNo).site='30';
datastruct(entryNo).modality='GCaMP';
