function [figHandle, demoPlotData, outputFiles] = plotDemoOptostim2( ...
    currentBlockStruct, imagingData, bitmapData, ...
    columnarProducts, demoProducts, blockID, currentSessID, ...
    mainPath, monkeyName, chamberWanted, saveFlag)
%PLOTDEMOOPTOSTIM
% Two-panel demonstration figure for one optostimulation session.
%
% Panel A:
%   Full coregistered PCA response difference (90 deg - 0 deg), designed
%   targets, ROI outline, and the larger Gaussian footprint.
%
% Panel B:
%   Bandpassed 0%-contrast response difference:
%       mean(OptoStim 90 deg) - mean(OptoStim 0 deg)
%   with the same designed target overlays as Panel A, ROI, and the same
%   Gaussian footprint. Stabilization offsets are tested in both sign
%   conventions, and Pearson R^2 versus Panel A is reported outside it.
%
% All displayed spatial products are in current-session camera space.
% The PCA background is not masked by the ROI.

% =====================================================================
% Hardcoded response files for the current demo session
% =====================================================================

integratedResponseFile = ...
    'Y:\Chip\Chip20230906\run2\M28D20230906R2StabIntgS004E023.mat';

trialStructureFile = ...
    'Y:\Chip\Chip20230906\run2\M28D20230906R2TS.mat';

stabilizationFile = ...
    'Y:\Chip\Chip20230906\run2\M28D20230906R2StabCfg.mat';

fprintf('Running plotDemoOptostim2 version 2026-06-29-coreg-layout-v11\n');

% =====================================================================
% 1. Orientation lookup
% =====================================================================

% Use imagingData.ortpca directly for the displayed PCA background.
% columnarProducts.VERpca is already multiplied by the ROI/SNR mask inside
% generateBitmap, so it cannot show activity outside that mask.
%
% Do not use ndims(...) here: MATLAB drops trailing singleton dimensions,
% so a valid 512x512xNortx1 array reports ndims == 3.
if ~isfield(imagingData, 'ortpca') || ...
        isempty(imagingData.ortpca) || ...
        size(imagingData.ortpca,1) ~= size(imagingData.ortpca,2) || ...
        size(imagingData.ortpca,4) < blockID

    error( ...
        'plotDemoOptostim:MissingFullPCA', ...
        ['imagingData.ortpca is unavailable or does not contain ' ...
         'blockID %d. Size found: [%s].'], ...
        blockID, num2str(size(imagingData.ortpca)));
end

pcaOrts = squeeze(imagingData.orts(1,:,blockID));
pcaOrts = pcaOrts(:)';

demoOrts = demoProducts.orts(:)';

coregOrts = squeeze(bitmapData.orts(1,:,blockID));
coregOrts = coregOrts(:)';

pcaIdx0 = demoFindOrientationIndex( ...
    pcaOrts, 0, 'full imaging PCA', currentSessID);

pcaIdx90 = demoFindOrientationIndex( ...
    pcaOrts, 90, 'full imaging PCA', currentSessID);

if size(imagingData.ortpca,3) < max([pcaIdx0 pcaIdx90])
    error( ...
        'plotDemoOptostim:MissingFullPCASlices', ...
        ['imagingData.ortpca has %d orientation slices, but indices ' ...
         '%d and %d were requested.'], ...
        size(imagingData.ortpca,3), pcaIdx0, pcaIdx90);
end

demoIdx0 = demoFindOrientationIndex( ...
    demoOrts, 0, 'demo bitmap', currentSessID);

demoIdx90 = demoFindOrientationIndex( ...
    demoOrts, 90, 'demo bitmap', currentSessID);

coregIdx0 = demoFindOrientationIndex( ...
    coregOrts, 0, 'coregistered bitmap', currentSessID);

coregIdx90 = demoFindOrientationIndex( ...
    coregOrts, 90, 'coregistered bitmap', currentSessID);

% =====================================================================
% 2. Reference-session PCA maps
% =====================================================================

% IMPORTANT: use the unmasked PCA-denoised responses from imagingData.
% VERpca is already ROI/SNR masked upstream and therefore cannot display
% the full field outside the ROI outline.
pca0Reference = double( ...
    imagingData.ortpca(:,:,pcaIdx0,blockID));

pca90Reference = double( ...
    imagingData.ortpca(:,:,pcaIdx90,blockID));

if ~any(isfinite(pca0Reference(:)))
    error( ...
        'plotDemoOptostim:EmptyPCA0', ...
        'Session %d: 0-degree PCA map has no finite pixels.', ...
        currentSessID);
end

if ~any(isfinite(pca90Reference(:)))
    error( ...
        'plotDemoOptostim:EmptyPCA90', ...
        'Session %d: 90-degree PCA map has no finite pixels.', ...
        currentSessID);
end

% =====================================================================
% 3. Current-camera column maps
% =====================================================================

columnMap0Current = double( ...
    bitmapData.columnarbitmapCoreg(:,:,coregIdx0,blockID));

columnMap90Current = double( ...
    bitmapData.columnarbitmapCoreg(:,:,coregIdx90,blockID));

if ~isequal(size(columnMap0Current), size(columnMap90Current))
    error( ...
        'plotDemoOptostim:CoregBitmapSizeMismatch', ...
        ['Session %d: 0-degree and 90-degree coregistered ' ...
         'column maps have different dimensions.'], ...
        currentSessID);
end

currentCameraRef = imref2d(size(columnMap0Current));

% =====================================================================
% 4. Warp PCA into current-session camera space
% =====================================================================

[pca0Current, pca90Current, validPcaMask] = ...
    demoWarpPcaToCurrentCamera( ...
        pca0Reference, ...
        pca90Reference, ...
        bitmapData, ...
        blockID, ...
        currentCameraRef);

% Keep the full coregistered PCA field. The ROI is displayed only as an
% outline and is not used to mask or multiply the PCA response.
pcaDifference = pca90Current - pca0Current;

% =====================================================================
% 5. Warp ROI into current-session camera space
% =====================================================================

if ~isfield(imagingData, 'nanmask') || ...
        size(imagingData.nanmask,3) < blockID

    error( ...
        'plotDemoOptostim:MissingROIMask', ...
        'imagingData.nanmask(:,:,blockID) is unavailable.');
end

roiReference = ...
    isfinite(imagingData.nanmask(:,:,blockID)) & ...
    imagingData.nanmask(:,:,blockID) ~= 0;

roiMask = demoWarpBinaryMaskToCurrentCamera( ...
    roiReference, ...
    bitmapData, ...
    blockID, ...
    currentCameraRef);

% =====================================================================
% 6. Orientation-specific Gaussian footprints
% =====================================================================

if ~isfield(demoProducts, 'gaussianMaskCamspace')
    error( ...
        'plotDemoOptostim:MissingGaussianMasks', ...
        'demoProducts.gaussianMaskCamspace is unavailable.');
end

gaussMask0 = ...
    demoProducts.gaussianMaskCamspace(:,:,demoIdx0) > 0.5;

gaussMask90 = ...
    demoProducts.gaussianMaskCamspace(:,:,demoIdx90) > 0.5;

if ~isequal(size(gaussMask0), size(columnMap0Current)) || ...
        ~isequal(size(gaussMask90), size(columnMap0Current))

    error( ...
        'plotDemoOptostim:GaussianSizeMismatch', ...
        ['Session %d: Gaussian masks do not match the ' ...
         'current-camera column-map dimensions.'], ...
        currentSessID);
end

% Plot only the larger of the two orientation-specific Gaussian footprints.
% Both original masks remain available for constructing their corresponding
% designed targets and for numerical output.
if nnz(gaussMask0) >= nnz(gaussMask90)

    gaussMaskLargest = gaussMask0;
    largestGaussianOrientation = 0;

else

    gaussMaskLargest = gaussMask90;
    largestGaussianOrientation = 90;
end

% =====================================================================
% 7. Designed pre-projector target columns
% =====================================================================

targetDesigned0 = demoBuildDesignedTarget( ...
    columnMap0Current, ...
    gaussMask0, ...
    bitmapData, ...
    coregIdx0, ...
    blockID);

targetDesigned90 = demoBuildDesignedTarget( ...
    columnMap90Current, ...
    gaussMask90, ...
    bitmapData, ...
    coregIdx90, ...
    blockID);

% The designed targets should be contained by their matching masks.

outsideGaussian0 = targetDesigned0 & ~gaussMask0;
outsideGaussian90 = targetDesigned90 & ~gaussMask90;

if any(outsideGaussian0(:))
    error( ...
        'plotDemoOptostim:TargetOutsideGaussian0', ...
        ['Session %d: %d designed 0-degree target pixels lie ' ...
         'outside the 0-degree Gaussian footprint.'], ...
        currentSessID, ...
        sum(outsideGaussian0(:)));
end

if any(outsideGaussian90(:))
    error( ...
        'plotDemoOptostim:TargetOutsideGaussian90', ...
        ['Session %d: %d designed 90-degree target pixels lie ' ...
         'outside the 90-degree Gaussian footprint.'], ...
        currentSessID, ...
        sum(outsideGaussian90(:)));
end

% =====================================================================
% 8. Recovered projector targets retained only for QC
% =====================================================================

if isfield(demoProducts, 'targetedColumnsCamspace')

    targetRecovered0Raw = double( ...
        demoProducts.targetedColumnsCamspace(:,:,demoIdx0));

    targetRecovered90Raw = double( ...
        demoProducts.targetedColumnsCamspace(:,:,demoIdx90));

    targetRecovered0 = ...
        isfinite(targetRecovered0Raw) & targetRecovered0Raw >= 0.5;

    targetRecovered90 = ...
        isfinite(targetRecovered90Raw) & targetRecovered90Raw >= 0.5;

else

    targetRecovered0 = false(size(targetDesigned0));
    targetRecovered90 = false(size(targetDesigned90));
end

% =====================================================================
% 9. Load actual 0%-contrast integrated opto-response difference
% =====================================================================

[zeroContrastOptoDifference, zeroContrastConditionInfo] = ...
    demoLoadZeroContrastOptoDifference( ...
        trialStructureFile, ...
        integratedResponseFile);

if ~isequal(size(zeroContrastOptoDifference), size(columnMap0Current))
    error( ...
        'plotDemoOptostim:IntegratedResponseSizeMismatch', ...
        ['Panel-B integrated response is [%d %d], but current-camera ' ...
         'products are [%d %d]. No automatic resizing was performed.'], ...
        size(zeroContrastOptoDifference,1), ...
        size(zeroContrastOptoDifference,2), ...
        size(columnMap0Current,1), ...
        size(columnMap0Current,2));
end

% =====================================================================
% 9b. Apply the stabilization offset and bandpass the measured response
% =====================================================================

bandpassSF = [0.8 3];  % cycles/mm

if ~isfield(zeroContrastConditionInfo, 'imagingSizePxl') || ...
        isempty(zeroContrastConditionInfo.imagingSizePxl) || ...
        ~isscalar(zeroContrastConditionInfo.imagingSizePxl) || ...
        ~isfinite(zeroContrastConditionInfo.imagingSizePxl) || ...
        zeroContrastConditionInfo.imagingSizePxl <= 0

    error( ...
        'plotDemoOptostim:MissingImagingSizePxl', ...
        'TS.Header.Imaging.SizePxl is missing or invalid.');
end

[meanStabilizationDx, meanStabilizationDy, stabilizationInfo] = ...
    demoLoadStabilizationOffsets(stabilizationFile);

% Register Panel B's measured activity to Panel A's PCA-denoised
% difference map. Panel A is the fixed image; Panel B is the moving image.
% The bitmap, ROI and Gaussian overlays remain fixed in current-camera
% coordinates.
activityTransformMode = 'rigid';
activityRegistrationSource = 'bandpass';

zeroContrastOptoDifferenceUnaligned = ...
    zeroContrastOptoDifference;

zeroContrastOptoDifferenceBandpassUnaligned = ...
    demoBandpassScalarMap( ...
        zeroContrastOptoDifferenceUnaligned, ...
        bandpassSF, ...
        zeroContrastConditionInfo.imagingSizePxl);

% Estimate the transform only from the valid imaging ROI. Erode the ROI
% slightly so the optimizer cannot lock onto the hard mask boundary. The
% displayed bitmap, ROI and Gaussian overlays remain completely fixed.
registrationMask = imerode( ...
    roiMask, ...
    strel('disk', 8, 0));

if nnz(registrationMask) < 500
    registrationMask = roiMask;
end

% The sign convention of refcfg.dx/dy is not explicit. Test full 2-D and
% horizontal-only stabilization seeds, then refine the measured activity
% with a constrained ROI-only rigid optimizer. Horizontal-only seeds are
% included because the
% visible mismatch appears mainly lateral while still being derived from
% the stabilization parameters rather than a manually imposed shift.
stabilizationCandidateLabels = { ...
    'no stabilization seed'; ...
    '+mean refcfg x/y seed'; ...
    '-mean refcfg x/y seed'; ...
    '+mean refcfg x-only seed'; ...
    '-mean refcfg x-only seed'};

stabilizationCandidateShiftsPx = [ ...
     0, 0; ...
     meanStabilizationDx, meanStabilizationDy; ...
    -meanStabilizationDx,-meanStabilizationDy; ...
     meanStabilizationDx, 0; ...
    -meanStabilizationDx, 0];

nStabilizationCandidates = ...
    size(stabilizationCandidateShiftsPx,1);

stabilizationRawCandidates = ...
    cell(nStabilizationCandidates,1);

stabilizationBandpassCandidates = ...
    cell(nStabilizationCandidates,1);

activityTransformCandidates = ...
    cell(nStabilizationCandidates,1);

activityTransformInfoCandidates = ...
    cell(nStabilizationCandidates,1);

stabilizationCandidateR = ...
    nan(nStabilizationCandidates,1);

stabilizationCandidateRSquared = ...
    nan(nStabilizationCandidates,1);

stabilizationCandidateNPixels = ...
    nan(nStabilizationCandidates,1);

candidateSelectionScores = ...
    -inf(nStabilizationCandidates,1);

for stabilizationCandidateIndex = 1:nStabilizationCandidates

    initialShift = ...
        stabilizationCandidateShiftsPx( ...
            stabilizationCandidateIndex,:);

    try
        [combinedTform, combinedInfo] = ...
            demoOptimizeRigidActivityTransform( ...
                pcaDifference, ...
                zeroContrastOptoDifferenceBandpassUnaligned, ...
                registrationMask, ...
                initialShift);

        combinedInfo.refinementSucceeded = true;

    catch registrationError

        warning( ...
            'plotDemoOptostim:RigidCandidateFallback', ...
            ['Rigid refinement failed for seed %s: %s. ' ...
             'Using the seed translation without rotation.'], ...
            stabilizationCandidateLabels{stabilizationCandidateIndex}, ...
            registrationError.message);

        combinedTform = affine2d([ ...
            1 0 0; ...
            0 1 0; ...
            initialShift(1) initialShift(2) 1]);

        combinedInfo = demoDecomposeAffine2D(combinedTform);
        combinedInfo.refinementSucceeded = false;
        combinedInfo.objectiveValue = NaN;
    end

    combinedInfo.initialShiftPx = initialShift;

    activityTransformCandidates{stabilizationCandidateIndex} = ...
        combinedTform;

    activityTransformInfoCandidates{stabilizationCandidateIndex} = ...
        combinedInfo;

    stabilizationRawCandidates{stabilizationCandidateIndex} = ...
        demoApplyGeometricTransform( ...
            zeroContrastOptoDifferenceUnaligned, ...
            combinedTform, ...
            size(pcaDifference), ...
            'linear');

    stabilizationBandpassCandidates{stabilizationCandidateIndex} = ...
        demoApplyGeometricTransform( ...
            zeroContrastOptoDifferenceBandpassUnaligned, ...
            combinedTform, ...
            size(pcaDifference), ...
            'linear');

    [stabilizationCandidateR(stabilizationCandidateIndex), ...
     stabilizationCandidateRSquared(stabilizationCandidateIndex), ...
     stabilizationCandidateNPixels(stabilizationCandidateIndex)] = ...
        demoPearsonRSquared( ...
            pcaDifference, ...
            stabilizationBandpassCandidates{ ...
                stabilizationCandidateIndex}, ...
            gaussMaskLargest);

    transformIsPlausible = ...
        all(isfinite(combinedInfo.translationPx)) && ...
        isfinite(combinedInfo.rotationDeg) && ...
        isfinite(combinedInfo.scaleX) && ...
        isfinite(combinedInfo.scaleY) && ...
        norm(combinedInfo.translationPx) <= 90 && ...
        abs(combinedInfo.rotationDeg) <= 20 && ...
        combinedInfo.scaleX >= 0.98 && ...
        combinedInfo.scaleX <= 1.02 && ...
        combinedInfo.scaleY >= 0.98 && ...
        combinedInfo.scaleY <= 1.02;

    if transformIsPlausible && ...
            isfinite(stabilizationCandidateRSquared( ...
                stabilizationCandidateIndex))

        candidateSelectionScores(stabilizationCandidateIndex) = ...
            stabilizationCandidateRSquared( ...
                stabilizationCandidateIndex);
    end
end

% Do not abort the whole pipeline if the refinement optimizer fails its
% plausibility checks. Fall back to the best finite candidate and warn.
if all(~isfinite(candidateSelectionScores)) || ...
        all(candidateSelectionScores == -Inf)

    finiteCandidateScores = stabilizationCandidateRSquared;
    finiteCandidateScores(~isfinite(finiteCandidateScores)) = -Inf;

    if all(finiteCandidateScores == -Inf)
        error( ...
            'plotDemoOptostim:ActivityRegistrationFailed', ...
            'Rigid activity registration produced no finite candidates.');
    end

    warning( ...
        'plotDemoOptostim:UsingBestUnconstrainedTransform', ...
        ['No candidate passed all rigid-transform plausibility limits. ' ...
         'Using the finite candidate with the highest Gaussian-region R^2.']);

    candidateSelectionScores = finiteCandidateScores;
end

[~, selectedStabilizationCandidate] = ...
    max(candidateSelectionScores);

activityTform = ...
    activityTransformCandidates{selectedStabilizationCandidate};

activityTransformInfo = ...
    activityTransformInfoCandidates{selectedStabilizationCandidate};

selectedStabilizationShiftPx = ...
    activityTransformInfo.translationPx;

selectedStabilizationLabel = sprintf( ...
    '%s + %s activity transform', ...
    stabilizationCandidateLabels{selectedStabilizationCandidate}, ...
    activityTransformMode);

zeroContrastOptoDifference = ...
    stabilizationRawCandidates{selectedStabilizationCandidate};

zeroContrastOptoDifferenceBandpass = ...
    stabilizationBandpassCandidates{selectedStabilizationCandidate};

% Apply the selected activity transform separately to the two underlying
% measured component maps. These remain unfiltered.
measuredActivity0CoregRaw = demoApplyGeometricTransform( ...
    zeroContrastConditionInfo.response0, ...
    activityTform, ...
    size(pcaDifference), ...
    'linear');

measuredActivity90CoregRaw = demoApplyGeometricTransform( ...
    zeroContrastConditionInfo.response90, ...
    activityTform, ...
    size(pcaDifference), ...
    'linear');

measuredActivityDifferenceCoregRaw = ...
    measuredActivity90CoregRaw - measuredActivity0CoregRaw;

pearsonR = ...
    stabilizationCandidateR(selectedStabilizationCandidate);

pearsonRSquared = ...
    stabilizationCandidateRSquared(selectedStabilizationCandidate);

nCorrelationPixels = ...
    stabilizationCandidateNPixels(selectedStabilizationCandidate);

if ~isequal(size(zeroContrastOptoDifferenceBandpass), ...
        size(zeroContrastOptoDifference))

    error( ...
        'plotDemoOptostim:BandpassSizeMismatch', ...
        ['Bandpassed response is [%d %d], while the aligned raw response ' ...
         'is [%d %d].'], ...
        size(zeroContrastOptoDifferenceBandpass,1), ...
        size(zeroContrastOptoDifferenceBandpass,2), ...
        size(zeroContrastOptoDifference,1), ...
        size(zeroContrastOptoDifference,2));
end

% =====================================================================
% 10. Validate masks and dimensions
% =====================================================================

demoValidateDimensions( ...
    pcaDifference, ...
    roiMask, ...
    gaussMask0, ...
    gaussMask90, ...
    targetDesigned0, ...
    targetDesigned90, ...
    zeroContrastOptoDifference);

if ~any(roiMask(:))
    error( ...
        'plotDemoOptostim:EmptyROI', ...
        'Session %d: coregistered ROI mask is empty.', ...
        currentSessID);
end

if ~any(gaussMask0(:))
    warning( ...
        'plotDemoOptostim:EmptyGaussian0', ...
        'Session %d: 0-degree Gaussian footprint is empty.', ...
        currentSessID);
end

if ~any(gaussMask90(:))
    warning( ...
        'plotDemoOptostim:EmptyGaussian90', ...
        'Session %d: 90-degree Gaussian footprint is empty.', ...
        currentSessID);
end

if ~any(targetDesigned0(:))
    error( ...
        'plotDemoOptostim:EmptyDesignedTarget0', ...
        'Session %d: designed 0-degree target is empty.', ...
        currentSessID);
end

if ~any(targetDesigned90(:))
    error( ...
        'plotDemoOptostim:EmptyDesignedTarget90', ...
        'Session %d: designed 90-degree target is empty.', ...
        currentSessID);
end

% =====================================================================
% 11. Physical coordinates
% =====================================================================

[xMM, yMM, pixelSizeMM] = demoComputeMMCoordinates( ...
    imagingData, ...
    blockID, ...
    pcaDifference);

% =====================================================================
% 12. Symmetric color limits
% =====================================================================

pcaColorLimits = demoSymmetricColorLimits( ...
    pcaDifference, ...
    validPcaMask & isfinite(pcaDifference), ...
    'PCA difference', ...
    currentSessID);

zeroContrastValidMask = isfinite(zeroContrastOptoDifference);

zeroContrastColorLimits = demoSymmetricColorLimits( ...
    zeroContrastOptoDifference, ...
    zeroContrastValidMask, ...
    '0%-contrast integrated response difference', ...
    currentSessID);

bandpassValidMask = ...
    isfinite(zeroContrastOptoDifferenceBandpass);

bandpassColorLimits = demoSymmetricColorLimits( ...
    zeroContrastOptoDifferenceBandpass, ...
    bandpassValidMask, ...
    '0%-contrast bandpassed response difference', ...
    currentSessID);

% Display-only copy: geometric warping leaves unsupported pixels as NaN,
% which appear as a light-gray strip. Zero is the midpoint of the shared
% symmetric c-axis, so use zero-valued padding for a neutral mean-gray edge.
zeroContrastOptoDifferenceBandpassDisplay = ...
    zeroContrastOptoDifferenceBandpass;

zeroContrastOptoDifferenceBandpassDisplay( ...
    ~isfinite(zeroContrastOptoDifferenceBandpassDisplay)) = 0;
% =====================================================================
% 13. Target overlap and projector QC
% =====================================================================

targetOverlap = ...
    targetDesigned0 & targetDesigned90;

nTargetOverlap = sum(targetOverlap(:));

if nTargetOverlap > 0
    warning( ...
        'plotDemoOptostim:DesignedTargetOverlap', ...
        ['Session %d: %d pixels overlap between designed ' ...
         '0-degree and 90-degree targets.'], ...
        currentSessID, ...
        nTargetOverlap);
end

diceRecovered0 = demoDiceCoefficient( ...
    targetDesigned0, ...
    targetRecovered0);

diceRecovered90 = demoDiceCoefficient( ...
    targetDesigned90, ...
    targetRecovered90);


% Use exactly the same designed current-camera target masks in Panels A
% and B. Do not substitute the projector-recovered masks here: that change
% produced a visibly worse overlay and mixes a different reconstruction
% pathway into the panel-to-panel comparison.
panelBTarget0 = targetDesigned0;
panelBTarget90 = targetDesigned90;
panelBTargetSource = 'same designed current-camera targets as Panel A';

panelBTargetOverlap = targetOverlap;
nPanelBTargetOverlap = nTargetOverlap;

% Mean stimulation metadata across the 0-degree and 90-degree patterns.
stimulationSummary = struct();

stimulationSummary.meanColumns = ...
    demoMeanBitmapMetric(bitmapData, 'nColumns', blockID);

stimulationSummary.meanPixelsON = ...
    demoMeanBitmapMetric(bitmapData, 'pixelsON', blockID);

stimulationSummary.meanTotalPower_mW = ...
    demoMeanBitmapMetric( ...
        bitmapData, ...
        'totalPowerToOnPixelsWithinROI_mW', ...
        blockID);

stimulationSummary.meanPowerDensityWithinROI_mWmm2 = ...
    demoMeanBitmapMetric( ...
        bitmapData, ...
        'meanPowerDensityWithinROI_mWmm2', ...
        blockID);

stimulationSummary.pearsonRSquared = pearsonRSquared;

% Fallbacks are used only if older bitmapData files lack the count fields.
if ~isfinite(stimulationSummary.meanColumns)
    connectedColumns0 = bwconncomp(targetDesigned0);
    connectedColumns90 = bwconncomp(targetDesigned90);
    stimulationSummary.meanColumns = mean([ ...
        connectedColumns0.NumObjects, ...
        connectedColumns90.NumObjects]);
end

if ~isfinite(stimulationSummary.meanPixelsON)
    stimulationSummary.meanPixelsON = mean([ ...
        nnz(targetDesigned0), ...
        nnz(targetDesigned90)]);
end

% =====================================================================
% 14. Diagnostics
% =====================================================================

fprintf('\n');
fprintf('--- Demo optostim diagnostics ---\n');
fprintf('Session:                         %d\n', currentSessID);
fprintf('Coordinate frame:                current-session camera\n');
fprintf('Registration direction:         Panel B activity -> Panel A PCA map\n');
fprintf('PCA orientations:                [%s]\n', num2str(pcaOrts));
fprintf('Bitmap orientations:             [%s]\n', num2str(coregOrts));
fprintf('Image dimensions:                %d x %d\n', ...
    size(pcaDifference,1), size(pcaDifference,2));
fprintf('Pixel size:                      %.6f mm/px\n', ...
    pixelSizeMM);
fprintf('ROI pixels:                      %d\n', ...
    sum(roiMask(:)));
fprintf('Finite PCA pixels outside ROI:   %d\n', ...
    nnz(isfinite(pcaDifference) & ~roiMask));
fprintf('0-deg Gaussian pixels:           %d\n', ...
    sum(gaussMask0(:)));
fprintf('90-deg Gaussian pixels:          %d\n', ...
    sum(gaussMask90(:)));
fprintf('Displayed Gaussian footprint:    %d deg (%d pixels)\n', ...
    largestGaussianOrientation, sum(gaussMaskLargest(:)));
fprintf('0-deg designed target pixels:    %d\n', ...
    sum(targetDesigned0(:)));
fprintf('90-deg designed target pixels:   %d\n', ...
    sum(targetDesigned90(:)));
fprintf('Designed target overlap:         %d\n', ...
    nTargetOverlap);
fprintf('0-deg recovered/design Dice:     %.4f\n', ...
    diceRecovered0);
fprintf('90-deg recovered/design Dice:    %.4f\n', ...
    diceRecovered90);
fprintf('PCA difference range:            [%.5g, %.5g]\n', ...
    min(pcaDifference(validPcaMask & isfinite(pcaDifference))), ...
    max(pcaDifference(validPcaMask & isfinite(pcaDifference))));
fprintf('Panel-B O00000 condition(s):     [%s]\n', ...
    num2str(zeroContrastConditionInfo.conditionIndices0));
fprintf('Panel-B O09000 condition(s):     [%s]\n', ...
    num2str(zeroContrastConditionInfo.conditionIndices90));
fprintf('Panel-B target overlay source:   %s\n', ...
    panelBTargetSource);
fprintf('Stabilization file:              %s\n', ...
    stabilizationFile);
fprintf('Stabilizer pixel size:           %.8f mm/px\n', ...
    stabilizationInfo.sizePxlMM);
fprintf('Mean refcfg dx, dy (native):     [%.4f, %.4f] mm\n', ...
    stabilizationInfo.meanDxNative, ...
    stabilizationInfo.meanDyNative);
fprintf('Mean refcfg dx, dy (converted):  [%.4f, %.4f] px\n', ...
    meanStabilizationDx, meanStabilizationDy);
fprintf('Selected activity translation:   [%.4f, %.4f] px\n', ...
    selectedStabilizationShiftPx(1), ...
    selectedStabilizationShiftPx(2));
fprintf('Selected convention:             %s\n', ...
    selectedStabilizationLabel);
fprintf('Selected rotation:               %.4f deg\n', ...
    activityTransformInfo.rotationDeg);
fprintf('Selected scale:                  [%.5f, %.5f]\n', ...
    activityTransformInfo.scaleX, ...
    activityTransformInfo.scaleY);
for stabilizationCandidateIndex = 1:nStabilizationCandidates
    candidateInfo = ...
        activityTransformInfoCandidates{stabilizationCandidateIndex};
    fprintf([ ...
        '  Candidate %-20s R^2=%.5f ' ...
        '(r=%.5f, n=%d, xy=[%.2f %.2f], rot=%.2f, ' ...
        'scale=[%.3f %.3f])\n'], ...
        stabilizationCandidateLabels{stabilizationCandidateIndex}, ...
        stabilizationCandidateRSquared(stabilizationCandidateIndex), ...
        stabilizationCandidateR(stabilizationCandidateIndex), ...
        stabilizationCandidateNPixels(stabilizationCandidateIndex), ...
        candidateInfo.translationPx(1), ...
        candidateInfo.translationPx(2), ...
        candidateInfo.rotationDeg, ...
        candidateInfo.scaleX, ...
        candidateInfo.scaleY);
end
fprintf('Panel A vs B Pearson r:          %.5f\n', pearsonR);
fprintf('Panel A vs B Pearson R^2:        %.5f (n=%d)\n', ...
    pearsonRSquared, nCorrelationPixels);
fprintf('Mean columns (0/90):             %.3f\n', ...
    stimulationSummary.meanColumns);
fprintf('Mean pixels ON (0/90):           %.3f\n', ...
    stimulationSummary.meanPixelsON);
fprintf('Mean total power (0/90):         %.5f mW\n', ...
    stimulationSummary.meanTotalPower_mW);
fprintf('Mean power density in ROI:       %.5f mW/mm^2\n', ...
    stimulationSummary.meanPowerDensityWithinROI_mWmm2);
fprintf('Panel-B raw response range:          [%.5g, %.5g]\n', ...
    min(zeroContrastOptoDifference(zeroContrastValidMask)), ...
    max(zeroContrastOptoDifference(zeroContrastValidMask)));
fprintf('---------------------------------\n');
fprintf('\n');

% =====================================================================
% 15. Create the two-panel figure
% =====================================================================

figHandle = figure( ...
    'Name', sprintf('demo-optostim_sess%d', currentSessID), ...
    'Color', 'white', ...
    'Units', 'inches', ...
    'Position', [0.35 0.55 20.5 7.4]);

% ---------------------------------------------------------------------
% Panel A: full unmasked PCA + targets + ROI + larger Gaussian footprint
% ---------------------------------------------------------------------

ax3 = subplot(1,2,1);

demoPlotScalarBackground( ...
    ax3, ...
    pcaDifference, ...
    xMM, ...
    yMM, ...
    pcaColorLimits);

hold(ax3, 'on');

[hTarget0C, hTarget90C] = demoPlotTargetOverlay( ...
    ax3, ...
    targetDesigned0, ...
    targetDesigned90, ...
    xMM, ...
    yMM, ...
    nTargetOverlap);

% Continuous ROI outline.
hRoiC = demoPlotMaskOutline( ...
    ax3, ...
    roiMask, ...
    pixelSizeMM, ...
    [0 0 0], ...
    '-', ...
    2.10, ...
    'ROI');

% Plot only the larger Gaussian footprint, in black dashed.
hGaussC = demoPlotMaskOutline( ...
    ax3, ...
    gaussMaskLargest, ...
    pixelSizeMM, ...
    [0 0 0], ...
    '--', ...
    0.85, ...
    sprintf('Gaussian footprint (%d%c)', ...
        largestGaussianOrientation, char(176)));

demoFormatAxes(ax3, xMM, yMM);

demoAddColorbar( ...
    ax3, ...
    ['PCA response: 90' char(176) ' - 0' char(176)]);

title( ...
    ax3, ...
    'Combined optostimulation targeting', ...
    'FontWeight', 'normal', ...
    'FontName', 'Arial', ...
    'FontSize', 12);

demoCreateTwoRowCombinedLegend( ...
    ax3, ...
    hTarget0C, ...
    hTarget90C, ...
    hRoiC, ...
    hGaussC);

panelLabelC = demoPanelLabel(ax3, 'A');

% ---------------------------------------------------------------------
% Panel B: bandpassed 0%-contrast OptoStim-90 minus OptoStim-0 response
% ---------------------------------------------------------------------

ax4 = subplot(1,2,2);

% Use the same display c-axis as Panel A for direct visual comparison.
demoPlotScalarBackground( ...
    ax4, ...
    zeroContrastOptoDifferenceBandpassDisplay, ...
    xMM, ...
    yMM, ...
    pcaColorLimits);

hold(ax4, 'on');

[hTarget0D, hTarget90D] = demoPlotTargetOverlay( ...
    ax4, ...
    panelBTarget0, ...
    panelBTarget90, ...
    xMM, ...
    yMM, ...
    nPanelBTargetOverlap);

% Continuous ROI outline.
hRoiD = demoPlotMaskOutline( ...
    ax4, ...
    roiMask, ...
    pixelSizeMM, ...
    [0 0 0], ...
    '-', ...
    2.10, ...
    'ROI');

% Plot only the larger Gaussian footprint, in black dashed.
hGaussD = demoPlotMaskOutline( ...
    ax4, ...
    gaussMaskLargest, ...
    pixelSizeMM, ...
    [0 0 0], ...
    '--', ...
    0.85, ...
    sprintf('Gaussian footprint (%d%c)', ...
        largestGaussianOrientation, char(176)));

demoFormatAxes(ax4, xMM, yMM);

demoAddColorbar( ...
    ax4, ...
    ['Bandpassed response: OptoStim 90' char(176) ...
     ' - OptoStim 0' char(176)]);

title( ...
    ax4, ...
    ['0% contrast: OptoStim 90' char(176) ...
     ' - OptoStim 0' char(176) ...
     ' (0.8-3 cycles/mm)'], ...
    'FontWeight', 'normal', ...
    'FontName', 'Arial', ...
    'FontSize', 12);


demoCreateTwoRowCombinedLegend( ...
    ax4, ...
    hTarget0D, ...
    hTarget90D, ...
    hRoiD, ...
    hGaussD);

panelLabelD = demoPanelLabel(ax4, 'B');

% =====================================================================
% 16. Equalize axes and apply the user's standard font treatment
% =====================================================================

drawnow;

demoEqualizeAxes([ax3 ax4]);

if exist('upFontSize', 'file') == 2

    axes(ax4);
    upFontSize(18, 0.01);
end

set( ...
    [ax3 ax4], ...
    'LineWidth', 2, ...
    'TickDir', 'out', ...
    'TickLength', [0.01 0.01], ...
    'FontName', 'Arial');

set( ...
    [panelLabelC panelLabelD], ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'FontName', 'Arial');

drawnow;
demoEqualizeAxes([ax3 ax4]);

% Reserve the right side of the figure for numerical summaries. The figure
% still contains only two data panels; the summary is an annotation outside
% both axes.
% Give the two image panels more horizontal room and reserve a narrower
% strip for the numerical summary.
set(ax3, 'Position', [0.050 0.235 0.300 0.615]);
set(ax4, 'Position', [0.445 0.235 0.300 0.615]);
drawnow;

summaryText = sprintf([ ...
    'STIMULATION SUMMARY\n' ...
    '(mean of 0%c and 90%c patterns)\n\n' ...
    'Columns: %.2f\n' ...
    'Pixels ON: %.0f\n' ...
    'Total power: %.4f mW\n' ...
    'ROI power density: %.4f mW/mm^2\n\n' ...
    'MAP COMPARISON\n' ...
    '(inside %d%c Gaussian)\n\n' ...
    'Pearson r: %.4f\n' ...
    'Pearson R^2: %.4f\n' ...
    'Compared pixels: %d'], ...
    char(176), char(176), ...
    stimulationSummary.meanColumns, ...
    stimulationSummary.meanPixelsON, ...
    stimulationSummary.meanTotalPower_mW, ...
    stimulationSummary.meanPowerDensityWithinROI_mWmm2, ...
    largestGaussianOrientation, char(176), ...
    pearsonR, ...
    pearsonRSquared, ...
    nCorrelationPixels);

summaryTextBox = annotation( ...
    figHandle, ...
    'textbox', ...
    [0.825 0.245 0.140 0.500], ...
    'String', summaryText, ...
    'FitBoxToText', 'off', ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'top', ...
    'FontName', 'Arial', ...
    'FontSize', 10.0, ...
    'FontWeight', 'normal', ...
    'LineStyle', 'none', ...
    'EdgeColor', 'none', ...
    'BackgroundColor', 'none', ...
    'Margin', 2);

drawnow;

% =====================================================================
% 17. Package numerical outputs
% =====================================================================

experimentMetadata = demoParseExperimentMetadata( ...
    integratedResponseFile, ...
    monkeyName, ...
    currentBlockStruct);

% This is the complete and intentionally minimal mapData struct written
% to the MAT file.
mapData = struct();

mapData.animalName = experimentMetadata.animalName;
mapData.experimentDate = experimentMetadata.experimentDate;
mapData.experimentRun = experimentMetadata.experimentRun;

mapData.bitmapNames0 = unique( ...
    zeroContrastConditionInfo.projectorImages0, ...
    'stable');

mapData.bitmapNames90 = unique( ...
    zeroContrastConditionInfo.projectorImages90, ...
    'stable');

% Panel-A PCA-denoised activity after vasculature coregistration.
mapData.pcaDenoised0Coreg = pca0Current;
mapData.pcaDenoised90Coreg = pca90Current;
mapData.pcaDenoisedDifference90Minus0Coreg = pcaDifference;

% Panel-B measured activity after the selected rigid registration.
mapData.measuredActivity0CoregRaw = measuredActivity0CoregRaw;
mapData.measuredActivity90CoregRaw = measuredActivity90CoregRaw;
mapData.measuredActivityDifference90Minus0CoregRaw = ...
    measuredActivityDifferenceCoregRaw;

% Exact bandpassed difference displayed in Panel B.
mapData.measuredActivityDifference90Minus0CoregBandpass = ...
    zeroContrastOptoDifferenceBandpass;

% Current-camera masks and displayed bitmaps.
mapData.roiMask = logical(roiMask);
mapData.gaussianMask0 = logical(gaussMask0);
mapData.gaussianMask90 = logical(gaussMask90);
mapData.displayedGaussianFootprint = logical(gaussMaskLargest);
mapData.bitmap0 = logical(targetDesigned0);
mapData.bitmap90 = logical(targetDesigned90);

demoValidateMinimalMapData(mapData, [512 512]);

signedTargetMap = nan(size(targetDesigned0), 'double');
signedTargetMap(targetDesigned0) = -1;
signedTargetMap(targetDesigned90) = 1;

demoPlotData = struct();

demoPlotData.coordinateFrame = ...
    'current-session camera, pre-projector';

demoPlotData.pca0Reference = pca0Reference;
demoPlotData.pca90Reference = pca90Reference;

demoPlotData.pca0Current = pca0Current;
demoPlotData.pca90Current = pca90Current;
demoPlotData.pcaDifference = pcaDifference;

demoPlotData.validPcaMask = validPcaMask;
demoPlotData.roiMaskCurrent = roiMask;

demoPlotData.gaussianMask0Current = gaussMask0;
demoPlotData.gaussianMask90Current = gaussMask90;

demoPlotData.gaussianMaskLargestCurrent = gaussMaskLargest;
demoPlotData.largestGaussianOrientation = largestGaussianOrientation;

demoPlotData.targetDesigned0Current = targetDesigned0;
demoPlotData.targetDesigned90Current = targetDesigned90;

demoPlotData.targetRecovered0Current = targetRecovered0;
demoPlotData.targetRecovered90Current = targetRecovered90;

demoPlotData.recoveredDesignDice0 = diceRecovered0;
demoPlotData.recoveredDesignDice90 = diceRecovered90;

demoPlotData.panelBTarget0Current = panelBTarget0;
demoPlotData.panelBTarget90Current = panelBTarget90;
demoPlotData.panelBTargetSource = panelBTargetSource;
demoPlotData.panelBActivityTransformApplied = ...
    selectedStabilizationLabel;

demoPlotData.stabilizationFile = stabilizationFile;
demoPlotData.stabilizationInfo = stabilizationInfo;
demoPlotData.stabilizationSizePxlMM = ...
    stabilizationInfo.sizePxlMM;
demoPlotData.meanStabilizationDxNativeMM = ...
    stabilizationInfo.meanDxNative;
demoPlotData.meanStabilizationDyNativeMM = ...
    stabilizationInfo.meanDyNative;
demoPlotData.meanStabilizationDxPx = meanStabilizationDx;
demoPlotData.meanStabilizationDyPx = meanStabilizationDy;
demoPlotData.stabilizationCandidateLabels = ...
    stabilizationCandidateLabels;
demoPlotData.stabilizationCandidateShiftsPx = ...
    stabilizationCandidateShiftsPx;
activityTransformCandidateMatrices = ...
    cell(nStabilizationCandidates,1);

for activityCandidateIndex = 1:nStabilizationCandidates
    activityTransformCandidateMatrices{activityCandidateIndex} = ...
        activityTransformCandidates{activityCandidateIndex}.T;
end

demoPlotData.activityTransformCandidateMatrices = ...
    activityTransformCandidateMatrices;
demoPlotData.activityTransformInfoCandidates = ...
    activityTransformInfoCandidates;
demoPlotData.stabilizationCandidateR = ...
    stabilizationCandidateR;
demoPlotData.stabilizationCandidateRSquared = ...
    stabilizationCandidateRSquared;
demoPlotData.stabilizationCandidateNPixels = ...
    stabilizationCandidateNPixels;
demoPlotData.stabilizationRawCandidates = ...
    stabilizationRawCandidates;
demoPlotData.stabilizationBandpassCandidates = ...
    stabilizationBandpassCandidates;
demoPlotData.selectedStabilizationCandidate = ...
    selectedStabilizationCandidate;
demoPlotData.selectedStabilizationShiftPx = ...
    selectedStabilizationShiftPx;
demoPlotData.selectedStabilizationLabel = ...
    selectedStabilizationLabel;
demoPlotData.activityTransformMode = activityTransformMode;
demoPlotData.activityRegistrationSource = activityRegistrationSource;
demoPlotData.activityTransformMatrix = activityTransformInfo.matrix;
demoPlotData.activityTransformTranslationPx = activityTransformInfo.translationPx;
demoPlotData.activityTransformRotationDeg = activityTransformInfo.rotationDeg;
demoPlotData.activityTransformScale = [activityTransformInfo.scaleX, activityTransformInfo.scaleY];
demoPlotData.activityRegistrationMask = registrationMask;

demoPlotData.stimulationSummary = stimulationSummary;

demoPlotData.pearsonRWithinLargestGaussian = pearsonR;
demoPlotData.pearsonRSquaredWithinLargestGaussian = pearsonRSquared;
demoPlotData.nCorrelationPixelsWithinLargestGaussian = nCorrelationPixels;

demoPlotData.signedTargetMap = signedTargetMap;

demoPlotData.zeroContrastOptoDifferenceUnaligned = ...
    zeroContrastOptoDifferenceUnaligned;

demoPlotData.zeroContrastOptoDifference = ...
    zeroContrastOptoDifference;

demoPlotData.zeroContrastConditionInfo = ...
    zeroContrastConditionInfo;

demoPlotData.integratedResponseFile = ...
    integratedResponseFile;

demoPlotData.trialStructureFile = ...
    trialStructureFile;

demoPlotData.xMM = xMM;
demoPlotData.yMM = yMM;

demoPlotData.pcaColorLimits = pcaColorLimits;
demoPlotData.zeroContrastColorLimits = zeroContrastColorLimits;

demoPlotData.zeroContrastOptoDifferenceBandpassUnaligned = ...
    zeroContrastOptoDifferenceBandpassUnaligned;

demoPlotData.zeroContrastOptoDifferenceBandpass = ...
    zeroContrastOptoDifferenceBandpass;

demoPlotData.bandpassSFcyclesPerMM = bandpassSF;
demoPlotData.bandpassColorLimits = bandpassColorLimits;
demoPlotData.sharedDisplayColorLimits = pcaColorLimits;

% =====================================================================
% 18. Save SVG and PNG
% =====================================================================

outputFiles = demoSaveOutputs( ...
    figHandle, ...
    mapData, ...
    stimulationSummary, ...
    mainPath, ...
    monkeyName, ...
    chamberWanted, ...
    currentSessID, ...
    currentBlockStruct, ...
    saveFlag);

end


% =====================================================================
% Find an orientation index
% =====================================================================

function orientationIndex = demoFindOrientationIndex( ...
        orientations, wantedOrientation, sourceName, currentSessID)

    orientationIndex = find( ...
        isfinite(orientations) & ...
        orientations == wantedOrientation, ...
        1, ...
        'first');

    if isempty(orientationIndex)

        error( ...
            'plotDemoOptostim:MissingOrientation', ...
            ['Session %d: %d-degree orientation is missing from %s. ' ...
             'Available orientations: [%s].'], ...
            currentSessID, ...
            wantedOrientation, ...
            sourceName, ...
            num2str(orientations));
    end
end


% =====================================================================
% Warp PCA into current-session camera space
% =====================================================================

function [pca0Current, pca90Current, validMask] = ...
        demoWarpPcaToCurrentCamera( ...
            pca0Reference, ...
            pca90Reference, ...
            bitmapData, ...
            blockID, ...
            outputRef)

    transformReferenceToCurrent = ...
        demoGetReferenceToCurrentTransform(bitmapData, blockID);

    valid0Reference = isfinite(pca0Reference);
    valid90Reference = isfinite(pca90Reference);

    pca0Filled = pca0Reference;
    pca90Filled = pca90Reference;

    pca0Filled(~valid0Reference) = 0;
    pca90Filled(~valid90Reference) = 0;

    pca0Current = imwarp( ...
        pca0Filled, ...
        transformReferenceToCurrent, ...
        'linear', ...
        'OutputView', outputRef, ...
        'FillValues', 0);

    pca90Current = imwarp( ...
        pca90Filled, ...
        transformReferenceToCurrent, ...
        'linear', ...
        'OutputView', outputRef, ...
        'FillValues', 0);

    valid0Current = imwarp( ...
        double(valid0Reference), ...
        transformReferenceToCurrent, ...
        'linear', ...
        'OutputView', outputRef, ...
        'FillValues', 0);

    valid90Current = imwarp( ...
        double(valid90Reference), ...
        transformReferenceToCurrent, ...
        'linear', ...
        'OutputView', outputRef, ...
        'FillValues', 0);

    validMask = ...
        valid0Current > 0.999 & ...
        valid90Current > 0.999;

    % Do not mask the PCA maps with the finite-support/ROI mask. The mask is
    % returned only for diagnostics and color-limit estimation.
end


% =====================================================================
% Warp a binary reference mask into current-session camera space
% =====================================================================

function currentMask = demoWarpBinaryMaskToCurrentCamera( ...
        referenceMask, bitmapData, blockID, outputRef)

    transformReferenceToCurrent = ...
        demoGetReferenceToCurrentTransform(bitmapData, blockID);

    currentMask = imwarp( ...
        double(referenceMask), ...
        transformReferenceToCurrent, ...
        'nearest', ...
        'OutputView', outputRef, ...
        'FillValues', 0) > 0.5;
end


% =====================================================================
% Retrieve the vasculature transform
% =====================================================================

function transformReferenceToCurrent = ...
        demoGetReferenceToCurrentTransform(bitmapData, blockID)

    if ~isfield(bitmapData, 'transformParams') || ...
            numel(bitmapData.transformParams) < blockID || ...
            isempty(bitmapData.transformParams{blockID})

        error( ...
            'plotDemoOptostim:MissingVasculatureTransform', ...
            'bitmapData.transformParams{%d} is missing or empty.', ...
            blockID);
    end

    transformReferenceToCurrent = ...
        bitmapData.transformParams{blockID};
end


% =====================================================================
% Reconstruct a designed pre-projector target
% =====================================================================

function targetMask = demoBuildDesignedTarget( ...
        coregisteredColumnMap, ...
        gaussianMask, ...
        bitmapData, ...
        bitmapIndex, ...
        blockID)

    targetMask = ...
        coregisteredColumnMap > 0.5 & ...
        gaussianMask;

    if isfield(bitmapData, 'nColumnsWanted') && ...
            size(bitmapData.nColumnsWanted,2) >= bitmapIndex && ...
            size(bitmapData.nColumnsWanted,3) >= blockID

        nColumnsWanted = ...
            bitmapData.nColumnsWanted(1,bitmapIndex,blockID);

        contourLevel = NaN;

        if isfield(bitmapData, 'gaussianContourLevel') && ...
                size(bitmapData.gaussianContourLevel,2) >= bitmapIndex && ...
                size(bitmapData.gaussianContourLevel,3) >= blockID

            contourLevel = ...
                bitmapData.gaussianContourLevel(1,bitmapIndex,blockID);
        end

        if isfinite(nColumnsWanted) && ...
                nColumnsWanted == 1 && ...
                isfinite(contourLevel) && ...
                contourLevel < 200

            targetMask = bwareaopen(targetMask, 300);
        end
    end
end


% =====================================================================
% Load Panel-B integrated response
% =====================================================================

function [differenceMap, conditionInfo] = ...
        demoLoadZeroContrastOptoDifference( ...
            trialStructureFile, ...
            integratedResponseFile)
    
    if exist(trialStructureFile, 'file') ~= 2
        error( ...
            'plotDemoOptostim:MissingTSFile', ...
            'Could not find TS file: %s', ...
            trialStructureFile);
    end

    if exist(integratedResponseFile, 'file') ~= 2
        error( ...
            'plotDemoOptostim:MissingIntegratedResponseFile', ...
            'Could not find integrated-response file: %s', ...
            integratedResponseFile);
    end

    tsLoaded = load(trialStructureFile, 'TS');
    responseLoaded = load(integratedResponseFile, 'DataCond');

    if ~isfield(tsLoaded, 'TS')
        error( ...
            'plotDemoOptostim:MissingTSVariable', ...
            'The file %s does not contain TS.', ...
            trialStructureFile);
    end

    if ~isfield(responseLoaded, 'DataCond')
        error( ...
            'plotDemoOptostim:MissingDataCond', ...
            'The file %s does not contain DataCond.', ...
            integratedResponseFile);
    end

    TS = tsLoaded.TS;
    DataCond = responseLoaded.DataCond;

    if ~isfield(TS.Header, 'Imaging') || ...
            ~isfield(TS.Header.Imaging, 'SizePxl') || ...
            isempty(TS.Header.Imaging.SizePxl)
    
        error( ...
            'plotDemoOptostim:MissingImagingSizePxl', ...
            'TS.Header.Imaging.SizePxl is unavailable.');
    end
    
    imagingSizePxl = double(TS.Header.Imaging.SizePxl);
    
    if ~isscalar(imagingSizePxl) || ...
            ~isfinite(imagingSizePxl) || ...
            imagingSizePxl <= 0
    
        error( ...
            'plotDemoOptostim:InvalidImagingSizePxl', ...
            'TS.Header.Imaging.SizePxl must be a positive scalar.');
    end

    if ~isfield(TS, 'Header') || ...
            ~isfield(TS.Header, 'Conditions')

        error( ...
            'plotDemoOptostim:MissingConditions', ...
            'TS.Header.Conditions is unavailable.');
    end

    conditions = TS.Header.Conditions;

    requiredFields = { ...
        'StimCon', ...
        'ProjImg'};

    for fieldIndex = 1:numel(requiredFields)

        if ~isfield(conditions, requiredFields{fieldIndex})

            error( ...
                'plotDemoOptostim:MissingConditionField', ...
                'TS.Header.Conditions.%s is unavailable.', ...
                requiredFields{fieldIndex});
        end
    end

    stimContrast = double(conditions.StimCon(:));

    nConditions = numel(stimContrast);

    if size(DataCond,3) ~= nConditions

        error( ...
            'plotDemoOptostim:DataCondConditionMismatch', ...
            ['DataCond contains %d condition slices, while TS defines ' ...
             '%d conditions.'], ...
            size(DataCond,3), ...
            nConditions);
    end

    projectorImages = demoNormalizeProjImgList( ...
        conditions.ProjImg, ...
        nConditions);

    isZeroDegreeBitmap = false(nConditions,1);
    isNinetyDegreeBitmap = false(nConditions,1);

    for conditionIndex = 1:nConditions

        imageBaseName = demoImageBaseName( ...
            projectorImages{conditionIndex});

        isZeroDegreeBitmap(conditionIndex) = ...
            strncmpi(imageBaseName, 'O00000', 6);

        isNinetyDegreeBitmap(conditionIndex) = ...
            strncmpi(imageBaseName, 'O09000', 6);
    end

    isOptoCondition = true(nConditions,1);

    if isfield(conditions, 'TypeCond')

        typeCondition = double(conditions.TypeCond(:));

        if numel(typeCondition) == nConditions
            isOptoCondition = typeCondition == 3;
        end
    end

    commonSelection = ...
        stimContrast == 0 & ...
        isOptoCondition;

    conditionIndices0 = find( ...
        commonSelection & ...
        isZeroDegreeBitmap);

    conditionIndices90 = find( ...
        commonSelection & ...
        isNinetyDegreeBitmap);

    if isempty(conditionIndices0)

        error( ...
            'plotDemoOptostim:MissingZeroContrastO00000', ...
            'No 0%%-contrast O00000 optostimulation condition was found.');
    end

    if isempty(conditionIndices90)

        error( ...
            'plotDemoOptostim:MissingZeroContrastO09000', ...
            'No 0%%-contrast O09000 optostimulation condition was found.');
    end

    response0 = demoMeanConditionMaps( ...
        DataCond, ...
        conditionIndices0);

    response90 = demoMeanConditionMaps( ...
        DataCond, ...
        conditionIndices90);

    differenceMap = response90 - response0;

    conditionInfo = struct();
    conditionInfo.conditionIndices0 = ...
        conditionIndices0(:)';

    conditionInfo.conditionIndices90 = ...
        conditionIndices90(:)';

    conditionInfo.projectorImages0 = ...
        projectorImages(conditionIndices0);

    conditionInfo.projectorImages90 = ...
        projectorImages(conditionIndices90);

    conditionInfo.response0 = response0;
    conditionInfo.response90 = response90;

    conditionInfo.imagingSizePxl = imagingSizePxl;
end


% =====================================================================
% Load mean stabilization offsets from a StabCfg file
% =====================================================================

function [meanDxPx, meanDyPx, stabilizationInfo] = ...
        demoLoadStabilizationOffsets(stabilizationFile)

    if exist(stabilizationFile, 'file') ~= 2
        error( ...
            'plotDemoOptostim:MissingStabilizationFile', ...
            'Could not find stabilization file: %s', ...
            stabilizationFile);
    end

    % This StabCfg contains both:
    %   refcfg.dx/refcfg.dy : reference-level translations
    %   ipu.SizePxl        : physical pixel size in mm/pixel
    %
    % The saved dx/dy values are in the same physical units as SizePxl,
    % not display pixels. Convert them to pixels before calling imwarp.
    loadedStabilization = load( ...
        stabilizationFile, ...
        'refcfg', ...
        'ipu');

    if ~isfield(loadedStabilization, 'refcfg') || ...
            ~isfield(loadedStabilization.refcfg, 'dx') || ...
            ~isfield(loadedStabilization.refcfg, 'dy')

        error( ...
            'plotDemoOptostim:MissingStabilizationOffsets', ...
            ['The stabilization file does not contain ' ...
             'refcfg.dx and refcfg.dy.']);
    end

    if ~isfield(loadedStabilization, 'ipu') || ...
            ~isfield(loadedStabilization.ipu, 'SizePxl') || ...
            isempty(loadedStabilization.ipu.SizePxl)

        error( ...
            'plotDemoOptostim:MissingStabilizationPixelSize', ...
            ['The stabilization file does not contain ' ...
             'ipu.SizePxl for conversion to pixels.']);
    end

    sizePxlMM = double(loadedStabilization.ipu.SizePxl);

    if ~isscalar(sizePxlMM) || ...
            ~isfinite(sizePxlMM) || ...
            sizePxlMM <= 0

        error( ...
            'plotDemoOptostim:InvalidStabilizationPixelSize', ...
            'ipu.SizePxl must be a positive finite scalar.');
    end

    dxValuesNative = ...
        double(loadedStabilization.refcfg.dx(:));

    dyValuesNative = ...
        double(loadedStabilization.refcfg.dy(:));

    finiteDxNative = ...
        dxValuesNative(isfinite(dxValuesNative));

    finiteDyNative = ...
        dyValuesNative(isfinite(dyValuesNative));

    if isempty(finiteDxNative) || isempty(finiteDyNative)
        error( ...
            'plotDemoOptostim:EmptyStabilizationOffsets', ...
            'refcfg.dx or refcfg.dy contains no finite values.');
    end

    meanDxNative = mean(finiteDxNative);
    meanDyNative = mean(finiteDyNative);

    meanDxPx = meanDxNative / sizePxlMM;
    meanDyPx = meanDyNative / sizePxlMM;

    stabilizationInfo = struct();
    stabilizationInfo.file = stabilizationFile;
    stabilizationInfo.sizePxlMM = sizePxlMM;
    stabilizationInfo.nativeUnits = 'mm';
    stabilizationInfo.nDx = numel(finiteDxNative);
    stabilizationInfo.nDy = numel(finiteDyNative);

    stabilizationInfo.meanDxNative = meanDxNative;
    stabilizationInfo.meanDyNative = meanDyNative;
    stabilizationInfo.medianDxNative = median(finiteDxNative);
    stabilizationInfo.medianDyNative = median(finiteDyNative);
    stabilizationInfo.minDxNative = min(finiteDxNative);
    stabilizationInfo.maxDxNative = max(finiteDxNative);
    stabilizationInfo.minDyNative = min(finiteDyNative);
    stabilizationInfo.maxDyNative = max(finiteDyNative);

    stabilizationInfo.meanDxPx = meanDxPx;
    stabilizationInfo.meanDyPx = meanDyPx;
    stabilizationInfo.medianDxPx = ...
        stabilizationInfo.medianDxNative / sizePxlMM;
    stabilizationInfo.medianDyPx = ...
        stabilizationInfo.medianDyNative / sizePxlMM;
    stabilizationInfo.minDxPx = ...
        stabilizationInfo.minDxNative / sizePxlMM;
    stabilizationInfo.maxDxPx = ...
        stabilizationInfo.maxDxNative / sizePxlMM;
    stabilizationInfo.minDyPx = ...
        stabilizationInfo.minDyNative / sizePxlMM;
    stabilizationInfo.maxDyPx = ...
        stabilizationInfo.maxDyNative / sizePxlMM;
end

% =====================================================================
% Translate a scalar map while preserving its finite-data support
% =====================================================================

function shiftedMap = demoTranslateScalarMap(imageData, dxPixels, dyPixels)

    imageData = double(imageData);
    validMask = isfinite(imageData);

    filledImage = imageData;
    filledImage(~validMask) = 0;

    outputRef = imref2d(size(imageData));

    translationTransform = affine2d([ ...
        1, 0, 0; ...
        0, 1, 0; ...
        dxPixels, dyPixels, 1]);

    shiftedMap = imwarp( ...
        filledImage, ...
        translationTransform, ...
        'linear', ...
        'OutputView', outputRef, ...
        'FillValues', 0);

    shiftedValidity = imwarp( ...
        double(validMask), ...
        translationTransform, ...
        'linear', ...
        'OutputView', outputRef, ...
        'FillValues', 0);

    shiftedMap(shiftedValidity < 0.999) = NaN;
end


% =====================================================================
% Apply the standard Fermi spatial bandpass to one scalar map
% =====================================================================

function bandpassedMap = ...
        demoBandpassScalarMap(imageData, bandpassSF, imagingSizePxl)

    imageData = double(imageData);
    validMask = isfinite(imageData);

    filterInput = imageData;
    filterInput(~validMask) = 0;

    bandpassedMap = FilterFermi3D( ...
        filterInput, ...
        bandpassSF(1), ...
        bandpassSF(2), ...
        imagingSizePxl);

    bandpassedMap = real(bandpassedMap);
    bandpassedMap(~validMask) = NaN;
end


% =====================================================================
% Mean one bitmap metric across the two orientation patterns
% =====================================================================

function meanValue = ...
        demoMeanBitmapMetric(bitmapData, fieldName, blockID)

    meanValue = NaN;

    if ~isfield(bitmapData, fieldName) || ...
            isempty(bitmapData.(fieldName))
        return;
    end

    fieldData = double(bitmapData.(fieldName));

    orientationByBlockFields = { ...
        'nColumns', ...
        'pixelsON'};

    orientationInSecondDimensionFields = { ...
        'totalPowerToOnPixelsWithinROI_mW', ...
        'meanPowerDensityWithinROI_mWmm2', ...
        'projectorPowerDensity_mWmm2', ...
        'temporalDutyCycle'};

    if any(strcmp(fieldName, orientationByBlockFields))

        if size(fieldData,2) < blockID
            return;
        end

        blockValues = fieldData(:,blockID);

    elseif any(strcmp(fieldName, ...
            orientationInSecondDimensionFields))

        if ndims(fieldData) >= 3

            if size(fieldData,3) < blockID
                return;
            end

            blockValues = fieldData(:,:,blockID);

        elseif blockID == 1

            % MATLAB suppresses a trailing singleton third dimension, so
            % [1 x 2 x 1] may appear as [1 x 2]. In that case both values
            % still belong to block 1 and must both be averaged.
            blockValues = fieldData;

        else

            return;
        end

    else

        % Conservative generic fallback for any later metric.
        if ndims(fieldData) >= 3

            if size(fieldData, ndims(fieldData)) < blockID
                return;
            end

            indices = repmat({':'}, 1, ndims(fieldData));
            indices{end} = blockID;
            blockValues = fieldData(indices{:});

        elseif size(fieldData,2) >= blockID

            blockValues = fieldData(:,blockID);

        elseif size(fieldData,1) >= blockID

            blockValues = fieldData(blockID,:);

        else

            return;
        end
    end

    blockValues = blockValues(isfinite(blockValues));

    if isempty(blockValues)
        return;
    end

    meanValue = mean(blockValues(:));
end


% =====================================================================
% Pearson r and r-squared within a binary comparison mask
% =====================================================================

function [pearsonR, pearsonRSquared, nPixels] = ...
        demoPearsonRSquared(mapA, mapB, comparisonMask)

    validMask = ...
        logical(comparisonMask) & ...
        isfinite(mapA) & ...
        isfinite(mapB);

    valuesA = double(mapA(validMask));
    valuesB = double(mapB(validMask));

    nPixels = numel(valuesA);

    if nPixels < 3 || std(valuesA) == 0 || std(valuesB) == 0

        pearsonR = NaN;
        pearsonRSquared = NaN;
        return;
    end

    correlationMatrix = corrcoef(valuesA, valuesB);
    pearsonR = correlationMatrix(1,2);
    pearsonRSquared = pearsonR.^2;
end


% =====================================================================
% Normalize TS.Header.Conditions.ProjImg into a cell array of char
% =====================================================================

function imageList = demoNormalizeProjImgList(projectorImages, nConditions)

    imageList = cell(nConditions,1);

    if iscell(projectorImages)

        if numel(projectorImages) ~= nConditions
            error( ...
                'plotDemoOptostim:ProjImgLengthMismatch', ...
                'ProjImg contains %d entries; expected %d.', ...
                numel(projectorImages), ...
                nConditions);
        end

        for conditionIndex = 1:nConditions
            imageList{conditionIndex} = ...
                demoConvertProjImgEntry(projectorImages{conditionIndex});
        end

        return;
    end

    if isstring(projectorImages)

        if numel(projectorImages) ~= nConditions
            error( ...
                'plotDemoOptostim:ProjImgLengthMismatch', ...
                'ProjImg contains %d entries; expected %d.', ...
                numel(projectorImages), ...
                nConditions);
        end

        for conditionIndex = 1:nConditions
            imageList{conditionIndex} = ...
                char(projectorImages(conditionIndex));
        end

        return;
    end

    if ischar(projectorImages)

        if nConditions == 1

            imageList{1} = strtrim(projectorImages);
            return;
        end

        if size(projectorImages,1) == nConditions

            for conditionIndex = 1:nConditions
                imageList{conditionIndex} = ...
                    strtrim(projectorImages(conditionIndex,:));
            end

            return;
        end
    end

    error( ...
        'plotDemoOptostim:UnsupportedProjImgType', ...
        'Unsupported TS.Header.Conditions.ProjImg representation.');
end


% =====================================================================
% Convert one ProjImg entry into char
% =====================================================================

function imageName = demoConvertProjImgEntry(entry)

    if isempty(entry)

        imageName = '';
        return;
    end

    if ischar(entry)

        imageName = strtrim(entry);
        return;
    end

    if isstring(entry)

        imageName = char(entry);
        return;
    end

    imageName = '';
end


% =====================================================================
% Extract an image basename from either slash convention
% =====================================================================

function imageBaseName = demoImageBaseName(imagePath)

    if isempty(imagePath)

        imageBaseName = '';
        return;
    end

    imageBaseName = regexp( ...
        imagePath, ...
        '[^\\/]+$', ...
        'match', ...
        'once');

    if isempty(imageBaseName)
        imageBaseName = imagePath;
    end
end


% =====================================================================
% Average selected condition maps with NaN handling
% =====================================================================

function meanMap = demoMeanConditionMaps(DataCond, conditionIndices)

    selectedData = double(DataCond(:,:,conditionIndices));

    finiteMask = isfinite(selectedData);

    selectedData(~finiteMask) = 0;

    finiteCount = sum(finiteMask,3);
    dataSum = sum(selectedData,3);

    meanMap = dataSum ./ finiteCount;
    meanMap(finiteCount == 0) = NaN;
end


% =====================================================================
% Validate array dimensions
% =====================================================================

function demoValidateDimensions( ...
        pcaDifference, ...
        roiMask, ...
        gaussMask0, ...
        gaussMask90, ...
        target0, ...
        target90, ...
        zeroContrastOptoDifference)

    expectedSize = size(pcaDifference);

    arrays = { ...
        roiMask, ...
        gaussMask0, ...
        gaussMask90, ...
        target0, ...
        target90, ...
        zeroContrastOptoDifference};

    arrayNames = { ...
        'roiMask', ...
        'gaussMask0', ...
        'gaussMask90', ...
        'target0', ...
        'target90', ...
        'zeroContrastOptoDifference'};

    for arrayIndex = 1:numel(arrays)

        currentSize = size(arrays{arrayIndex});

        if currentSize(1) ~= expectedSize(1) || ...
                currentSize(2) ~= expectedSize(2)

            error( ...
                'plotDemoOptostim:DimensionMismatch', ...
                ['pcaDifference is [%d %d], but %s is [%d %d].'], ...
                expectedSize(1), ...
                expectedSize(2), ...
                arrayNames{arrayIndex}, ...
                currentSize(1), ...
                currentSize(2));
        end
    end
end


% =====================================================================
% Physical coordinate vectors
% =====================================================================

function [xMM, yMM, pixelSizeMM] = ...
        demoComputeMMCoordinates(imagingData, blockID, referenceArray)

    defaultPixelSizeMM = 8.22 / 512;

    pixelSizeMM = [];

    if isfield(imagingData, 'pixelsizemm') && ...
            numel(imagingData.pixelsizemm) >= blockID && ...
            isfinite(imagingData.pixelsizemm(blockID)) && ...
            imagingData.pixelsizemm(blockID) > 0

        pixelSizeMM = imagingData.pixelsizemm(blockID);
    end

    if isempty(pixelSizeMM)

        warning( ...
            'plotDemoOptostim:MissingPixelSize', ...
            ['imagingData.pixelsizemm is unavailable. ' ...
             'Using %.6f mm/px.'], ...
            defaultPixelSizeMM);

        pixelSizeMM = defaultPixelSizeMM;
    end

    nRows = size(referenceArray,1);
    nColumns = size(referenceArray,2);

    xMM = (0:nColumns-1) * pixelSizeMM;
    yMM = (0:nRows-1) * pixelSizeMM;
end


% =====================================================================
% Symmetric color limits around zero
% =====================================================================

function colorLimits = demoSymmetricColorLimits( ...
        imageData, validMask, dataName, currentSessID)

    validValues = imageData(validMask & isfinite(imageData));

    if isempty(validValues)

        error( ...
            'plotDemoOptostim:NoFiniteValues', ...
            'Session %d: %s contains no finite values.', ...
            currentSessID, ...
            dataName);
    end

    maximumAbsoluteValue = max(abs(validValues));

    if ~isfinite(maximumAbsoluteValue) || ...
            maximumAbsoluteValue <= 0

        error( ...
            'plotDemoOptostim:ZeroDynamicRange', ...
            'Session %d: %s has zero dynamic range.', ...
            currentSessID, ...
            dataName);
    end

    colorLimits = [ ...
        -maximumAbsoluteValue, ...
         maximumAbsoluteValue];
end


% =====================================================================
% Plot a scalar grayscale background
% =====================================================================

function imageHandle = demoPlotScalarBackground( ...
        axesHandle, imageData, xMM, yMM, colorLimits)

    imageHandle = imagesc( ...
        axesHandle, ...
        xMM, ...
        yMM, ...
        imageData);

    imageHandle.HandleVisibility = 'off';
    imageHandle.AlphaData = isfinite(imageData);

    set(axesHandle, ...
        'Color', [0.82 0.82 0.82], ...
        'CLim', colorLimits);

    colormap(axesHandle, gray(257));
end


% =====================================================================
% Add a colorbar
% =====================================================================

function colorbarHandle = demoAddColorbar( ...
        axesHandle, labelText)

    colorbarHandle = colorbar(axesHandle);

    colorbarHandle.Label.String = labelText;
    colorbarHandle.Label.FontName = 'Arial';
    colorbarHandle.Label.FontSize = 10;
end


% =====================================================================
% Plot a mask outline
% =====================================================================

function legendHandle = demoPlotMaskOutline( ...
        axesHandle, ...
        mask, ...
        pixelSizeMM, ...
        lineColor, ...
        lineStyle, ...
        lineWidth, ...
        displayName)

    if ~any(mask(:))

        legendHandle = plot( ...
            axesHandle, ...
            NaN, ...
            NaN, ...
            lineStyle, ...
            'Color', lineColor, ...
            'LineWidth', lineWidth, ...
            'DisplayName', displayName);

        return;
    end

    boundaries = bwboundaries(mask);

    legendHandle = [];

    for boundaryIndex = 1:numel(boundaries)

        boundary = boundaries{boundaryIndex};

        xCoordinates = ...
            (boundary(:,2) - 1) * pixelSizeMM;

        yCoordinates = ...
            (boundary(:,1) - 1) * pixelSizeMM;

        if boundaryIndex == 1

            legendHandle = plot( ...
                axesHandle, ...
                xCoordinates, ...
                yCoordinates, ...
                lineStyle, ...
                'Color', lineColor, ...
                'LineWidth', lineWidth, ...
                'DisplayName', displayName);

        else

            plot( ...
                axesHandle, ...
                xCoordinates, ...
                yCoordinates, ...
                lineStyle, ...
                'Color', lineColor, ...
                'LineWidth', lineWidth, ...
                'HandleVisibility', 'off');
        end
    end
end


% =====================================================================
% Plot red/blue target overlays with contrasting outlines
% =====================================================================

function [target0LegendHandle, target90LegendHandle, overlapLegendHandle] = ...
        demoPlotTargetOverlay( ...
            axesHandle, ...
            target0, ...
            target90, ...
            xMM, ...
            yMM, ...
            nOverlap)

    targetAlpha = 0.78;

    color0 = [0 0 1];
    color90 = [1 0 0];
    colorOverlap = [1 0 1];

    [nRows, nColumns] = size(target0);

    rgbImage = zeros(nRows,nColumns,3);
    alphaImage = zeros(nRows,nColumns);

    target0Only = target0 & ~target90;
    target90Only = target90 & ~target0;
    overlapMask = target0 & target90;

    for channelIndex = 1:3

        colorPlane = rgbImage(:,:,channelIndex);

        colorPlane(target0Only) = ...
            color0(channelIndex);

        colorPlane(target90Only) = ...
            color90(channelIndex);

        colorPlane(overlapMask) = ...
            colorOverlap(channelIndex);

        rgbImage(:,:,channelIndex) = colorPlane;
    end

    alphaImage(target0Only) = targetAlpha;
    alphaImage(target90Only) = targetAlpha;
    alphaImage(overlapMask) = 0.90;

    overlayHandle = image( ...
        axesHandle, ...
        xMM, ...
        yMM, ...
        rgbImage);

    overlayHandle.AlphaData = alphaImage;
    overlayHandle.HandleVisibility = 'off';

    % White outline around blue 0-degree targets.
    [~, blueBoundaryHandle] = contour( ...
        axesHandle, ...
        xMM, ...
        yMM, ...
        double(target0), ...
        [0.5 0.5], ...
        'Color', [1 1 1], ...
        'LineWidth', 0.25);

    blueBoundaryHandle.HandleVisibility = 'off';

    % Black outline around red 90-degree targets.
    [~, redBoundaryHandle] = contour( ...
        axesHandle, ...
        xMM, ...
        yMM, ...
        double(target90), ...
        [0.5 0.5], ...
        'Color', [0 0 0], ...
        'LineWidth', 0.25);

    redBoundaryHandle.HandleVisibility = 'off';

    target0LegendHandle = patch( ...
        axesHandle, ...
        NaN, ...
        NaN, ...
        color0, ...
        'FaceAlpha', targetAlpha, ...
        'EdgeColor', [1 1 1], ...
        'LineWidth', 0.25, ...
        'DisplayName', ...
        ['0' char(176) ' designed targets']);

    target90LegendHandle = patch( ...
        axesHandle, ...
        NaN, ...
        NaN, ...
        color90, ...
        'FaceAlpha', targetAlpha, ...
        'EdgeColor', [0 0 0], ...
        'LineWidth', 0.25, ...
        'DisplayName', ...
        ['90' char(176) ' designed targets']);

    overlapLegendHandle = [];

    if nOverlap > 0

        overlapLegendHandle = patch( ...
            axesHandle, ...
            NaN, ...
            NaN, ...
            colorOverlap, ...
            'FaceAlpha', 0.90, ...
            'EdgeColor', [0 0 0], ...
            'LineWidth', 0.25, ...
            'DisplayName', ...
            sprintf('Overlap (%d px)', nOverlap));
    end
end


% =====================================================================
% Create the two-row combined legend
% =====================================================================

function legendHandle = demoCreateTwoRowCombinedLegend( ...
        axesHandle, ...
        target0Handle, ...
        target90Handle, ...
        roiHandle, ...
        gaussianHandle)

    % Two rows, two columns:
    % row 1 = 0-degree and 90-degree target patterns
    % row 2 = ROI and the larger Gaussian footprint
    legendHandle = legend( ...
        axesHandle, ...
        [target0Handle, ...
         target90Handle, ...
         roiHandle, ...
         gaussianHandle], ...
        'Location', 'southoutside', ...
        'Orientation', 'horizontal', ...
        'NumColumns', 2, ...
        'FontName', 'Arial', ...
        'FontSize', 8, ...
        'Box', 'off');
end


% =====================================================================
% Format axes
% =====================================================================

function demoFormatAxes(axesHandle, xMM, yMM)

    axis(axesHandle, 'image');

    set(axesHandle, ...
        'YDir', 'reverse', ...
        'TickDir', 'out', ...
        'FontName', 'Arial', ...
        'FontSize', 11, ...
        'Box', 'off', ...
        'XGrid', 'off', ...
        'YGrid', 'off');

    xlim(axesHandle, [xMM(1), xMM(end)]);
    ylim(axesHandle, [yMM(1), yMM(end)]);

    xlabel( ...
        axesHandle, ...
        'X (mm)', ...
        'FontName', 'Arial');

    ylabel( ...
        axesHandle, ...
        'Y (mm)', ...
        'FontName', 'Arial');
end


% =====================================================================
% Panel label
% =====================================================================

function labelHandle = demoPanelLabel(axesHandle, labelText)

    labelHandle = text( ...
        axesHandle, ...
        -0.15, ...
        1.04, ...
        labelText, ...
        'Units', 'normalized', ...
        'FontName', 'Arial', ...
        'FontSize', 16, ...
        'FontWeight', 'bold');
end


% =====================================================================
% Equalize the visual dimensions of all panel axes
% =====================================================================

function demoEqualizeAxes(axesHandles)

    drawnow;

    nAxes = numel(axesHandles);
    positions = zeros(nAxes,4);

    for axisIndex = 1:nAxes
        positions(axisIndex,:) = get(axesHandles(axisIndex), 'Position');
    end

    commonWidth = min(positions(:,3));
    commonHeight = min(positions(:,4));

    for axisIndex = 1:nAxes

        centerX = positions(axisIndex,1) + positions(axisIndex,3)/2;
        centerY = positions(axisIndex,2) + positions(axisIndex,4)/2;

        newPosition = [ ...
            centerX - commonWidth/2, ...
            centerY - commonHeight/2, ...
            commonWidth, ...
            commonHeight];

        set(axesHandles(axisIndex), 'Position', newPosition);
    end
end


% =====================================================================
% Dice coefficient for projector QC
% =====================================================================

function diceValue = demoDiceCoefficient(maskA, maskB)

    denominator = sum(maskA(:)) + sum(maskB(:));

    if denominator == 0

        diceValue = NaN;
        return;
    end

    diceValue = ...
        2 * sum(maskA(:) & maskB(:)) / denominator;
end


% =====================================================================
% Parse Panel-B experiment metadata
% =====================================================================

function metadata = demoParseExperimentMetadata( ...
        integratedResponseFile, monkeyName, currentBlockStruct)

    metadata = struct();
    metadata.animalName = char(monkeyName);
    metadata.experimentDate = '';
    metadata.experimentRun = NaN;

    fileToken = regexp( ...
        integratedResponseFile, ...
        'D(\d{8})R(\d+)', ...
        'tokens', ...
        'once');

    if ~isempty(fileToken)
        metadata.experimentDate = fileToken{1};
        metadata.experimentRun = str2double(fileToken{2});
        return;
    end

    if isfield(currentBlockStruct, 'date')
        metadata.experimentDate = char(currentBlockStruct.date);
    end

    if isfield(currentBlockStruct, 'run')
        metadata.experimentRun = str2double( ...
            num2str(currentBlockStruct.run));
    end
end


% =====================================================================
% Validate all saved image fields as 512 x 512
% =====================================================================

function demoValidateMinimalMapData(mapData, expectedSize)

    spatialFields = { ...
        'pcaDenoised0Coreg', ...
        'pcaDenoised90Coreg', ...
        'pcaDenoisedDifference90Minus0Coreg', ...
        'measuredActivity0CoregRaw', ...
        'measuredActivity90CoregRaw', ...
        'measuredActivityDifference90Minus0CoregRaw', ...
        'measuredActivityDifference90Minus0CoregBandpass', ...
        'roiMask', ...
        'gaussianMask0', ...
        'gaussianMask90', ...
        'displayedGaussianFootprint', ...
        'bitmap0', ...
        'bitmap90'};

    for fieldIndex = 1:numel(spatialFields)

        fieldName = spatialFields{fieldIndex};

        if ~isfield(mapData, fieldName)
            error( ...
                'plotDemoOptostim:MissingSavedMap', ...
                'mapData.%s is missing.', ...
                fieldName);
        end

        fieldSize = size(mapData.(fieldName));

        if numel(fieldSize) < 2 || ...
                fieldSize(1) ~= expectedSize(1) || ...
                fieldSize(2) ~= expectedSize(2)

            error( ...
                'plotDemoOptostim:SavedMapSizeMismatch', ...
                ['mapData.%s is [%s], expected [%d %d].'], ...
                fieldName, ...
                num2str(fieldSize), ...
                expectedSize(1), ...
                expectedSize(2));
        end
    end
end


% =====================================================================
% Save SVG and PNG
% =====================================================================

function outputFiles = demoSaveOutputs( ...
        figHandle, ...
        mapData, ...
        stimulationSummary, ...
        mainPath, ...
        monkeyName, ...
        chamberWanted, ...
        currentSessID, ...
        currentBlockStruct, ...
        saveFlag)

    outputFiles = struct( ...
        'svg', '', ...
        'png', '', ...
        'mat', '');

    if saveFlag ~= 1
        return;
    end

    outputDirectory = fullfile( ...
        mainPath, ...
        monkeyName, ...
        'Meta', ...
        'demo-optostim');

    if ~exist(outputDirectory, 'dir')
        mkdir(outputDirectory);
    end

    dateString = regexprep( ...
        char(currentBlockStruct.date), ...
        '[^A-Za-z0-9_-]', ...
        '');

    runString = regexprep( ...
        num2str(currentBlockStruct.run), ...
        '[^A-Za-z0-9_-]', ...
        '');

    chamberString = regexprep( ...
        chamberWanted, ...
        '[^A-Za-z0-9_-]', ...
        '');

    baseName = sprintf( ...
        'demo-optostim_%s_%s_sess%d_%sR%s', ...
        monkeyName, ...
        chamberString, ...
        currentSessID, ...
        dateString, ...
        runString);

    svgFile = fullfile( ...
        outputDirectory, ...
        [baseName '.svg']);

    pngFile = fullfile( ...
        outputDirectory, ...
        [baseName '.png']);

    matFile = fullfile( ...
        outputDirectory, ...
        [baseName '_maps.mat']);

    set(figHandle, ...
        'PaperPositionMode', 'auto');

    drawnow;

    print( ...
        figHandle, ...
        svgFile, ...
        '-dsvg');

    print( ...
        figHandle, ...
        pngFile, ...
        '-dpng', ...
        '-r300');

    % Intentionally save only the two requested structs.
    save( ...
        matFile, ...
        'mapData', ...
        'stimulationSummary', ...
        '-v7.3');

    fprintf('Saved SVG: %s\n', svgFile);
    fprintf('Saved PNG: %s\n', pngFile);
    fprintf('Saved MAT structs (mapData, stimulationSummary): %s\n', matFile);

    outputFiles.svg = svgFile;
    outputFiles.png = pngFile;
    outputFiles.mat = matFile;
end


% ==============================================================
% Constrained ROI-only rigid registration of the measured activity
% ==============================================================

function [tform, transformInfo] = ...
        demoOptimizeRigidActivityTransform( ...
            fixedImage, movingImage, registrationMask, initialShiftPx)

    validMask = ...
        logical(registrationMask) & ...
        isfinite(fixedImage) & ...
        isfinite(movingImage);

    if nnz(validMask) < 500
        error( ...
            'plotDemoOptostim:TooFewRigidRegistrationPixels', ...
            'Only %d pixels are available for ROI rigid registration.', ...
            nnz(validMask));
    end

    fixedWork = double(fixedImage);
    movingWork = double(movingImage);

    fixedValues = fixedWork(validMask);
    movingValues = movingWork(validMask);

    fixedScale = std(fixedValues);
    movingScale = std(movingValues);

    if ~isfinite(fixedScale) || fixedScale <= eps
        fixedScale = 1;
    end

    if ~isfinite(movingScale) || movingScale <= eps
        movingScale = 1;
    end

    fixedWork = (fixedWork - mean(fixedValues)) ./ fixedScale;
    movingWork = (movingWork - mean(movingValues)) ./ movingScale;

    fixedWork(~isfinite(fixedWork)) = 0;
    movingWork(~isfinite(movingWork)) = 0;

    % Smooth only the copies used by the registration objective.
    fixedWork = imgaussfilt(fixedWork, 2.0);
    movingWork = imgaussfilt(movingWork, 2.0);

    initialParameters = [ ...
        initialShiftPx(1), ...
        initialShiftPx(2), ...
        0];

    parameterLimits = [60, 60, 15];

    optimizationOptions = optimset( ...
        'Display', 'off', ...
        'MaxIter', 180, ...
        'MaxFunEvals', 500, ...
        'TolX', 0.05, ...
        'TolFun', 1e-5);

    objectiveFunction = @(parameters) ...
        demoRigidRegistrationObjective( ...
            parameters, ...
            fixedWork, ...
            movingWork, ...
            registrationMask, ...
            parameterLimits);

    [optimizedParameters, objectiveValue] = fminsearch( ...
        objectiveFunction, ...
        initialParameters, ...
        optimizationOptions);

    optimizedParameters(1) = max( ...
        -parameterLimits(1), ...
        min(parameterLimits(1), optimizedParameters(1)));

    optimizedParameters(2) = max( ...
        -parameterLimits(2), ...
        min(parameterLimits(2), optimizedParameters(2)));

    optimizedParameters(3) = max( ...
        -parameterLimits(3), ...
        min(parameterLimits(3), optimizedParameters(3)));

    tform = demoMakeCenteredRigidTransform( ...
        size(fixedImage), ...
        optimizedParameters(1), ...
        optimizedParameters(2), ...
        optimizedParameters(3));

    transformInfo = demoDecomposeAffine2D(tform);
    transformInfo.objectiveValue = objectiveValue;
    transformInfo.optimizedParameters = optimizedParameters;
    transformInfo.nRegistrationPixels = nnz(validMask);
end


% ==============================================================
% Objective for constrained ROI-only rigid registration
% ==============================================================

function objectiveValue = demoRigidRegistrationObjective( ...
        parameters, fixedImage, movingImage, registrationMask, limits)

    excess = max(abs(parameters) - limits, 0);

    if any(excess > 0)
        objectiveValue = 1e3 + sum(excess.^2);
        return;
    end

    tform = demoMakeCenteredRigidTransform( ...
        size(fixedImage), ...
        parameters(1), ...
        parameters(2), ...
        parameters(3));

    transformedMoving = demoApplyGeometricTransform( ...
        movingImage, ...
        tform, ...
        size(fixedImage), ...
        'linear');

    [pearsonR, ~, nPixels] = demoPearsonRSquared( ...
        fixedImage, ...
        transformedMoving, ...
        registrationMask);

    if nPixels < 500 || ~isfinite(pearsonR)
        objectiveValue = 1e3;
        return;
    end

    % Preserve the sign of the relationship: maximize positive Pearson r,
    % rather than maximizing r-squared and accepting an inverted pattern.
    objectiveValue = 1 - pearsonR;
end


% ==============================================================
% Construct a rigid affine2d transform around the image center
% ==============================================================

function tform = demoMakeCenteredRigidTransform( ...
        imageSize, xShiftPx, yShiftPx, rotationDeg)

    centerX = (imageSize(2) + 1) / 2;
    centerY = (imageSize(1) + 1) / 2;

    angleRadians = rotationDeg * pi / 180;

    translateToOrigin = [ ...
        1 0 0; ...
        0 1 0; ...
       -centerX -centerY 1];

    rotationMatrix = [ ...
         cos(angleRadians) sin(angleRadians) 0; ...
        -sin(angleRadians) cos(angleRadians) 0; ...
         0 0 1];

    translateBack = [ ...
        1 0 0; ...
        0 1 0; ...
        centerX centerY 1];

    finalTranslation = [ ...
        1 0 0; ...
        0 1 0; ...
        xShiftPx yShiftPx 1];

    tform = affine2d( ...
        translateToOrigin * ...
        rotationMatrix * ...
        translateBack * ...
        finalTranslation);
end


% ==============================================================
% Estimate a geometric transform that moves only the measured activity
% ==============================================================

function [tform, transformInfo] = demoEstimateActivityTransform( ...
        fixedImage, movingImage, registrationMask, transformType)

    validMask = ...
        registrationMask & ...
        isfinite(fixedImage) & ...
        isfinite(movingImage);

    if nnz(validMask) < 500
        error( ...
            'plotDemoOptostim:TooFewRegistrationPixels', ...
            ['Only %d pixels are available for geometric registration ' ...
             'inside the registration region.'], ...
            nnz(validMask));
    end

    fixedWork = zeros(size(fixedImage), 'double');
    movingWork = zeros(size(movingImage), 'double');

    fixedValues = double(fixedImage(validMask));
    movingValues = double(movingImage(validMask));

    fixedStd = std(fixedValues);
    movingStd = std(movingValues);

    if ~isfinite(fixedStd) || fixedStd <= eps
        fixedStd = 1;
    end

    if ~isfinite(movingStd) || movingStd <= eps
        movingStd = 1;
    end

    fixedWork(validMask) = ...
        (fixedValues - mean(fixedValues)) / fixedStd;

    movingWork(validMask) = ...
        (movingValues - mean(movingValues)) / movingStd;

    % Smooth only the registration copies. The displayed data and final
    % Pearson calculation remain unsmoothed. A 2-pixel sigma suppresses
    % column-scale noise while retaining the broad spatial geometry.
    fixedWork = imgaussfilt(fixedWork, 2.0);
    movingWork = imgaussfilt(movingWork, 2.0);

    % Phase-correlation registration is more stable for this problem than
    % starting directly with the intensity optimizer. Fall back to
    % imregtform when imregcorr is unavailable or rejects the transform type.
    registrationSucceeded = false;

    if exist('imregcorr', 'file') == 2
        try
            tform = imregcorr( ...
                movingWork, ...
                fixedWork, ...
                transformType);
            registrationSucceeded = true;
        catch
            registrationSucceeded = false;
        end
    end

    if ~registrationSucceeded
        [optimizer, metric] = imregconfig('monomodal');

        if isprop(optimizer, 'MaximumIterations')
            optimizer.MaximumIterations = 500;
        end

        if isprop(optimizer, 'MinimumStepLength')
            optimizer.MinimumStepLength = 1e-6;
        end

        outputRef = imref2d(size(fixedImage));

        tform = imregtform( ...
            movingWork, ...
            outputRef, ...
            fixedWork, ...
            outputRef, ...
            transformType, ...
            optimizer, ...
            metric, ...
            'PyramidLevels', 4);
    end

    transformInfo = demoDecomposeAffine2D(tform);
    transformInfo.nRegistrationPixels = nnz(validMask);
end


% ==============================================================
% Apply a geometric transform to an activity map
% ==============================================================

function transformedImage = demoApplyGeometricTransform( ...
        inputImage, tform, outputSize, interpolationMethod)

    inputValid = isfinite(inputImage);
    inputFilled = double(inputImage);
    inputFilled(~inputValid) = 0;

    outputRef = imref2d(outputSize);

    transformedImage = imwarp( ...
        inputFilled, ...
        tform, ...
        interpolationMethod, ...
        'OutputView', outputRef, ...
        'FillValues', 0);

    transformedValid = imwarp( ...
        double(inputValid), ...
        tform, ...
        'linear', ...
        'OutputView', outputRef, ...
        'FillValues', 0);

    transformedImage(transformedValid < 0.5) = NaN;
end


% ==============================================================
% Decompose affine2d transform for reporting
% ==============================================================

function transformInfo = demoDecomposeAffine2D(tform)

    transformMatrix = tform.T;

    transformInfo.matrix = transformMatrix;
    transformInfo.translationPx = [transformMatrix(3,1), transformMatrix(3,2)];

    linearPart = transformMatrix(1:2,1:2);

    [U,S,V] = svd(linearPart);

    rotationMatrix = U * V';

    transformInfo.rotationDeg = atan2d(rotationMatrix(1,2), rotationMatrix(1,1));
    transformInfo.scaleX = S(1,1);
    transformInfo.scaleY = S(2,2);
end

