function decoderResult = runNeurometricOptostimDecoder( ...
    neurometricInput, saveFlag, plotFlag, userOptions)
%RUNNEUROMETRICOPTOSTIMDECODER Condition-average orientation decoder.
%
% This decoder is deliberately separate from
% runNeurometricOptostimAnalysis. It consumes the completed neurometric
% result structure or its saved MAT file and can therefore be revised and
% rerun without repeating image loading, coregistration, spatial filtering,
% or broad/DC fitting.
%
% INPUTS
%   neurometricInput
%       Either:
%         1) the neurometricOptostim result structure, or
%         2) a MAT-file containing neurometricOptostim.
%
%   saveFlag
%       1 saves the decoder result MAT file, PNG/FIG copies of every
%       plotted figure, and one multipage PDF with one figure per page.
%
%   plotFlag
%       1 leaves the figures visible. Figures are still generated invisibly
%       when saveFlag=1 and plotFlag=0.
%
%   userOptions
%       Optional structure overriding fields from
%       defaultNeurometricDecoderOptions.
%
% OUTPUT
%   decoderResult
%       Condition-average signed-pattern evidence, orientation bias,
%       similarity, separate column-domain activation, strength, and
%       coactivation metrics.
%
% SIGN CONVENTION
%   pattern.evidenceBias < 0  -> more 0-degree-like
%   pattern.evidenceBias > 0  -> more 90-degree-like
%
% IMPORTANT
%   This is a condition-average decoder/representation analysis. It is not
%   trial-wise classification accuracy and is not a formal confusion
%   matrix. Trial-wise decoding and cross-validation can be added later.

if nargin < 4 || isempty(userOptions)
    userOptions = struct();
end
if nargin < 3 || isempty(plotFlag)
    plotFlag = 1;
end
if nargin < 2 || isempty(saveFlag)
    saveFlag = 0;
end

[neurometricOptostim, inputAudit] = ...
    loadNeurometricDecoderInput(neurometricInput);

options = defaultNeurometricDecoderOptions(neurometricOptostim);
options = mergeStructFields(options, userOptions);
options.saveFlag = logical(saveFlag);
options.plotFlag = logical(plotFlag);

validateNeurometricDecoderInput(neurometricOptostim);

columnarMaps = double( ...
    neurometricOptostim.filteredMaps.columnar);

analysisMask = logical( ...
    neurometricOptostim.analysisMask);

templates = neurometricOptostim.templates;

decoderResult = calculateConditionAverageDecoder( ...
    columnarMaps, ...
    templates, ...
    analysisMask, ...
    neurometricOptostim.stimContrastMatrix, ...
    options);

decoderResult.metadata = struct();
decoderResult.metadata.analysisMode = ...
    'neurometric-optostim-decoder';
decoderResult.metadata.created = datestr(now, 30);
decoderResult.metadata.sessionLabel = options.sessionLabel;
decoderResult.metadata.inputAudit = inputAudit;
decoderResult.metadata.conditionDefinitions = ...
    neurometricOptostim.conditionDefinitions;
decoderResult.metadata.stimContrastMatrix = ...
    neurometricOptostim.stimContrastMatrix;
decoderResult.metadata.options = options;
decoderResult.metadata.codeVersion = options.codeVersion;

printNeurometricDecoderAudit(decoderResult);

outputFiles = struct();
decoderMatFile = '';

% Save numerical results before optional plotting.
if saveFlag
    if exist(options.outputDir, 'dir') ~= 7
        mkdir(options.outputDir);
    end

    decoderMatFile = fullfile( ...
        options.outputDir, ...
        sprintf('%s_neurometricOptostimDecoder.mat', ...
        options.sessionLabel));

    outputFiles.matFile = decoderMatFile;
    decoderResult.outputFiles = outputFiles;

    save(decoderMatFile, ...
        'decoderResult', ...
        '-v7.3');
end

if plotFlag || saveFlag
    originalVisibility = get(groot, 'DefaultFigureVisible');

    if ~plotFlag
        set(groot, 'DefaultFigureVisible', 'off');
    end

    try
        plotFiles = plotNeurometricDecoderQC( ...
            decoderResult, ...
            neurometricOptostim, ...
            options);

        outputFiles = mergeStructFields( ...
            outputFiles, plotFiles);

        decoderResult.outputFiles = outputFiles;

        if saveFlag
            save(decoderMatFile, ...
                'decoderResult', ...
                '-v7.3');
        end
    catch ME
        set(groot, ...
            'DefaultFigureVisible', ...
            originalVisibility);

        decoderResult.plotError = ...
            getReport(ME, ...
            'extended', ...
            'hyperlinks', 'off');

        if saveFlag
            save(decoderMatFile, ...
                'decoderResult', ...
                '-v7.3');
        end

        rethrow(ME);
    end

    set(groot, ...
        'DefaultFigureVisible', ...
        originalVisibility);
end

end


function options = defaultNeurometricDecoderOptions( ...
    neurometricOptostim)

options = struct();

% Normalized scores are hidden when the corresponding raw strength falls
% below this fraction of the largest condition-average strength.
options.patternStrengthFloorFraction = 0.05;
options.domainStrengthFloorFraction = 0.05;

% Warn when the two signed PCA templates are nearly redundant or nearly
% exact opposites. Bias can still work, but coactivation cannot be inferred
% cleanly from signed-pattern projections alone.
options.templateCorrelationWarning = 0.80;

options.figurePositionPattern = [50 50 1750 950];
options.figurePositionDomain = [80 80 1550 900];
options.figurePositionLineBias = [100 100 1250 560];
options.figurePositionLineRaw = [120 80 1250 900];
options.savePNGCopies = false;
options.pngResolutionDPI = 600;
options.codeVersion = ...
    '2026-07-16-local-temp-vector-report-v6';

if isfield(neurometricOptostim, 'options') && ...
        isfield(neurometricOptostim.options, 'sessionLabel')

    options.sessionLabel = ...
        neurometricOptostim.options.sessionLabel;

elseif isfield(neurometricOptostim, 'metadata') && ...
        isfield(neurometricOptostim.metadata, 'sessionLabel')

    options.sessionLabel = ...
        neurometricOptostim.metadata.sessionLabel;
else
    options.sessionLabel = 'neurometricSession';
end

if isfield(neurometricOptostim, 'options') && ...
        isfield(neurometricOptostim.options, 'outputDir')

    options.outputDir = fullfile( ...
        neurometricOptostim.options.outputDir, ...
        'decoder');
else
    repoRoot = fileparts(mfilename('fullpath'));

    options.outputDir = fullfile( ...
        repoRoot, ...
        'outputs', ...
        'neurometric-optostim-decoder');
end

end


function [neurometricOptostim, inputAudit] = ...
    loadNeurometricDecoderInput(neurometricInput)

inputAudit = struct();

if isstruct(neurometricInput)
    neurometricOptostim = neurometricInput;
    inputAudit.inputType = 'structure';
    inputAudit.inputFile = '';
    return;
end

if ischar(neurometricInput) || isstring(neurometricInput)
    inputFile = char(neurometricInput);

    if exist(inputFile, 'file') ~= 2
        error('runNeurometricOptostimDecoder:MissingInputFile', ...
            'Input MAT file does not exist: %s', inputFile);
    end

    loaded = load(inputFile);

    if isfield(loaded, 'neurometricOptostim')
        neurometricOptostim = loaded.neurometricOptostim;
    else
        loadedFields = fieldnames(loaded);
        matchingField = '';

        for fieldIndex = 1:numel(loadedFields)
            candidate = loaded.(loadedFields{fieldIndex});

            if isstruct(candidate) && ...
                    isfield(candidate, 'filteredMaps') && ...
                    isfield(candidate, 'templates') && ...
                    isfield(candidate, 'analysisMask')

                matchingField = loadedFields{fieldIndex};
                break;
            end
        end

        if isempty(matchingField)
            error('runNeurometricOptostimDecoder:MissingResultVariable', ...
                ['No neurometricOptostim-like result structure was ' ...
                 'found in: %s'], inputFile);
        end

        neurometricOptostim = loaded.(matchingField);
    end

    inputAudit.inputType = 'MAT file';
    inputAudit.inputFile = inputFile;
    return;
end

error('runNeurometricOptostimDecoder:InvalidInput', ...
    ['neurometricInput must be either a result structure ' ...
     'or a MAT-file path.']);

end


function validateNeurometricDecoderInput(neurometricOptostim)

requiredTopLevelFields = { ...
    'filteredMaps', ...
    'templates', ...
    'analysisMask', ...
    'stimContrastMatrix', ...
    'conditionDefinitions'};

for fieldIndex = 1:numel(requiredTopLevelFields)
    fieldName = requiredTopLevelFields{fieldIndex};

    if ~isfield(neurometricOptostim, fieldName)
        error('runNeurometricOptostimDecoder:MissingField', ...
            'Missing required result field: %s', fieldName);
    end
end

if ~isfield(neurometricOptostim.filteredMaps, 'columnar')
    error('runNeurometricOptostimDecoder:MissingColumnarMaps', ...
        'filteredMaps.columnar is required.');
end

requiredTemplateFields = { ...
    'G_analysis', ...
    'pca0Current', ...
    'pca90Current'};

for fieldIndex = 1:numel(requiredTemplateFields)
    fieldName = requiredTemplateFields{fieldIndex};

    if ~isfield(neurometricOptostim.templates, fieldName)
        error('runNeurometricOptostimDecoder:MissingTemplateField', ...
            'Missing required template field: %s', fieldName);
    end
end

mapSize = size(neurometricOptostim.filteredMaps.columnar);

if numel(mapSize) < 4
    error('runNeurometricOptostimDecoder:InvalidColumnarMapSize', ...
        ['filteredMaps.columnar must be height x width x ' ...
         'contrast x condition.']);
end

expectedSpatialSize = mapSize(1:2);

if ~isequal(size(neurometricOptostim.analysisMask), ...
        expectedSpatialSize)

    error('runNeurometricOptostimDecoder:MaskSizeMismatch', ...
        'analysisMask does not match the columnar map size.');
end

if ~isequal(size(neurometricOptostim.templates.G_analysis), ...
        expectedSpatialSize)

    error('runNeurometricOptostimDecoder:GaussianSizeMismatch', ...
        'templates.G_analysis does not match the columnar map size.');
end

if ~isequal(size(neurometricOptostim.templates.pca0Current), ...
        expectedSpatialSize) || ...
        ~isequal(size(neurometricOptostim.templates.pca90Current), ...
        expectedSpatialSize)

    error('runNeurometricOptostimDecoder:PCATemplateSizeMismatch', ...
        'PCA decoder templates do not match the columnar map size.');
end

end


function decoder = calculateConditionAverageDecoder( ...
    columnarMaps, templates, analysisMask, ...
    stimContrastMatrix, options)

nContrasts = size(columnarMaps, 3);
nConditions = size(columnarMaps, 4);

spatialWeight = prepareDecoderSpatialWeight( ...
    templates.G_analysis, ...
    analysisMask);

[template0Unit, template0QC] = ...
    prepareSignedDecoderTemplate( ...
        templates.pca0Current, ...
        spatialWeight, ...
        analysisMask, ...
        '0-degree');

[template90Unit, template90QC] = ...
    prepareSignedDecoderTemplate( ...
        templates.pca90Current, ...
        spatialWeight, ...
        analysisMask, ...
        '90-degree');

templateCorrelation = sum( ...
    spatialWeight(:) .* ...
    template0Unit(:) .* ...
    template90Unit(:));

templateCorrelation = min(max(templateCorrelation, -1), 1);

if abs(templateCorrelation) >= ...
        options.templateCorrelationWarning

    warning('runNeurometricOptostimDecoder:TemplateCorrelation', ...
        ['The signed 0-degree and 90-degree PCA templates are strongly ' ...
         'correlated or anticorrelated (r=%g). Signed orientation bias ' ...
         'remains interpretable, but simultaneous activation of both ' ...
         'signed patterns may not be separately identifiable.'], ...
        templateCorrelation);
end

[domainWeight0, domainWeight90, domainWeightQC] = ...
    prepareColumnDomainWeights( ...
        templates, ...
        spatialWeight, ...
        analysisMask);

patternEvidence0 = nan(nContrasts, nConditions);
patternEvidence90 = nan(nContrasts, nConditions);
patternSimilarity0 = nan(nContrasts, nConditions);
patternSimilarity90 = nan(nContrasts, nConditions);
columnarRMS = nan(nContrasts, nConditions);

domainActivation0 = nan(nContrasts, nConditions);
domainActivation90 = nan(nContrasts, nConditions);

for contrastIndex = 1:nContrasts
    for conditionIndex = 1:nConditions

        currentMap = double(columnarMaps( ...
            :, :, contrastIndex, conditionIndex));

        currentMap(~analysisMask | ~isfinite(currentMap)) = 0;

        currentMean = sum( ...
            spatialWeight(:) .* currentMap(:));

        centeredMap = currentMap;
        centeredMap(analysisMask) = ...
            centeredMap(analysisMask) - currentMean;
        centeredMap(~analysisMask) = 0;

        currentRMS = sqrt(sum( ...
            spatialWeight(:) .* centeredMap(:).^2));

        evidence0 = sum( ...
            spatialWeight(:) .* ...
            centeredMap(:) .* ...
            template0Unit(:));

        evidence90 = sum( ...
            spatialWeight(:) .* ...
            centeredMap(:) .* ...
            template90Unit(:));

        patternEvidence0(contrastIndex, conditionIndex) = ...
            evidence0;

        patternEvidence90(contrastIndex, conditionIndex) = ...
            evidence90;

        columnarRMS(contrastIndex, conditionIndex) = ...
            currentRMS;

        if isfinite(currentRMS) && currentRMS > eps
            patternSimilarity0(contrastIndex, conditionIndex) = ...
                evidence0 ./ currentRMS;

            patternSimilarity90(contrastIndex, conditionIndex) = ...
                evidence90 ./ currentRMS;
        end

        domainActivation0(contrastIndex, conditionIndex) = ...
            sum(domainWeight0(analysisMask) .* ...
                currentMap(analysisMask));

        domainActivation90(contrastIndex, conditionIndex) = ...
            sum(domainWeight90(analysisMask) .* ...
                currentMap(analysisMask));
    end
end

patternSimilarity0 = min(max(patternSimilarity0, -1), 1);
patternSimilarity90 = min(max(patternSimilarity90, -1), 1);

%% Signed-pattern representation

patternEvidenceBias = ...
    patternEvidence90 - patternEvidence0;

% Descriptive magnitude in the two projection coordinates. Because the
% signed templates may not be orthogonal, this is not unique neural energy.
patternEvidenceStrength = hypot( ...
    patternEvidence0, patternEvidence90);

patternStrengthFloor = calculateRelativeStrengthFloor( ...
    patternEvidenceStrength, ...
    options.patternStrengthFloorFraction);

patternNormalizedIsStable = ...
    isfinite(patternEvidenceStrength) & ...
    patternEvidenceStrength > max(patternStrengthFloor, eps);

patternNormalizedBias = nan(nContrasts, nConditions);

patternBiasDenominator = ...
    abs(patternEvidence90) + abs(patternEvidence0);

patternNormalizedBias(patternNormalizedIsStable) = ...
    patternEvidenceBias(patternNormalizedIsStable) ./ ...
    max(patternBiasDenominator(patternNormalizedIsStable), eps);

patternNormalizedBias = ...
    min(max(patternNormalizedBias, -1), 1);

%% Separate nonnegative column-domain representation

domainDifference = ...
    domainActivation90 - domainActivation0;

domainStrength = hypot( ...
    domainActivation0, domainActivation90);

domainStrengthFloor = calculateRelativeStrengthFloor( ...
    domainStrength, ...
    options.domainStrengthFloorFraction);

domainNormalizedIsStable = ...
    isfinite(domainStrength) & ...
    domainStrength > max(domainStrengthFloor, eps);

domainNormalizedBias = nan(nContrasts, nConditions);

domainBiasDenominator = ...
    abs(domainActivation90) + abs(domainActivation0);

domainNormalizedBias(domainNormalizedIsStable) = ...
    domainDifference(domainNormalizedIsStable) ./ ...
    max(domainBiasDenominator(domainNormalizedIsStable), eps);

domainNormalizedBias = ...
    min(max(domainNormalizedBias, -1), 1);

positiveDomain0 = max(domainActivation0, 0);
positiveDomain90 = max(domainActivation90, 0);
positiveDomainSum = positiveDomain0 + positiveDomain90;

totalPositiveDomainStrength = hypot( ...
    positiveDomain0, positiveDomain90);

% Raw coactivation is high only when both positive domain readouts are high.
rawCoactivation = sqrt( ...
    positiveDomain0 .* positiveDomain90);

coactivationIsStable = ...
    isfinite(positiveDomainSum) & ...
    positiveDomainSum > max(domainStrengthFloor, eps);

normalizedCoactivation = nan(nContrasts, nConditions);

normalizedCoactivation(coactivationIsStable) = ...
    2 .* rawCoactivation(coactivationIsStable) ./ ...
    positiveDomainSum(coactivationIsStable);

normalizedCoactivation = ...
    min(max(normalizedCoactivation, 0), 1);

%% Visual-only benchmark checks

benchmark = calculateVisualOnlyBenchmark( ...
    patternEvidenceBias, ...
    domainDifference, ...
    stimContrastMatrix);

%% Package

decoder = struct();

decoder.pattern = struct();
decoder.pattern.evidence0 = patternEvidence0;
decoder.pattern.evidence90 = patternEvidence90;
decoder.pattern.evidenceBias = patternEvidenceBias;
decoder.pattern.evidenceStrength = patternEvidenceStrength;
decoder.pattern.similarity0 = patternSimilarity0;
decoder.pattern.similarity90 = patternSimilarity90;
decoder.pattern.normalizedBias = patternNormalizedBias;
decoder.pattern.normalizedIsStable = patternNormalizedIsStable;
decoder.pattern.strengthFloor = patternStrengthFloor;
decoder.pattern.columnarRMS = columnarRMS;

decoder.domain = struct();
decoder.domain.activation0 = domainActivation0;
decoder.domain.activation90 = domainActivation90;
decoder.domain.difference = domainDifference;
decoder.domain.strength = domainStrength;
decoder.domain.normalizedBias = domainNormalizedBias;
decoder.domain.normalizedIsStable = domainNormalizedIsStable;
decoder.domain.strengthFloor = domainStrengthFloor;
decoder.domain.positiveActivation0 = positiveDomain0;
decoder.domain.positiveActivation90 = positiveDomain90;
decoder.domain.totalPositiveStrength = ...
    totalPositiveDomainStrength;
decoder.domain.rawCoactivation = rawCoactivation;
decoder.domain.normalizedCoactivation = ...
    normalizedCoactivation;
decoder.domain.coactivationIsStable = ...
    coactivationIsStable;

decoder.templates = struct();
decoder.templates.spatialWeight = spatialWeight;
decoder.templates.signed0Unit = template0Unit;
decoder.templates.signed90Unit = template90Unit;
decoder.templates.domainWeight0 = domainWeight0;
decoder.templates.domainWeight90 = domainWeight90;

decoder.qc = struct();
decoder.qc.templateCorrelation = templateCorrelation;
decoder.qc.template0 = template0QC;
decoder.qc.template90 = template90QC;
decoder.qc.domainWeights = domainWeightQC;
decoder.qc.visualOnlyBenchmark = benchmark;

decoder.method = struct();
decoder.method.patternEvidence = ...
    ['Weighted projection of each condition-average 0.8-3 cycles/mm ' ...
     'map onto mean-centered, unit-weighted-RMS signed PCA-denoised ' ...
     'flash templates.'];

decoder.method.patternBias = ...
    ['evidence90 - evidence0; negative means more 0-degree-like and ' ...
     'positive means more 90-degree-like.'];

decoder.method.patternNormalizedBias = ...
    ['(evidence90 - evidence0) / ' ...
     '(|evidence90| + |evidence0|).'];

decoder.method.domainActivation = ...
    ['Weighted average of the condition columnar map within separate ' ...
     'nonnegative flash-derived 0-degree and 90-degree domains.'];

decoder.method.coactivation = ...
    ['sqrt(max(domain0,0) * max(domain90,0)); high only when both ' ...
     'column-domain activations are positive and large.'];

end


function spatialWeight = prepareDecoderSpatialWeight( ...
    gaussianMap, analysisMask)

spatialWeight = double(gaussianMap);
spatialWeight(~analysisMask | ~isfinite(spatialWeight)) = 0;
spatialWeight = max(spatialWeight, 0);

weightSum = sum(spatialWeight(:));

if ~isfinite(weightSum) || weightSum <= 0
    error('runNeurometricOptostimDecoder:InvalidSpatialWeight', ...
        'The flash-derived Gaussian spatial weight is invalid.');
end

spatialWeight = spatialWeight ./ weightSum;

end


function [templateUnit, templateQC] = ...
    prepareSignedDecoderTemplate( ...
        templateMap, spatialWeight, ...
        analysisMask, templateName)

templateMap = double(templateMap);
templateMap(~analysisMask | ~isfinite(templateMap)) = 0;

templateMean = sum( ...
    spatialWeight(:) .* templateMap(:));

templateCentered = templateMap;
templateCentered(analysisMask) = ...
    templateCentered(analysisMask) - templateMean;
templateCentered(~analysisMask) = 0;

templateRMS = sqrt(sum( ...
    spatialWeight(:) .* templateCentered(:).^2));

if ~isfinite(templateRMS) || templateRMS <= eps
    error('runNeurometricOptostimDecoder:InvalidSignedTemplate', ...
        '%s signed PCA template has zero weighted RMS.', ...
        templateName);
end

templateUnit = templateCentered ./ templateRMS;

templateQC = struct();
templateQC.weightedMean = templateMean;
templateQC.weightedRMS = templateRMS;
templateQC.minimum = min(templateCentered(analysisMask));
templateQC.maximum = max(templateCentered(analysisMask));

end


function [weight0, weight90, qc] = ...
    prepareColumnDomainWeights( ...
        templates, spatialWeight, analysisMask)

if isfield(templates, 'W_COL0') && ...
        isfield(templates, 'W_COL90') && ...
        ~isempty(templates.W_COL0) && ...
        ~isempty(templates.W_COL90)

    weight0 = double(templates.W_COL0);
    weight90 = double(templates.W_COL90);
else
    preference0 = max(double(templates.pca0Current), 0);
    preference90 = max(double(templates.pca90Current), 0);

    weight0 = spatialWeight .* preference0;
    weight90 = spatialWeight .* preference90;
end

weight0(~analysisMask | ~isfinite(weight0)) = 0;
weight90(~analysisMask | ~isfinite(weight90)) = 0;

weight0 = max(weight0, 0);
weight90 = max(weight90, 0);

sum0 = sum(weight0(analysisMask));
sum90 = sum(weight90(analysisMask));

if ~isfinite(sum0) || sum0 <= 0 || ...
        ~isfinite(sum90) || sum90 <= 0

    error('runNeurometricOptostimDecoder:InvalidDomainWeights', ...
        'The 0-degree or 90-degree domain weight is empty.');
end

weight0 = weight0 ./ sum0;
weight90 = weight90 ./ sum90;

qc = struct();
qc.sum0 = sum(weight0(analysisMask));
qc.sum90 = sum(weight90(analysisMask));
qc.softOverlap = sum(min( ...
    weight0(analysisMask), ...
    weight90(analysisMask)));
qc.correlation = safeDecoderCorrelation( ...
    weight0(analysisMask), ...
    weight90(analysisMask));

end


function strengthFloor = calculateRelativeStrengthFloor( ...
    strengthValues, floorFraction)

finiteStrength = strengthValues(isfinite(strengthValues));

if isempty(finiteStrength)
    strengthFloor = 0;
else
    strengthFloor = floorFraction .* max(finiteStrength);
end

end


function benchmark = calculateVisualOnlyBenchmark( ...
    patternBias, domainBias, stimContrastMatrix)

benchmark = struct();

if size(patternBias, 2) < 4 || ...
        size(stimContrastMatrix, 2) < 4

    benchmark.status = ...
        'Not calculated: expected six-condition layout was unavailable.';
    return;
end

v0Contrast = stimContrastMatrix(:,1);
v90Contrast = stimContrastMatrix(:,4);

v0Rows = isfinite(v0Contrast) & v0Contrast > 0;
v90Rows = isfinite(v90Contrast) & v90Contrast > 0;

patternV0Correct = patternBias(v0Rows,1) < 0;
patternV90Correct = patternBias(v90Rows,4) > 0;

domainV0Correct = domainBias(v0Rows,1) < 0;
domainV90Correct = domainBias(v90Rows,4) > 0;

benchmark.patternV0Correct = patternV0Correct;
benchmark.patternV90Correct = patternV90Correct;
benchmark.domainV0Correct = domainV0Correct;
benchmark.domainV90Correct = domainV90Correct;

benchmark.patternAccuracy = meanFiniteLogical([ ...
    patternV0Correct(:); ...
    patternV90Correct(:)]);

benchmark.domainAccuracy = meanFiniteLogical([ ...
    domainV0Correct(:); ...
    domainV90Correct(:)]);

benchmark.status = ...
    ['Uses nonzero-contrast visual-only V0 and V90 cells as a sign ' ...
     'sanity check; it is not cross-validated decoding accuracy.'];

end


function outputFiles = plotNeurometricDecoderQC( ...
    decoderResult, neurometricOptostim, options)

outputFiles = struct();

[cmapDiverging, cmapPositive] = ...
    getNeurometricDecoderColormaps();

conditionLabels = decoderConditionLabels( ...
    size(decoderResult.pattern.evidence0, 2));

rowLabels = decoderContrastRowLabels( ...
    neurometricOptostim.stimContrastMatrix);

%% Figure 1: signed-pattern decoder heatmaps

figPattern = figure( ...
    'Name', ...
    'Neurometric optostim signed-pattern decoder', ...
    'Color', 'w', ...
    'Position', ...
    options.figurePositionPattern);

patternEvidencePairLimit = finiteMaxAbs([ ...
    decoderResult.pattern.evidence0(:); ...
    decoderResult.pattern.evidence90(:)]);

patternBiasLimit = finiteMaxAbs( ...
    decoderResult.pattern.evidenceBias(:));

patternStrengthLimit = finiteMaxPositive( ...
    decoderResult.pattern.evidenceStrength(:));

columnarRMSLimit = finiteMaxPositive( ...
    decoderResult.pattern.columnarRMS(:));

plotDecoderPanel( ...
    subplot(2,4,1), ...
    decoderResult.pattern.evidence0, ...
    'Raw signed-pattern evidence: 0 degrees', ...
    [-patternEvidencePairLimit patternEvidencePairLimit], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,2), ...
    decoderResult.pattern.evidence90, ...
    'Raw signed-pattern evidence: 90 degrees', ...
    [-patternEvidencePairLimit patternEvidencePairLimit], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,3), ...
    decoderResult.pattern.evidenceBias, ...
    'Raw orientation bias: 90 minus 0', ...
    [-patternBiasLimit patternBiasLimit], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,4), ...
    decoderResult.pattern.evidenceStrength, ...
    'Raw signed-pattern strength', ...
    [0 patternStrengthLimit], ...
    cmapPositive, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,5), ...
    decoderResult.pattern.similarity0, ...
    'Pattern similarity to 0 degrees', ...
    [-1 1], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,6), ...
    decoderResult.pattern.similarity90, ...
    'Pattern similarity to 90 degrees', ...
    [-1 1], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,7), ...
    decoderResult.pattern.normalizedBias, ...
    'Normalized pattern bias', ...
    [-1 1], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,8), ...
    decoderResult.pattern.columnarRMS, ...
    'Total condition columnar RMS', ...
    [0 columnarRMSLimit], ...
    cmapPositive, ...
    conditionLabels, rowLabels);

annotation(figPattern, ...
    'textbox', ...
    [0.16 0.965 0.68 0.025], ...
    'String', sprintf([ ...
        'Signed flash-PCA decoder; template correlation = %.3f; ' ...
        'gray normalized cells are below %.1f%% of maximum strength'], ...
        decoderResult.qc.templateCorrelation, ...
        100 .* options.patternStrengthFloorFraction), ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

%% Figure 2: separate column domains and coactivation

figDomain = figure( ...
    'Name', ...
    'Neurometric optostim column-domain decoder', ...
    'Color', 'w', ...
    'Position', ...
    options.figurePositionDomain);

domainActivationPairLimit = finiteMaxAbs([ ...
    decoderResult.domain.activation0(:); ...
    decoderResult.domain.activation90(:)]);

domainDifferenceLimit = finiteMaxAbs( ...
    decoderResult.domain.difference(:));

domainPositiveStrengthLimit = finiteMaxPositive( ...
    decoderResult.domain.totalPositiveStrength(:));

rawCoactivationLimit = finiteMaxPositive( ...
    decoderResult.domain.rawCoactivation(:));

plotDecoderPanel( ...
    subplot(2,4,1), ...
    decoderResult.domain.activation0, ...
    '0-degree column-domain activation', ...
    [-domainActivationPairLimit domainActivationPairLimit], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,2), ...
    decoderResult.domain.activation90, ...
    '90-degree column-domain activation', ...
    [-domainActivationPairLimit domainActivationPairLimit], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,3), ...
    decoderResult.domain.difference, ...
    'Column-domain bias: 90 minus 0', ...
    [-domainDifferenceLimit domainDifferenceLimit], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,4), ...
    decoderResult.domain.normalizedBias, ...
    'Normalized signed domain bias', ...
    [-1 1], ...
    cmapDiverging, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,5), ...
    decoderResult.domain.totalPositiveStrength, ...
    'Total positive domain strength', ...
    [0 domainPositiveStrengthLimit], ...
    cmapPositive, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,6), ...
    decoderResult.domain.rawCoactivation, ...
    'Raw positive 0/90 coactivation', ...
    [0 rawCoactivationLimit], ...
    cmapPositive, ...
    conditionLabels, rowLabels);

plotDecoderPanel( ...
    subplot(2,4,7), ...
    decoderResult.domain.normalizedCoactivation, ...
    'Normalized positive coactivation', ...
    [0 1], ...
    cmapPositive, ...
    conditionLabels, rowLabels);

benchmarkAxes = subplot(2,4,8);
axis(benchmarkAxes, 'off');

benchmarkText = formatBenchmarkText( ...
    decoderResult.qc.visualOnlyBenchmark);

text(benchmarkAxes, ...
    0, 0.85, benchmarkText, ...
    'Interpreter', 'none', ...
    'VerticalAlignment', 'top', ...
    'FontSize', 11);

annotation(figDomain, ...
    'textbox', ...
    [0.16 0.965 0.68 0.025], ...
    'String', sprintf([ ...
        'Separate positive flash-derived column domains; ' ...
        'gray normalized cells are below %.1f%% of maximum strength'], ...
        100 .* options.domainStrengthFloorFraction), ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

%% Figures 3-4: contrast line summaries

[figLineBias, figLineRaw] = ...
    createNeurometricDecoderLineFigures( ...
        decoderResult, ...
        neurometricOptostim.stimContrastMatrix, ...
        options);

%% Save all four figures
%
% Every original figure is written directly to one vector landscape PDF
% page in a unique local staging directory. The merged report is copied to
% a new timestamped output file, so an older open PDF cannot block saving.

if options.saveFlag
    if exist(options.outputDir, 'dir') ~= 7
        mkdir(options.outputDir);
    end

    reportContext = ...
        prepareDecoderPDFReport(options);

    outputFiles.signedPattern = ...
        saveDecoderFigurePage( ...
            figPattern, ...
            options, ...
            'decoder_signed_pattern', ...
            1, ...
            reportContext);

    outputFiles.columnDomain = ...
        saveDecoderFigurePage( ...
            figDomain, ...
            options, ...
            'decoder_column_domain', ...
            2, ...
            reportContext);

    outputFiles.lineDomainBias = ...
        saveDecoderFigurePage( ...
            figLineBias, ...
            options, ...
            'decoder_line_domainBias', ...
            3, ...
            reportContext);

    outputFiles.lineRawDomainActivation = ...
        saveDecoderFigurePage( ...
            figLineRaw, ...
            options, ...
            'decoder_line_rawDomainActivation', ...
            4, ...
            reportContext);

    pagePaths = { ...
        outputFiles.signedPattern.pdfPage, ...
        outputFiles.columnDomain.pdfPage, ...
        outputFiles.lineDomainBias.pdfPage, ...
        outputFiles.lineRawDomainActivation.pdfPage};

    outputFiles.multiPagePDF = ...
        finalizeDecoderMultiPagePDF( ...
            pagePaths, ...
            options, ...
            reportContext);
end


end


function [figLineBias, figLineRaw] = ...
    createNeurometricDecoderLineFigures( ...
        decoderResult, stimContrastMatrix, options)

if size(stimContrastMatrix, 2) < 6
    error('runNeurometricOptostimDecoder:MissingSixConditions', ...
        ['The line-summary figures require the standard six-condition ' ...
         'layout.']);
end

visualColor = [0 0 0];
congruentColor = [1 0 0];
incongruentColor = [0 0 1];

lineColors = { ...
    visualColor, ...
    congruentColor, ...
    incongruentColor};

visual0Indices = [1 2 3];
visual90Indices = [4 6 5];

visual0Labels = { ...
    'V0', ...
    'V0 + O0 (congruent)', ...
    'V0 + O90 (incongruent)'};

visual90Labels = { ...
    'V90', ...
    'V90 + O90 (congruent)', ...
    'V90 + O0 (incongruent)'};

%% Figure 3: primary signed domain-bias curves

domainBias = decoderResult.domain.difference;
domainBiasLimit = finiteMaxAbs(domainBias(:));

figLineBias = figure( ...
    'Name', ...
    'Neurometric optostim line summary: column-domain bias', ...
    'Color', 'w', ...
    'Position', ...
    options.figurePositionLineBias);

plotDecoderConditionTrio( ...
    subplot(1,2,1), ...
    stimContrastMatrix, ...
    domainBias, ...
    visual0Indices, ...
    visual0Labels, ...
    lineColors, ...
    'Visual 0 conditions', ...
    'COL90 - COL0 (\DeltaF/F)', ...
    [-domainBiasLimit domainBiasLimit], ...
    true);

plotDecoderConditionTrio( ...
    subplot(1,2,2), ...
    stimContrastMatrix, ...
    domainBias, ...
    visual90Indices, ...
    visual90Labels, ...
    lineColors, ...
    'Visual 90 conditions', ...
    'COL90 - COL0 (\DeltaF/F)', ...
    [-domainBiasLimit domainBiasLimit], ...
    true);

annotation(figLineBias, ...
    'textbox', ...
    [0.18 0.95 0.64 0.035], ...
    'String', ...
    ['Column-domain orientation bias across contrast; ' ...
     'negative = more 0-degree-like, positive = more 90-degree-like'], ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

%% Figure 4: raw matched/opposite domain activation

activation0 = decoderResult.domain.activation0;
activation90 = decoderResult.domain.activation90;

rawActivationLimit = finiteMaxAbs([ ...
    activation0(:); ...
    activation90(:)]);

figLineRaw = figure( ...
    'Name', ...
    'Neurometric optostim line summary: raw domain activation', ...
    'Color', 'w', ...
    'Position', ...
    options.figurePositionLineRaw);

plotDecoderConditionTrio( ...
    subplot(2,2,1), ...
    stimContrastMatrix, ...
    activation0, ...
    visual0Indices, ...
    visual0Labels, ...
    lineColors, ...
    'Visual 0: matched 0-degree domain', ...
    'COL0 activation (\DeltaF/F)', ...
    [-rawActivationLimit rawActivationLimit], ...
    false);

plotDecoderConditionTrio( ...
    subplot(2,2,2), ...
    stimContrastMatrix, ...
    activation90, ...
    visual90Indices, ...
    visual90Labels, ...
    lineColors, ...
    'Visual 90: matched 90-degree domain', ...
    'COL90 activation (\DeltaF/F)', ...
    [-rawActivationLimit rawActivationLimit], ...
    false);

plotDecoderConditionTrio( ...
    subplot(2,2,3), ...
    stimContrastMatrix, ...
    activation90, ...
    visual0Indices, ...
    visual0Labels, ...
    lineColors, ...
    'Visual 0: opposite 90-degree domain', ...
    'COL90 activation (\DeltaF/F)', ...
    [-rawActivationLimit rawActivationLimit], ...
    false);

plotDecoderConditionTrio( ...
    subplot(2,2,4), ...
    stimContrastMatrix, ...
    activation0, ...
    visual90Indices, ...
    visual90Labels, ...
    lineColors, ...
    'Visual 90: opposite 0-degree domain', ...
    'COL0 activation (\DeltaF/F)', ...
    [-rawActivationLimit rawActivationLimit], ...
    false);

annotation(figLineRaw, ...
    'textbox', ...
    [0.14 0.965 0.72 0.025], ...
    'String', ...
    ['Raw column-domain activation across contrast; ' ...
     'top row = matched domain, bottom row = opposite domain; ' ...
     'black = visual only, red = congruent, blue = incongruent'], ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold', ...
    'EdgeColor', 'none');

end


function plotDecoderConditionTrio( ...
    ax, stimContrastMatrix, metricMatrix, ...
    conditionIndices, conditionLabels, ...
    lineColors, panelTitle, yLabelText, ...
    yLimits, addBiasDirectionLabels)

hold(ax, 'on');

lineHandles = gobjects(1, numel(conditionIndices));

for lineIndex = 1:numel(conditionIndices)
    conditionIndex = conditionIndices(lineIndex);

    xValues = double( ...
        stimContrastMatrix(:,conditionIndex));

    yValues = double( ...
        metricMatrix(:,conditionIndex));

    valid = isfinite(xValues) & isfinite(yValues);

    xValues = xValues(valid);
    yValues = yValues(valid);

    [xValues, sortOrder] = sort(xValues);
    yValues = yValues(sortOrder);

    lineHandles(lineIndex) = plot( ...
        ax, ...
        xValues, ...
        yValues, ...
        '-o', ...
        'Color', lineColors{lineIndex}, ...
        'MarkerFaceColor', lineColors{lineIndex}, ...
        'MarkerEdgeColor', lineColors{lineIndex}, ...
        'LineWidth', 2, ...
        'MarkerSize', 6);
end

allX = double( ...
    stimContrastMatrix(:,conditionIndices));

allX = allX(isfinite(allX));

if isempty(allX)
    xLimits = [0 1];
else
    xMinimum = min(allX);
    xMaximum = max(allX);

    if xMaximum <= xMinimum
        xLimits = [xMinimum - 0.5, xMaximum + 0.5];
    else
        xPadding = 0.03 .* ...
            (xMaximum - xMinimum);

        xLimits = [ ...
            max(0, xMinimum - xPadding), ...
            xMaximum + xPadding];
    end
end

plot(ax, ...
    xLimits, ...
    [0 0], ...
    '--', ...
    'Color', [0.45 0.45 0.45], ...
    'LineWidth', 1, ...
    'HandleVisibility', 'off');

xlim(ax, xLimits);
ylim(ax, yLimits);

xlabel(ax, 'Stimulus contrast (%)');
ylabel(ax, yLabelText);
title(ax, panelTitle);

legend(ax, ...
    lineHandles, ...
    conditionLabels, ...
    'Location', 'best', ...
    'Interpreter', 'none');

set(ax, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'FontSize', 10);

if addBiasDirectionLabels
    text(ax, ...
        0.02, 0.97, ...
        'More 90-degree-like', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'top', ...
        'FontWeight', 'bold');

    text(ax, ...
        0.02, 0.03, ...
        'More 0-degree-like', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', ...
        'FontWeight', 'bold');
end

hold(ax, 'off');

end


function plotDecoderPanel( ...
    ax, values, panelTitle, colorLimits, ...
    colorMap, conditionLabels, rowLabels)

% No transparent graphics. Invalid cells are displayed as solid gray.
invalidMask = ~isfinite(values);

valuesToPlot = values;
valuesToPlot(invalidMask) = 0;

imagesc(ax, valuesToPlot);

set(ax, ...
    'Color', ...
    [0.75 0.75 0.75]);

axis(ax, 'square');
caxis(ax, colorLimits);
colormap(ax, colorMap);
colorbar(ax);

hold(ax, 'on');

[invalidRows, invalidColumns] = find(invalidMask);

for invalidIndex = 1:numel(invalidRows)
    rectangle(ax, ...
        'Position', [ ...
            invalidColumns(invalidIndex) - 0.5, ...
            invalidRows(invalidIndex) - 0.5, ...
            1, ...
            1], ...
        'FaceColor', [0.75 0.75 0.75], ...
        'EdgeColor', 'none');
end

hold(ax, 'off');

title(ax, panelTitle, ...
    'Interpreter', 'none');

set(ax, ...
    'XTick', 1:numel(conditionLabels), ...
    'XTickLabel', conditionLabels, ...
    'XTickLabelRotation', 30, ...
    'YTick', 1:numel(rowLabels), ...
    'YTickLabel', rowLabels);

xlabel(ax, 'Condition');
ylabel(ax, 'BL / opto contrast (%)');

end


function [cmapDiverging, cmapPositive] = ...
    getNeurometricDecoderColormaps()

if exist('fireice', 'file') == 2
    [cmapDiverging, cmapPositive, ~] = fireice(64);
    return;
end

halfCount = 32;

blueToBlack = [ ...
    zeros(halfCount,1), ...
    linspace(1,0,halfCount)', ...
    linspace(1,0,halfCount)'];

blackToRedYellow = [ ...
    linspace(0,1,halfCount)', ...
    linspace(0,1,halfCount)', ...
    zeros(halfCount,1)];

cmapDiverging = [ ...
    blueToBlack; ...
    0 0 0; ...
    blackToRedYellow];

cmapPositive = [ ...
    0 0 0; ...
    blackToRedYellow];

end


function labels = decoderConditionLabels(nConditions)

if nConditions == 6
    labels = { ...
        'V0', ...
        'V0 + O0', ...
        'V0 + O90', ...
        'V90', ...
        'V90 + O0', ...
        'V90 + O90'};
else
    labels = cell(1, nConditions);

    for conditionIndex = 1:nConditions
        labels{conditionIndex} = ...
            sprintf('Condition %d', conditionIndex);
    end
end

end


function rowLabels = decoderContrastRowLabels( ...
    stimContrastMatrix)

nRows = size(stimContrastMatrix, 1);
rowLabels = cell(nRows, 1);

for rowIndex = 1:nRows
    baselineColumns = intersect([1 4], ...
        1:size(stimContrastMatrix,2));

    optoColumns = intersect([2 3 5 6], ...
        1:size(stimContrastMatrix,2));

    baselineCandidates = ...
        stimContrastMatrix(rowIndex, baselineColumns);

    optoCandidates = ...
        stimContrastMatrix(rowIndex, optoColumns);

    baselineCandidates = ...
        baselineCandidates(isfinite(baselineCandidates));

    optoCandidates = ...
        optoCandidates(isfinite(optoCandidates));

    if isempty(baselineCandidates)
        baselineContrast = NaN;
    else
        baselineContrast = baselineCandidates(1);
    end

    if isempty(optoCandidates)
        optoContrast = NaN;
    else
        optoContrast = optoCandidates(1);
    end

    if isfinite(baselineContrast) && ...
            isfinite(optoContrast)

        rowLabels{rowIndex} = sprintf('%g / %g', ...
            baselineContrast, optoContrast);

    elseif isfinite(baselineContrast)
        rowLabels{rowIndex} = sprintf('%g / -', ...
            baselineContrast);

    elseif isfinite(optoContrast)
        rowLabels{rowIndex} = sprintf('- / %g', ...
            optoContrast);
    else
        rowLabels{rowIndex} = ...
            sprintf('Rank %d', rowIndex);
    end
end

end


function reportContext = ...
    prepareDecoderPDFReport(options)
%PREPAREDECODERPDFREPORT Create a unique local staging directory.
%
% PDF pages are never written directly into the network output directory.
% Existing reports can therefore remain open in Acrobat, Edge, or another
% viewer without locking the next run's temporary pages. The completed
% four-page report is copied to a new timestamped output filename only
% after all pages have been created and merged successfully.

reportContext = struct();

reportContext.tempDir = tempname(tempdir);

[mkdirSucceeded, mkdirMessage] = ...
    mkdir(reportContext.tempDir);

if ~mkdirSucceeded
    error('runNeurometricOptostimDecoder:TempReportDirectoryFailed', ...
        ['Could not create the local decoder report staging directory:\n' ...
         '%s\n\n%s'], ...
        reportContext.tempDir, ...
        mkdirMessage);
end

reportContext.localMergedPDF = fullfile( ...
    reportContext.tempDir, ...
    'neurometricOptostimDecoder_merged.pdf');

runStamp = datestr(now, ...
    'yyyymmdd_HHMMSS');

reportContext.finalPDF = fullfile( ...
    options.outputDir, ...
    sprintf('%s_neurometricOptostimDecoder_figures_%s.pdf', ...
        options.sessionLabel, ...
        runStamp));

% Resolve the extremely unlikely case of two runs beginning in one second.
suffixIndex = 1;

while exist(reportContext.finalPDF, 'file') == 2
    reportContext.finalPDF = fullfile( ...
        options.outputDir, ...
        sprintf('%s_neurometricOptostimDecoder_figures_%s_%02d.pdf', ...
            options.sessionLabel, ...
            runStamp, ...
            suffixIndex));

    suffixIndex = suffixIndex + 1;
end

end


function savedFiles = saveDecoderFigurePage( ...
    fig, options, suffix, pageNumber, ...
    reportContext)
%SAVEDECODERFIGUREPAGE Save one complete figure and one vector PDF page.
%
% The report PDF is written directly from the original MATLAB figure using
% the Painters renderer. There is no PNG-to-PDF round trip, so increasing
% PNG resolution cannot slow or blur the report. Text, axes, lines,
% markers, legends, and annotations remain vector objects. The small
% heatmap image objects are embedded without resampling the entire page.

savedFiles = struct();

set(fig, 'Color', 'w');
drawnow;

%% Editable MATLAB FIG

savedFiles.fig = fullfile( ...
    options.outputDir, ...
    sprintf('%s_%s.fig', ...
        options.sessionLabel, ...
        suffix));

savefig(fig, savedFiles.fig);

%% Optional high-resolution PNG copy
%
% Disabled by default because it is not used to build the PDF report.
% Enable userOptions.savePNGCopies only when a separate raster file is
% actually needed.

savedFiles.png = '';

if isfield(options, 'savePNGCopies') && ...
        options.savePNGCopies

    savedFiles.png = fullfile( ...
        options.outputDir, ...
        sprintf('%s_%s.png', ...
            options.sessionLabel, ...
            suffix));

    saveDecoderOptionalPNG( ...
        fig, ...
        savedFiles.png, ...
        options.pngResolutionDPI);
end

%% Explicitly numbered direct vector PDF page

savedFiles.pdfPage = fullfile( ...
    reportContext.tempDir, ...
    sprintf('decoderPdfPage_%02d_%s.pdf', ...
        pageNumber, ...
        suffix));

saveDecoderVectorPDFPage( ...
    fig, ...
    savedFiles.pdfPage);

end


function saveDecoderOptionalPNG( ...
    fig, pngPath, resolutionDPI)
%SAVEDECODEROPTIONALPNG Save a separate raster copy when explicitly asked.

if exist(pngPath, 'file') == 2
    delete(pngPath);
end

oldState = captureDecoderPrintState(fig);

set(fig, ...
    'Color', 'w', ...
    'Renderer', 'opengl', ...
    'PaperPositionMode', 'auto', ...
    'InvertHardcopy', 'off');

drawnow;

try
    print(fig, ...
        pngPath, ...
        '-dpng', ...
        '-opengl', ...
        sprintf('-r%d', resolutionDPI));
catch ME
    restoreDecoderPrintState(fig, oldState);
    rethrow(ME);
end

restoreDecoderPrintState(fig, oldState);

if exist(pngPath, 'file') ~= 2
    error('runNeurometricOptostimDecoder:PNGSaveFailed', ...
        'The optional decoder PNG was not created: %s', ...
        pngPath);
end

end


function saveDecoderVectorPDFPage( ...
    fig, pdfPath)
%SAVEDECODERVECTORPDFPAGE Save one complete landscape vector PDF page.
%
% The page is fixed at 11 x 8.5 inches. The figure aspect ratio is
% preserved and centered. Painters is used directly on the original
% figure, avoiding both screen-resolution capture and OpenGL page
% rasterization.

if exist(pdfPath, 'file') == 2
    delete(pdfPath);
end

oldState = captureDecoderPrintState(fig);

set(fig, ...
    'Color', 'w', ...
    'Units', 'pixels');

figurePosition = get(fig, 'Position');

figureWidth = max(double(figurePosition(3)), 1);
figureHeight = max(double(figurePosition(4)), 1);
figureAspect = figureWidth ./ figureHeight;

pageWidth = 11;
pageHeight = 8.5;
margin = 0.25;

availableWidth = pageWidth - 2 .* margin;
availableHeight = pageHeight - 2 .* margin;
availableAspect = availableWidth ./ availableHeight;

if figureAspect >= availableAspect
    printedWidth = availableWidth;
    printedHeight = printedWidth ./ figureAspect;
else
    printedHeight = availableHeight;
    printedWidth = printedHeight .* figureAspect;
end

printedLeft = 0.5 .* ...
    (pageWidth - printedWidth);

printedBottom = 0.5 .* ...
    (pageHeight - printedHeight);

set(fig, ...
    'Renderer', 'painters', ...
    'PaperUnits', 'inches', ...
    'PaperSize', [pageWidth pageHeight], ...
    'PaperPosition', [ ...
        printedLeft, ...
        printedBottom, ...
        printedWidth, ...
        printedHeight], ...
    'PaperPositionMode', 'manual', ...
    'PaperOrientation', 'portrait', ...
    'InvertHardcopy', 'off');

drawnow;

try
    print(fig, ...
        pdfPath, ...
        '-dpdf', ...
        '-painters');
catch ME
    restoreDecoderPrintState(fig, oldState);
    rethrow(ME);
end

restoreDecoderPrintState(fig, oldState);

if exist(pdfPath, 'file') ~= 2
    error('runNeurometricOptostimDecoder:PDFPageSaveFailed', ...
        'The direct vector PDF page was not created: %s', ...
        pdfPath);
end

end


function oldState = captureDecoderPrintState(fig)

oldState = struct();
oldState.Color = get(fig, 'Color');
oldState.Renderer = get(fig, 'Renderer');
oldState.Units = get(fig, 'Units');
oldState.PaperUnits = get(fig, 'PaperUnits');
oldState.PaperSize = get(fig, 'PaperSize');
oldState.PaperPosition = get(fig, 'PaperPosition');
oldState.PaperPositionMode = ...
    get(fig, 'PaperPositionMode');
oldState.PaperOrientation = ...
    get(fig, 'PaperOrientation');
oldState.InvertHardcopy = ...
    get(fig, 'InvertHardcopy');

end


function restoreDecoderPrintState( ...
    fig, oldState)

set(fig, ...
    'Color', oldState.Color, ...
    'Renderer', oldState.Renderer, ...
    'Units', oldState.Units, ...
    'PaperUnits', oldState.PaperUnits, ...
    'PaperSize', oldState.PaperSize, ...
    'PaperPosition', oldState.PaperPosition, ...
    'PaperPositionMode', ...
        oldState.PaperPositionMode, ...
    'PaperOrientation', ...
        oldState.PaperOrientation, ...
    'InvertHardcopy', ...
        oldState.InvertHardcopy);

end


function pdfPath = finalizeDecoderMultiPagePDF( ...
    pagePaths, options, reportContext)
%FINALIZEDECODERMULTIPAGEPDF Merge four local pages and publish atomically.
%
% The four vector pages and the merged report are created on the local
% system drive. Only the completed report is copied to the network output
% directory. The final filename is timestamped, so an older PDF can remain
% open without causing permission-denied errors.

expectedPageCount = 4;

if numel(pagePaths) ~= expectedPageCount
    cleanupDecoderReportTempDirectory( ...
        reportContext.tempDir);

    error('runNeurometricOptostimDecoder:WrongPDFPageCount', ...
        'Expected %d decoder PDF pages, but received %d.', ...
        expectedPageCount, ...
        numel(pagePaths));
end

for pageIndex = 1:expectedPageCount
    if exist(pagePaths{pageIndex}, 'file') ~= 2
        error('runNeurometricOptostimDecoder:MissingPDFPage', ...
            ['Decoder PDF page %d is missing:\n%s\n\n' ...
             'The local staging directory was retained:\n%s'], ...
            pageIndex, ...
            pagePaths{pageIndex}, ...
            reportContext.tempDir);
    end
end

ghostscriptPath = ...
    findDecoderGhostscriptExecutable();

if exist(reportContext.localMergedPDF, 'file') == 2
    delete(reportContext.localMergedPDF);
end

inputArguments = '';

for pageIndex = 1:expectedPageCount
    inputArguments = sprintf( ...
        '%s "%s"', ...
        inputArguments, ...
        pagePaths{pageIndex});
end

ghostscriptCommand = sprintf([ ...
    '"%s" ' ...
    '-q ' ...
    '-dNOPAUSE ' ...
    '-dBATCH ' ...
    '-dNOSAFER ' ...
    '-sDEVICE=pdfwrite ' ...
    '-dAutoRotatePages=/None ' ...
    '-dCompatibilityLevel=1.4 ' ...
    '-dDetectDuplicateImages=false ' ...
    '-dDownsampleColorImages=false ' ...
    '-dDownsampleGrayImages=false ' ...
    '-dDownsampleMonoImages=false ' ...
    '-sOutputFile="%s"%s'], ...
    ghostscriptPath, ...
    reportContext.localMergedPDF, ...
    inputArguments);

[mergeStatus, mergeOutput] = ...
    system(ghostscriptCommand);

if mergeStatus ~= 0 || ...
        exist(reportContext.localMergedPDF, 'file') ~= 2

    error('runNeurometricOptostimDecoder:PDFMergeFailed', ...
        ['Direct local Ghostscript merge failed.\n\n' ...
         'Command output:\n%s\n\n' ...
         'The four local PDF pages were retained in:\n%s'], ...
        mergeOutput, ...
        reportContext.tempDir);
end

actualPageCount = countDecoderPDFPages( ...
    ghostscriptPath, ...
    reportContext.localMergedPDF);

if isfinite(actualPageCount) && ...
        actualPageCount ~= expectedPageCount

    error('runNeurometricOptostimDecoder:WrongMergedPDFPageCount', ...
        ['The locally merged report contains %d pages instead of %d.\n' ...
         'The local staging directory was retained:\n%s'], ...
        actualPageCount, ...
        expectedPageCount, ...
        reportContext.tempDir);
end

% Copy to a new output filename. No existing network file is deleted or
% overwritten, so open PDF viewers cannot block this operation.
[copySucceeded, copyMessage] = copyfile( ...
    reportContext.localMergedPDF, ...
    reportContext.finalPDF);

if ~copySucceeded || ...
        exist(reportContext.finalPDF, 'file') ~= 2

    error('runNeurometricOptostimDecoder:PDFPublishFailed', ...
        ['The completed local decoder report could not be copied to:\n' ...
         '%s\n\n%s\n\n' ...
         'The complete local report remains available at:\n%s'], ...
        reportContext.finalPDF, ...
        copyMessage, ...
        reportContext.localMergedPDF);
end

pdfPath = reportContext.finalPDF;

if isfinite(actualPageCount)
    fprintf(['Saved decoder PDF report with %d verified vector pages:\n' ...
        '  %s\n'], ...
        actualPageCount, ...
        pdfPath);
else
    fprintf(['Saved decoder PDF report from four explicit vector pages:\n' ...
        '  %s\n'], ...
        pdfPath);
end

cleanupDecoderReportTempDirectory( ...
    reportContext.tempDir);

end


function cleanupDecoderReportTempDirectory( ...
    tempDirectory)

if isempty(tempDirectory) || ...
        exist(tempDirectory, 'dir') ~= 7

    return;
end

try
    rmdir(tempDirectory, 's');
catch
    % Cleanup is noncritical. Do not turn a successfully saved report into
    % a failed analysis merely because Windows retained a transient handle.
end

end


function ghostscriptPath = ...
    findDecoderGhostscriptExecutable()

candidateExecutables = { ...
    'gswin64c.exe', ...
    'gswin32c.exe'};

ghostscriptPath = '';

for candidateIndex = 1:numel(candidateExecutables)
    [whereStatus, whereOutput] = system( ...
        sprintf('where %s', ...
            candidateExecutables{candidateIndex}));

    if whereStatus ~= 0
        continue;
    end

    outputLines = regexp( ...
        strtrim(whereOutput), ...
        '\r\n|\n|\r', ...
        'split');

    for lineIndex = 1:numel(outputLines)
        candidatePath = strtrim(outputLines{lineIndex});

        if exist(candidatePath, 'file') == 2
            ghostscriptPath = candidatePath;
            return;
        end
    end
end

error('runNeurometricOptostimDecoder:GhostscriptNotFound', ...
    ['Neither gswin64c.exe nor gswin32c.exe was found on the ' ...
     'Windows PATH.']);

end


function pageCount = countDecoderPDFPages( ...
    ghostscriptPath, pdfPath)
%COUNTDECODERPDFPAGES Best-effort page-count verification.
%
% Verification is deliberately nonessential to report generation. The
% merged PDF has already been created from four explicit input files.
%
% First try pdfinfo when it is installed. Otherwise ask Ghostscript to
% inspect the trusted local PDF with -dNOSAFER. Ghostscript 10 enables
% SAFER by default, which was why the previous verification command could
% not open the newly created PDF even though the merge itself succeeded.

pageCount = NaN;

%% Preferred counter: pdfinfo

[whereStatus, whereOutput] = ...
    system('where pdfinfo.exe');

if whereStatus == 0
    outputLines = regexp( ...
        strtrim(whereOutput), ...
        '\r\n|\n|\r', ...
        'split');

    if ~isempty(outputLines)
        pdfInfoPath = strtrim(outputLines{1});

        if exist(pdfInfoPath, 'file') == 2
            [infoStatus, infoOutput] = system( ...
                sprintf('"%s" "%s"', ...
                    pdfInfoPath, ...
                    pdfPath));

            if infoStatus == 0
                pageToken = regexp( ...
                    infoOutput, ...
                    'Pages:\s*(\d+)', ...
                    'tokens', ...
                    'once');

                if ~isempty(pageToken)
                    pageCount = str2double( ...
                        pageToken{1});
                    return;
                end
            end
        end
    end
end

%% Fallback counter: Ghostscript

postScriptPath = strrep(pdfPath, '\', '/');
postScriptPath = strrep(postScriptPath, '(', '\(');
postScriptPath = strrep(postScriptPath, ')', '\)');

countCommand = sprintf([ ...
    '"%s" -q -dNODISPLAY -dNOSAFER ' ...
    '-c "(%s) (r) file runpdfbegin pdfpagecount = quit"'], ...
    ghostscriptPath, ...
    postScriptPath);

[countStatus, countOutput] = ...
    system(countCommand);

if countStatus ~= 0
    return;
end

numericTokens = regexp( ...
    strtrim(countOutput), ...
    '\d+', ...
    'match');

if ~isempty(numericTokens)
    pageCount = str2double( ...
        numericTokens{end});
end

end


function printNeurometricDecoderAudit(decoderResult)

fprintf('\n');
fprintf('=== neurometric-optostim decoder audit ===\n');

fprintf('decoder code version: %s\n', ...
    decoderResult.metadata.codeVersion);

fprintf(['decoder PDF backend: direct Painters vector pages staged ' ...
    'locally -> local four-page Ghostscript merge -> new timestamped ' ...
    'network PDF; no overwrite of open files']);

fprintf('signed PCA template correlation: %g\n', ...
    decoderResult.qc.templateCorrelation);

fprintf('pattern normalized stable cells: %d / %d\n', ...
    nnz(decoderResult.pattern.normalizedIsStable), ...
    numel(decoderResult.pattern.normalizedIsStable));

fprintf('domain normalized stable cells: %d / %d\n', ...
    nnz(decoderResult.domain.normalizedIsStable), ...
    numel(decoderResult.domain.normalizedIsStable));

fprintf('coactivation stable cells: %d / %d\n', ...
    nnz(decoderResult.domain.coactivationIsStable), ...
    numel(decoderResult.domain.coactivationIsStable));

benchmark = decoderResult.qc.visualOnlyBenchmark;

if isfield(benchmark, 'patternAccuracy')
    fprintf('visual-only pattern sign sanity accuracy: %g\n', ...
        benchmark.patternAccuracy);

    fprintf('visual-only domain sign sanity accuracy: %g\n', ...
        benchmark.domainAccuracy);
end

fprintf(['bias convention: negative=0-degree-like, ' ...
    'positive=90-degree-like\n']);

fprintf('=== end neurometric-optostim decoder audit ===\n');
fprintf('\n');

end


function textValue = formatBenchmarkText(benchmark)

if isfield(benchmark, 'patternAccuracy')
    textValue = sprintf([ ...
        'Visual-only sign sanity check\n\n' ...
        'Signed-pattern accuracy: %.3f\n' ...
        'Column-domain accuracy: %.3f\n\n' ...
        'Expected:\n' ...
        'V0 bias < 0\n' ...
        'V90 bias > 0\n\n' ...
        'This is not cross-validated\n' ...
        'trial-wise accuracy.'], ...
        benchmark.patternAccuracy, ...
        benchmark.domainAccuracy);
else
    textValue = benchmark.status;
end

end


function value = finiteMaxAbs(values)

values = values(isfinite(values));

if isempty(values)
    value = 1;
else
    value = max(abs(values));

    if value <= 0
        value = 1;
    end
end

end


function value = finiteMaxPositive(values)

values = values(isfinite(values));

if isempty(values)
    value = 1;
else
    value = max(values);

    if value <= 0
        value = 1;
    end
end

end


function r = safeDecoderCorrelation(x, y)

x = double(x(:));
y = double(y(:));

valid = isfinite(x) & isfinite(y);
x = x(valid);
y = y(valid);

if numel(x) < 2 || ...
        std(x) <= eps || ...
        std(y) <= eps

    r = NaN;
    return;
end

correlationMatrix = corrcoef(x, y);
r = correlationMatrix(1,2);

end


function output = mergeStructFields(base, override)

output = base;

if isempty(override)
    return;
end

overrideFields = fieldnames(override);

for fieldIndex = 1:numel(overrideFields)
    output.(overrideFields{fieldIndex}) = ...
        override.(overrideFields{fieldIndex});
end

end


function value = meanFiniteLogical(values)

values = double(values(:));
values = values(isfinite(values));

if isempty(values)
    value = NaN;
else
    value = mean(values);
end

end
