function [mdl, objectiveFunction] = getWeibullFreeAllModelFuncs(common)
    % Use provided constants if available, otherwise defaults
    if isfield(common, 'lowerAsymptoteBL'), lowerAsymptoteBL = common.lowerAsymptoteBL; else, lowerAsymptoteBL = 50; end
    if isfield(common, 'epsilon'), epsilon = common.epsilon; else, epsilon = 1e-6; end

    % Shared helper for a palindromic Weibull-based psychometric curve
    % A: horizontal “shift” param as coded in your original form
    % B: lower/central asymptote (at x==0)
    % alpha/beta: shape params
    weibullPal = @(x, A, B, alpha, beta) ...
        100 .* ((x==0) .* (B)) + ...
        [ ...
          fliplr(100 - (100 .* ((x>=0) .* ( ...
              (sign(x) .* (1 - exp(-((x)./alpha).^beta))) .* ((1-B) - A) + 1 - (1-B) ))))) ...
          + ...
          ((100 .* (x>=0) .* ( ...
              (sign(x) .* (1 - exp(-((x)./alpha).^beta))) .* (B - A) + 1 - B )) ) ...
           - 100 .* (x>=0)) ...
        ];

    % Baseline uses fixed B = lowerAsymptoteBL, A/alpha/beta from params(1:4)
    mdlBaseline = @(x, p) weibullPal(x, p(1), lowerAsymptoteBL, p(3), p(4));

    % Congruent opto uses params(5:8)
    mdlCon      = @(x, p) weibullPal(x, p(5),  p(6),              p(7), p(8));

    % Incongruent opto uses params(9:12)
    mdlIncon    = @(x, p) weibullPal(x, p(9),  p(10),             p(11), p(12));

    % First output: package the curves (so downstream code can keep both)
    mdl = struct('baseline', mdlBaseline, 'con', mdlCon, 'incon', mdlIncon);

    % Second output: objective function EXPECTING (params, data)
    % and using the field names produced by fitPsyMLE
    objectiveFunction = @(params, data) ...
        -sum( ...
            data.successBaseline .* log((mdlBaseline(data.xBaseline, params) + epsilon)/100) + ...
            (data.sumBaseline - data.successBaseline) .* log(1 - (mdlBaseline(data.xBaseline, params) + epsilon)/100) ...
        ) ...
        -sum( ...
            data.successConOpto .* log((mdlCon(data.xConOpto, params) + epsilon)/100) + ...
            (data.sumConOpto - data.successConOpto) .* log(1 - (mdlCon(data.xConOpto, params) + epsilon)/100) ...
        ) ...
        -sum( ...
            data.successInconOpto .* log((mdlIncon(data.xInconOpto, params) + epsilon)/100) + ...
            (data.sumInconOpto - data.successInconOpto) .* log(1 - (mdlIncon(data.xInconOpto, params) + epsilon)/100) ...
        );

end
