function testAnalyzePowerClusterRelevanceSynthetic
%TESTANALYZEPOWERCLUSTERRELEVANCESYNTHETIC Synthetic dominance checks.

    nBlocks = 36;
    rng(42);

    paramBL = repmat([3, 50, 15, 4], nBlocks, 1);
    dCon = randn(nBlocks, 4);
    dIncon = randn(nBlocks, 4);
    parameterContrast = dCon - dIncon;
    parameterContrast(:, 2) = linspace(-4, 4, nBlocks)' + ...
        0.1 .* randn(nBlocks, 1);
    dCon(:, 2) = parameterContrast(:, 2) ./ 2;
    dIncon(:, 2) = -parameterContrast(:, 2) ./ 2;

    clusterMdl = struct();
    clusterMdl.fittedParams = [paramBL, dCon, dIncon];
    clusterMdl.deltaBias = 5 + 8 .* parameterContrast(:, 2) + ...
        randn(nBlocks, 1);
    clusterMdl.deltaMask = randn(nBlocks, 1);
    clusterMdl.clusterBlocksIdx = (1:nBlocks)';

    energy = linspace(0.1, 7, nBlocks)';
    clusterMdl.deltaBias = clusterMdl.deltaBias + 0.5 .* energy;

    bitmapData = struct();
    bitmapData.meanPowerDensityWithinROI_mWmm2 = reshape( ...
        energy, 1, 1, []);
    bitmapData.totalPowerToOnPixelsWithinROI_mW = reshape( ...
        energy .* 1.2, 1, 1, []);
    bitmapData.projectorPowerDensity_mWmm2 = reshape( ...
        energy .* 0.8, 1, 1, []);
    bitmapData.nColumns = repmat(20, 1, nBlocks);
    bitmapData.pixelsON = repmat(100, 1, nBlocks);
    bitmapData.areaFinalROI = repmat(1, 1, nBlocks);
    bitmapData.areaPixelsONWithinROI = repmat(0.2, 1, nBlocks);
    bitmapData.spatialDutyCycleWithinROI = repmat(0.2, 1, nBlocks);
    bitmapData.temporalDutyCycle = repmat(0.5, 1, nBlocks);
    bitmapData.sensitivity = repmat(1, 1, nBlocks);
    bitmapData.adaptthresh = repmat(0.1, 1, nBlocks);

    clusterLabels = ones(nBlocks, 1);
    opts = struct('saveFlag', 0, 'makeFigures', false, ...
        'nBootstrap', 25, 'sourceMdlField', 'synthetic', ...
        'aggregateField', 'syntheticAggregate');

    relevanceStruct = analyzePowerClusterRelevance( ...
        clusterMdl, clusterLabels, bitmapData, opts);

    [~, dominantParam] = max( ...
        relevanceStruct.parameter.allBlocks.bias.percentOfModelR2);
    assert(dominantParam == 2, ...
        'Synthetic bias should be dominated by predictor B.');

    parameterTable = relevanceStruct.summaryTables.parameterShapley;
    assert(ismember('BShapleyR2', parameterTable.Properties.VariableNames), ...
        'Parameter table should store absolute Shapley R2.');
    assert(ismember('BPercentModelR2', parameterTable.Properties.VariableNames), ...
        'Parameter table should store percent model R2.');
    assert(ismember('BPercentModelR2CI025', ...
        parameterTable.Properties.VariableNames), ...
        'Parameter table should store bootstrap percent-model-R2 CI.');
    assert(ismember('OptimismCorrectedR2', ...
        parameterTable.Properties.VariableNames), ...
        'Parameter table should store optimism-corrected R2.');
    assert(ismember('MeanOptimism', parameterTable.Properties.VariableNames), ...
        'Parameter table should store mean bootstrap optimism.');
    assert(ismember('LeaveOneOutPredictiveR2', ...
        parameterTable.Properties.VariableNames), ...
        'Parameter table should store leave-one-out predictive R2.');
    assert(ismember('AdjustedR2', parameterTable.Properties.VariableNames), ...
        'Parameter table should store adjusted R2.');
    assert(ismember('BApproxContributionR2', ...
        parameterTable.Properties.VariableNames), ...
        'Parameter table should store approximate absolute contribution R2.');
    assert(~isempty(relevanceStruct.summaryTables.parameterShapleyByCluster), ...
        'Parameter by-cluster Shapley table should be stored.');
    clusterDiagnostic = relevanceStruct.summaryTables.parameterClusterDiagnostic;
    assert(height(clusterDiagnostic) == 4, ...
        'Parameter cluster diagnostic table should include pooled plus C1-C3.');
    assert(strcmp(clusterDiagnostic.RowLabel{1}, 'All pooled'), ...
        'First diagnostic row should summarize all pooled sessions.');
    assert(strcmp(clusterDiagnostic.RowLabel{3}, 'Power cluster 2'), ...
        'Diagnostic table should keep fixed power-cluster rows.');
    assert(strcmp(clusterDiagnostic.RowStatus{3}, 'underpowered'), ...
        'Missing or too-small clusters should be marked underpowered.');
    assert(ismember('BiasTopParameterPercent', ...
        clusterDiagnostic.Properties.VariableNames), ...
        'Diagnostic table should store top-parameter percentages.');
    assert(ismember('BiasOptimismCorrectedR2', ...
        clusterDiagnostic.Properties.VariableNames), ...
        'Diagnostic table should display optimism-corrected R2.');
    assert(ismember('BiasLeaveOneOutPredictiveR2', ...
        clusterDiagnostic.Properties.VariableNames), ...
        'Diagnostic table should keep LOO R2 as a secondary field.');
    assert(isfinite(parameterTable.OptimismCorrectedR2(1)), ...
        'Well-behaved synthetic data should have finite optimism-corrected R2.');
    assert(parameterTable.OptimismCorrectedR2(1) <= ...
        parameterTable.ApparentR2(1) + 1e-10, ...
        'Optimism-corrected R2 should not exceed apparent R2 here.');

    noiseStruct = clusterMdl;
    rng(7);
    noiseStruct.deltaBias = randn(nBlocks, 1);
    noiseRelevance = analyzePowerClusterRelevance( ...
        noiseStruct, clusterLabels, bitmapData, opts);
    noiseR2 = noiseRelevance.parameter.allBlocks.bias.optimismCorrectedR2;
    assert(~isfinite(noiseR2) || noiseR2 < 0.10, ...
        'Noise-only data should have low or negative optimism-corrected R2.');

    sourceText = fileread(fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
        'analyzePowerClusterRelevance.m'));
    assert(isempty(strfind(sourceText, 'tiledlayout')), ...
        'Code should remain MATLAB 2018b-compatible: no tiledlayout.');
    assert(isempty(strfind(sourceText, 'nexttile')), ...
        'Code should remain MATLAB 2018b-compatible: no nexttile.');
    assert(isempty(strfind(sourceText, 'Y:\')), ...
        'Relevance code should not hard-code server scans.');

    stimDiagnostics = relevanceStruct.summaryTables.stimulationPredictorDiagnostics;
    assert(any(strcmp(stimDiagnostics.Family, 'Spatial factors')), ...
        'Stimulation diagnostics should label spatial factors.');
    assert(any(strcmp(stimDiagnostics.Family, 'Temporal factors')), ...
        'Stimulation diagnostics should label temporal factors.');
    assert(~any(strcmp(stimDiagnostics.Family, 'Coverage')), ...
        'Stimulation diagnostics should not use the old Coverage label.');

    familyTable = relevanceStruct.summaryTables.stimulationFamilyShapley;
    assert(ismember('EnergyShapleyR2', familyTable.Properties.VariableNames), ...
        'Family table should store absolute Energy Shapley R2.');
    assert(ismember('EnergyPercentModelR2', ...
        familyTable.Properties.VariableNames), ...
        'Family table should store Energy percent model R2.');
    assert(ismember('OptimismCorrectedR2', ...
        familyTable.Properties.VariableNames), ...
        'Family table should store optimism-corrected R2.');
    assert(ismember('LeaveOneOutPredictiveR2', ...
        familyTable.Properties.VariableNames), ...
        'Family table should store leave-one-out predictive R2.');
    assert(ismember('EnergyApproxContributionR2', ...
        familyTable.Properties.VariableNames), ...
        'Family table should store approximate absolute contribution R2.');
    assert(~isempty(relevanceStruct.summaryTables.stimulationFamilyScores), ...
        'Family-score predictor table should be stored.');
    assert(~isempty(relevanceStruct.summaryTables.stimulationFamilyShapleyByCluster), ...
        'Stimulation by-cluster Shapley table should be stored.');

    [~, dominantFamily] = max( ...
        relevanceStruct.stimulation.allBlocks.bias.groupedPercentOfModelR2);
    energyIdx = find(strcmp( ...
        relevanceStruct.stimulation.allBlocks.bias.familyNames, 'Energy'));
    assert(dominantFamily == energyIdx, ...
        'Synthetic stimulation relevance should be dominated by Energy.');
end
