function [mdl, objectiveFunction] = getWeibullSignedBX0ModelFuncs(common)
%GETWEIBULLSIGNEDBX0MODELFUNCS Model and likelihood for signed B+X0 Weibull.
%
% Parameter order:
%   1  A_baseline
%   2  alpha_baseline
%   3  beta_baseline
%   4  A_con
%   5  alpha_con
%   6  beta_con
%   7  A_incon
%   8  alpha_incon
%   9  beta_incon
%   10 deltaB
%   11 deltaX0

if isfield(common, 'epsilon')
    epsilon = common.epsilon;
else
    epsilon = 1e-10;
end
if isfield(common, 'maxSlopePctPerContrast')
    maxSlopePctPerContrast = common.maxSlopePctPerContrast;
else
    maxSlopePctPerContrast = 5.0;
end

mdl = struct();
mdl.modelVersion = 'fullBeta_slopeCap_v1';
mdl.parameterNames = signedBX0ParameterNames();
mdl.maxSlopePctPerContrast = maxSlopePctPerContrast;
mdl.signed = @(x, params) signedPredictions(x, params);
mdl.baseline = @(x, params) foldedPredictions(x, params);
mdl.con = @(x, params) foldedPredictions(x, params);
mdl.incon = @(x, params) foldedPredictions(x, params);
mdl.slopeDiagnostics = @(params) getWeibullSignedBX0SlopeDiagnostics(...
    params, maxSlopePctPerContrast);
mdl.binomialNLL = @(params, data) signedBinomialNLL(params, data, epsilon);

objectiveFunction = @(params, data) signedConstrainedNLL( ...
    params, data, epsilon, maxSlopePctPerContrast);
end

function y = signedPredictions(x, params)
effective = unpackSignedBX0Params(params);
y = struct();
y.pBaseline = weibullSignedBX0Mdl(x, ...
    effective.baseline.ALeft, effective.baseline.alphaLeft, ...
    effective.baseline.betaLeft, effective.baseline.ARight, ...
    effective.baseline.alphaRight, effective.baseline.betaRight, ...
    effective.baseline.B, effective.baseline.X0);
y.pHorizontalOpto = weibullSignedBX0Mdl(x, ...
    effective.horizontal.ALeft, effective.horizontal.alphaLeft, ...
    effective.horizontal.betaLeft, effective.horizontal.ARight, ...
    effective.horizontal.alphaRight, effective.horizontal.betaRight, ...
    effective.horizontal.B, effective.horizontal.X0);
y.pVerticalOpto = weibullSignedBX0Mdl(x, ...
    effective.vertical.ALeft, effective.vertical.alphaLeft, ...
    effective.vertical.betaLeft, effective.vertical.ARight, ...
    effective.vertical.alphaRight, effective.vertical.betaRight, ...
    effective.vertical.B, effective.vertical.X0);
end

function y = foldedPredictions(x, params)
% Convert signed choice-vertical predictions into the folded percent-correct
% convention used by the existing six-panel psychometric display.
c = abs(x);
effective = unpackSignedBX0Params(params);

pBLneg = weibullSignedBX0Mdl(-c, ...
    effective.baseline.ALeft, effective.baseline.alphaLeft, ...
    effective.baseline.betaLeft, effective.baseline.ARight, ...
    effective.baseline.alphaRight, effective.baseline.betaRight, ...
    effective.baseline.B, effective.baseline.X0);
pBLpos = weibullSignedBX0Mdl(+c, ...
    effective.baseline.ALeft, effective.baseline.alphaLeft, ...
    effective.baseline.betaLeft, effective.baseline.ARight, ...
    effective.baseline.alphaRight, effective.baseline.betaRight, ...
    effective.baseline.B, effective.baseline.X0);

pHneg = weibullSignedBX0Mdl(-c, ...
    effective.horizontal.ALeft, effective.horizontal.alphaLeft, ...
    effective.horizontal.betaLeft, effective.horizontal.ARight, ...
    effective.horizontal.alphaRight, effective.horizontal.betaRight, ...
    effective.horizontal.B, effective.horizontal.X0);
pHpos = weibullSignedBX0Mdl(+c, ...
    effective.horizontal.ALeft, effective.horizontal.alphaLeft, ...
    effective.horizontal.betaLeft, effective.horizontal.ARight, ...
    effective.horizontal.alphaRight, effective.horizontal.betaRight, ...
    effective.horizontal.B, effective.horizontal.X0);

pVneg = weibullSignedBX0Mdl(-c, ...
    effective.vertical.ALeft, effective.vertical.alphaLeft, ...
    effective.vertical.betaLeft, effective.vertical.ARight, ...
    effective.vertical.alphaRight, effective.vertical.betaRight, ...
    effective.vertical.B, effective.vertical.X0);
pVpos = weibullSignedBX0Mdl(+c, ...
    effective.vertical.ALeft, effective.vertical.alphaLeft, ...
    effective.vertical.betaLeft, effective.vertical.ARight, ...
    effective.vertical.alphaRight, effective.vertical.betaRight, ...
    effective.vertical.B, effective.vertical.X0);

y.pcntrl = 0.5 .* ((100 - pBLneg) + pBLpos);
y.pc = 0.5 .* ((100 - pHneg) + pVpos);
y.pic = 0.5 .* (pHpos + (100 - pVneg));
end

function nLL = signedConstrainedNLL(params, data, epsilon, maxSlopePctPerContrast)
if numel(params) ~= 11 || any(~isfinite(params(:)))
    nLL = 1e12;
    return;
end
slopeDiagnostics = getWeibullSignedBX0SlopeDiagnostics(...
    params, maxSlopePctPerContrast);
if ~slopeDiagnostics.isValid
    excess = slopeDiagnostics.slopeExcess;
    excess(~isfinite(excess)) = maxSlopePctPerContrast;
    nLL = 1e12 + 1e6 .* sum(excess .^ 2);
    return;
end
nLL = signedBinomialNLL(params, data, epsilon);
end

function nLL = signedBinomialNLL(params, data, epsilon)
if numel(params) ~= 11 || any(~isfinite(params(:)))
    nLL = 1e12;
    return;
end
effective = unpackSignedBX0Params(params);
if ~isSignedBX0ParamsValid(effective)
    nLL = 1e12;
    return;
end

pBaseline = weibullSignedBX0Mdl(data.xBaselineChoice, ...
    effective.baseline.ALeft, effective.baseline.alphaLeft, ...
    effective.baseline.betaLeft, effective.baseline.ARight, ...
    effective.baseline.alphaRight, effective.baseline.betaRight, ...
    effective.baseline.B, effective.baseline.X0) ./ 100;
pHorizontal = weibullSignedBX0Mdl(data.xHorizontalOptoChoice, ...
    effective.horizontal.ALeft, effective.horizontal.alphaLeft, ...
    effective.horizontal.betaLeft, effective.horizontal.ARight, ...
    effective.horizontal.alphaRight, effective.horizontal.betaRight, ...
    effective.horizontal.B, effective.horizontal.X0) ./ 100;
pVertical = weibullSignedBX0Mdl(data.xVerticalOptoChoice, ...
    effective.vertical.ALeft, effective.vertical.alphaLeft, ...
    effective.vertical.betaLeft, effective.vertical.ARight, ...
    effective.vertical.alphaRight, effective.vertical.betaRight, ...
    effective.vertical.B, effective.vertical.X0) ./ 100;

pBaseline = min(max(pBaseline, epsilon), 1 - epsilon);
pHorizontal = min(max(pHorizontal, epsilon), 1 - epsilon);
pVertical = min(max(pVertical, epsilon), 1 - epsilon);

nLL = ...
    conditionNLL(data.successBaselineChoice, ...
        data.sumBaselineChoice, pBaseline) + ...
    conditionNLL(data.successHorizontalOptoChoice, ...
        data.sumHorizontalOptoChoice, pHorizontal) + ...
    conditionNLL(data.successVerticalOptoChoice, ...
        data.sumVerticalOptoChoice, pVertical);
end

function effective = unpackSignedBX0Params(params)
params = params(:)';
if numel(params) ~= 11
    error('getWeibullSignedBX0ModelFuncs:InvalidParameterCount', ...
        'weibullSignedBX0 requires exactly 11 parameters; got %d.', ...
        numel(params));
end

effective.baseline = makeBranchParams( ...
    params(1), params(2), params(3), ...
    params(1), params(2), params(3), 50, 0);

effective.horizontal = makeBranchParams( ...
    params(4), params(5), params(6), ...
    params(7), params(8), params(9), ...
    50 - params(10), +params(11));

effective.vertical = makeBranchParams( ...
    params(7), params(8), params(9), ...
    params(4), params(5), params(6), ...
    50 + params(10), -params(11));

effective.deltaB = params(10);
effective.deltaX0 = params(11);
effective.parameterNames = signedBX0ParameterNames();
end

function branch = makeBranchParams(ALeft, alphaLeft, betaLeft, ...
        ARight, alphaRight, betaRight, B, X0)
branch = struct( ...
    'ALeft', ALeft, ...
    'alphaLeft', alphaLeft, ...
    'betaLeft', betaLeft, ...
    'ARight', ARight, ...
    'alphaRight', alphaRight, ...
    'betaRight', betaRight, ...
    'B', B, ...
    'X0', X0);
end

function isValid = isSignedBX0ParamsValid(effective)
conditions = {'baseline', 'horizontal', 'vertical'};
isValid = true;
for idx = 1:numel(conditions)
    branch = effective.(conditions{idx});
    branchValues = [branch.ALeft, branch.alphaLeft, branch.betaLeft, ...
        branch.ARight, branch.alphaRight, branch.betaRight, ...
        branch.B, branch.X0];
    if any(~isfinite(branchValues))
        isValid = false;
        return;
    end
    if branch.alphaLeft <= 0 || branch.alphaRight <= 0 || ...
            branch.betaLeft <= 1 || branch.betaRight <= 1
        isValid = false;
        return;
    end
    if ~(branch.ALeft < branch.B && branch.B < 100 - branch.ARight)
        isValid = false;
        return;
    end
end
end

function names = signedBX0ParameterNames()
names = {'A_baseline', 'alpha_baseline', 'beta_baseline', ...
    'A_con', 'alpha_con', 'beta_con', ...
    'A_incon', 'alpha_incon', 'beta_incon', ...
    'deltaB', 'deltaX0'};
end

function nLL = conditionNLL(successes, nTrials, probability)
failures = nTrials - successes;
nLL = -sum(successes .* log(probability) + ...
    failures .* log(1 - probability));
end