function [weibullModel, objectiveFunction] = getWeibullModelFuncs(common)
    weibullModel = @(x, params) weibullMdl(x, params);
        
    sumAll = @(x) sum(x(:));
    epsilon = 1e-10;
    objectiveFunction = @(params, data) ...
        - sumAll(data.successBaseline .* log(max(weibullModel(data.xBaseline, params).pcntrl/100, epsilon)) + ...
                  (data.sumBaseline - data.successBaseline) .* log(max(1 - weibullModel(data.xBaseline, params).pcntrl/100, epsilon))) ...
        - sumAll(data.successInconOpto .* log(max(weibullModel(data.xInconOpto, params).pic/100, epsilon)) + ...
                  (data.sumInconOpto - data.successInconOpto) .* log(max(1 - weibullModel(data.xInconOpto, params).pic/100, epsilon))) ...
        - sumAll(data.successConOpto .* log(max(weibullModel(data.xConOpto, params).pc/100, epsilon)) + ...
                  (data.sumConOpto - data.successConOpto) .* log(max(1 - weibullModel(data.xConOpto, params).pc/100, epsilon)));

end

