function audit = addDeltaBiasPermutationVisualization(ax, permResult, context)
% Add raw two-sided deltaBias permutation visualization to a merged bias panel.

    if nargin < 3
        context = struct();
    end
    audit = buildEmptyAudit();
    if isempty(permResult.contrast)
        warning('addDeltaBiasPermutationVisualization:NoContrasts', ...
            'No exact con/incon contrasts available for permutation visualization.');
        return;
    end

    if ~isfield(context, 'type') || ~strcmp(context.type, 'cluster')
        audit = buildAuditTables(permResult, context);
        [overallBandHandle, overallMedianHandle, overallHandle, noteHandle] = ...
            addOverallOnlyPermutationVisualization(ax, permResult);
        audit.visualization = buildOverallOnlyVisualizationAudit( ...
            overallBandHandle, overallMedianHandle, overallHandle, noteHandle);
        return;
    end

    yl = ylim(ax);
    annotationY = yl(2) - 0.06 .* diff(yl);
    boxWidth = chooseBoxWidth(permResult.contrast);
    nullHandles = gobjects(numel(permResult.contrast), 1);
    medianHandles = gobjects(numel(permResult.contrast), 1);
    labelHandles = gobjects(numel(permResult.contrast), 1);
    for ii = 1:numel(permResult.contrast)
        x = permResult.contrast(ii);
        lo = permResult.nullLower95(ii);
        hi = permResult.nullUpper95(ii);
        med = permResult.nullMedian(ii);
        if hi < lo
            error('addDeltaBiasPermutationVisualization:InvalidNullInterval', ...
                'Null interval lower bound exceeds upper bound at contrast %.6g.', x);
        end
        widthThis = boxWidth(ii);
        nullHandles(ii) = patch(ax, ...
            x + 0.5 .* widthThis .* [-1 1 1 -1], ...
            [lo lo hi hi], [0.65 0.65 0.65], ...
            'EdgeColor', [0.45 0.45 0.45], ...
            'LineWidth', 0.75, ...
            'FaceAlpha', 0.25, ...
            'Tag', 'DeltaPermNullInterval', ...
            'HandleVisibility', 'off');
        medianHandles(ii) = plot(ax, x + 0.35 .* widthThis .* [-1 1], [med med], '-', ...
            'Color', [0.35 0.35 0.35], 'LineWidth', 1.2, ...
            'Tag', 'DeltaPermNullMedian', 'HandleVisibility', 'off');
    end
    try
        oldPatches = findobj(ax, 'Type', 'Patch', '-not', 'Tag', 'DeltaPermNullInterval');
        oldLines = findobj(ax, 'Type', 'Line', '-not', 'Tag', 'DeltaPermNullMedian');
        if ~isempty(oldPatches)
            uistack(oldPatches, 'bottom');
        end
        uistack(nullHandles, 'top');
        uistack(medianHandles, 'top');
        if ~isempty(oldLines)
            uistack(oldLines, 'top');
        end
    catch
    end

    for ii = 1:numel(permResult.contrast)
        if permResult.significantUncorrected(ii)
            labelText = '*';
            labelFontSize = 15;
            labelFontWeight = 'bold';
        else
            labelText = 'n.s.';
            labelFontSize = 8;
            labelFontWeight = 'normal';
        end
        labelHandles(ii) = text(ax, permResult.contrast(ii), annotationY, labelText, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'Interpreter', 'none', ...
            'FontSize', labelFontSize, ...
            'FontWeight', labelFontWeight, ...
            'Clipping', 'off', ...
            'Tag', 'DeltaPermContrastLabel', ...
            'HandleVisibility', 'off');
    end

    try
        uistack(labelHandles, 'top');
    catch
    end

    overallHandle = addOverallAnnotation(ax, permResult);
    noteHandle = text(ax, 0.02, 0.03, sprintf('Gray boxes: permutation null 95%%\n* raw two-sided p < 0.05; uncorrected'), ...
        'Units', 'normalized', 'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', 'FontSize', 7, ...
        'Color', [0.25 0.25 0.25], 'Interpreter', 'none', ...
        'Tag', 'DeltaPermNote', 'HandleVisibility', 'off');

    try
        uistack([labelHandles(:); overallHandle; noteHandle], 'top');
    catch
    end

    audit = buildAuditTables(permResult, context);
    audit.visualization = buildVisualizationAudit(ax, nullHandles, medianHandles, labelHandles, overallHandle, noteHandle, annotationY);
end

function [bandHandle, medianHandle, overallHandle, noteHandle] = addOverallOnlyPermutationVisualization(ax, permResult)
    xLimits = xlim(ax);
    lower95 = permResult.nullMeanLower95;
    upper95 = permResult.nullMeanUpper95;
    nullMedian = permResult.nullMeanMedian;
    if upper95 < lower95
        error('addDeltaBiasPermutationVisualization:InvalidOverallNullInterval', ...
            'Overall null interval lower bound exceeds upper bound.');
    end

    bandHandle = patch(ax, ...
        [xLimits(1), xLimits(2), xLimits(2), xLimits(1)], ...
        [lower95, lower95, upper95, upper95], ...
        [0.65 0.65 0.65], ...
        'EdgeColor', 'none', ...
        'FaceAlpha', 0.15, ...
        'Tag', 'DeltaPermOverallNullBand', ...
        'HandleVisibility', 'off');
    medianHandle = plot(ax, xLimits, [nullMedian, nullMedian], '-', ...
        'Color', [0.4 0.4 0.4], ...
        'LineWidth', 1.0, ...
        'Tag', 'DeltaPermOverallNullMedian', ...
        'HandleVisibility', 'off');

    try
        uistack([bandHandle; medianHandle], 'bottom');
    catch
    end

    overallHandle = addOverallAnnotation(ax, permResult);
    noteHandle = text(ax, 0.02, 0.03, ...
        'Gray band: overall permutation null 95%', ...
        'Units', 'normalized', ...
        'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', ...
        'FontSize', 7, ...
        'Color', [0.25 0.25 0.25], ...
        'Interpreter', 'none', ...
        'Tag', 'DeltaPermNote', ...
        'HandleVisibility', 'off');
    try
        uistack([overallHandle; noteHandle], 'top');
    catch
    end
end

function visualization = buildOverallOnlyVisualizationAudit(bandHandle, medianHandle, overallHandle, noteHandle)
    handles = [bandHandle; medianHandle; overallHandle; noteHandle];
    visualization = struct( ...
        'nNullIntervals', 0, ...
        'nNullMedians', 0, ...
        'nLabels', 0, ...
        'nOverall', sum(isgraphics(overallHandle)), ...
        'nNullIntervalsFromHandles', 0, ...
        'nNullMediansFromHandles', 0, ...
        'nLabelsFromHandles', 0, ...
        'nOverallFromHandles', sum(isgraphics(overallHandle)), ...
        'nOverallNullBands', sum(isgraphics(bandHandle)), ...
        'nOverallNullMedians', sum(isgraphics(medianHandle)), ...
        'labelY', NaN, ...
        'labelsShareY', true, ...
        'allHandlesHidden', handlesAreHidden(handles), ...
        'nNote', sum(isgraphics(noteHandle)));
end
function visualization = buildVisualizationAudit(ax, nullHandles, medianHandles, labelHandles, overallHandle, noteHandle, annotationY)
    validNull = isgraphics(nullHandles);
    validMedians = isgraphics(medianHandles);
    validLabels = isgraphics(labelHandles);
    validOverall = isgraphics(overallHandle);
    validNote = isgraphics(noteHandle);
    labelY = nan(size(labelHandles));
    for ii = 1:numel(labelHandles)
        if validLabels(ii)
            pos = get(labelHandles(ii), 'Position');
            labelY(ii) = pos(2);
        end
    end
    labelsShareY = all(validLabels) && ...
        all(abs(labelY(validLabels) - annotationY) < 1e-9);
    visualization = struct( ...
        'nNullIntervals', sum(validNull), ...
        'nNullMedians', sum(validMedians), ...
        'nLabels', sum(validLabels), ...
        'nOverall', sum(validOverall), ...
        'nNullIntervalsFromHandles', sum(validNull), ...
        'nNullMediansFromHandles', sum(validMedians), ...
        'nLabelsFromHandles', sum(validLabels), ...
        'nOverallFromHandles', sum(validOverall), ...
        'labelY', annotationY, ...
        'labelsShareY', labelsShareY, ...
        'allHandlesHidden', handlesAreHidden([nullHandles(:); medianHandles(:); labelHandles(:); overallHandle(:); noteHandle(:)]), ...
        'nNote', sum(validNote));
end
function overallHandle = addOverallAnnotation(ax, permResult)
    if permResult.overallSignificant
        resultText = '*';
        resultFontSize = 15;
        resultFontWeight = 'bold';
    else
        resultText = 'n.s.';
        resultFontSize = 8;
        resultFontWeight = 'normal';
    end
    text(ax, 0.88, 0.84, 'Overall:', ...
        'Units', 'normalized', 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'bottom', 'FontSize', 8, ...
        'Interpreter', 'none', 'HandleVisibility', 'off');
    overallHandle = text(ax, 0.89, 0.84, resultText, ...
        'Units', 'normalized', 'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', 'FontSize', resultFontSize, ...
        'FontWeight', resultFontWeight, 'Interpreter', 'none', ...
        'Tag', 'DeltaPermOverallLabel', 'HandleVisibility', 'off');
    text(ax, 0.98, 0.77, formatPValue(permResult.rawOverallTwoSidedP), ...
        'Units', 'normalized', 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'bottom', 'FontSize', 8, ...
        'Interpreter', 'none', 'HandleVisibility', 'off');
end

function audit = buildAuditTables(permResult, context)
    audit = buildEmptyAudit();
    n = numel(permResult.contrast);
    correction = repmat("none", n, 1);
    if isfield(context, 'type') && strcmp(context.type, 'cluster')
        audit.clusterContrasts = table( ...
            repmat(context.clusterID, n, 1), ...
            permResult.contrast(:), ...
            permResult.nContributingExperiments(:), ...
            permResult.observedDeltaBias(:), ...
            permResult.nullMedian(:), ...
            permResult.nullLower95(:), ...
            permResult.nullUpper95(:), ...
            permResult.rawTwoSidedP(:), ...
            permResult.rawPositiveOneSidedP(:), ...
            permResult.significantUncorrected(:), ...
            correction, ...
            repmat(permResult.nPermutations, n, 1), ...
            'VariableNames', {'clusterID', 'contrast', ...
            'nContributingExperiments', 'observedAggregateDeltaBias', ...
            'nullMedian', 'nullLower95', 'nullUpper95', 'rawTwoSidedP', ...
            'rawPositiveOneSidedP', 'significantUncorrected', 'multipleComparisonCorrection', ...
            'nPermutations'});
        audit.clusterSummary = table( ...
            context.clusterID, n, permResult.observedMeanDeltaBias, ...
            permResult.nullMeanMedian, permResult.nullMeanLower95, ...
            permResult.nullMeanUpper95, permResult.rawOverallTwoSidedP, ...
            permResult.rawOverallPositiveOneSidedP, ...
            permResult.overallSignificant, permResult.nPermutations, ...
            'VariableNames', {'clusterID', 'nDisplayedContrasts', ...
            'observedMeanDeltaBias', 'nullMeanMedian', 'nullMeanLower95', ...
            'nullMeanUpper95', 'rawOverallTwoSidedP', ...
            'rawOverallPositiveOneSidedP', 'overallSignificant', 'nPermutations'});
    else
        audit.experimentContrasts = table( ...
            repmat(string(context.experimentID), n, 1), ...
            repmat(context.modelRow, n, 1), ...
            repmat(context.powerClusterID, n, 1), ...
            permResult.contrast(:), permResult.conPct(:), permResult.inconPct(:), ...
            permResult.observedDeltaBias(:), permResult.nullMedian(:), ...
            permResult.nullLower95(:), permResult.nullUpper95(:), ...
            permResult.rawTwoSidedP(:), permResult.rawPositiveOneSidedP(:), ...
            permResult.significantUncorrected(:), ...
            correction, permResult.nCon(:), permResult.nIncon(:), ...
            permResult.conCorrect(:), permResult.inconCorrect(:), ...
            permResult.conReconstructionErrorPct(:), ...
            permResult.inconReconstructionErrorPct(:), ...
            repmat(permResult.nPermutations, n, 1), ...
            'VariableNames', {'experimentID', 'modelRow', 'powerClusterID', ...
            'contrast', 'conPct', 'inconPct', 'observedDeltaBias', ...
            'nullMedian', 'nullLower95', 'nullUpper95', 'rawTwoSidedP', ...
            'rawPositiveOneSidedP', 'significantUncorrected', 'multipleComparisonCorrection', ...
            'nCon', 'nIncon', 'conCorrect', 'inconCorrect', ...
            'conReconstructionErrorPct', 'inconReconstructionErrorPct', ...
            'nPermutations'});
        audit.experimentSummary = table( ...
            string(context.experimentID), context.modelRow, context.powerClusterID, ...
            n, permResult.observedMeanDeltaBias, permResult.nullMeanMedian, ...
            permResult.nullMeanLower95, permResult.nullMeanUpper95, ...
            permResult.rawOverallTwoSidedP, ...
            permResult.rawOverallPositiveOneSidedP, ...
            permResult.overallSignificant, ...
            permResult.nPermutations, ...
            'VariableNames', {'experimentID', 'modelRow', 'powerClusterID', ...
            'nMatchedContrasts', 'observedMeanDeltaBias', 'nullMeanMedian', ...
            'nullMeanLower95', 'nullMeanUpper95', 'rawOverallTwoSidedP', ...
            'rawOverallPositiveOneSidedP', 'overallSignificant', 'nPermutations'});
    end
end

function audit = buildEmptyAudit()
    audit = struct('experimentContrasts', table(), ...
        'experimentSummary', table(), ...
        'clusterContrasts', table(), ...
        'clusterSummary', table());
end

function width = chooseBoxWidth(x)
    x = sort(x(:));
    width = repmat(5, size(x));
    if numel(x) < 2
        return;
    end
    for ii = 1:numel(x)
        distances = abs(x(ii) - x);
        distances = distances(distances > 0);
        if ~isempty(distances)
            width(ii) = 0.60 .* min(distances);
        end
    end
end

function tf = handlesAreHidden(handles)
    handles = handles(isgraphics(handles));
    if isempty(handles)
        tf = true;
        return;
    end
    tf = true;
    for ii = 1:numel(handles)
        tf = tf && strcmp(get(handles(ii), 'HandleVisibility'), 'off');
    end
end
function out = ternary(condition, firstValue, secondValue)
    if condition
        out = firstValue;
    else
        out = secondValue;
    end
end

function textValue = formatPValue(pValue)
    if ~isfinite(pValue)
        textValue = 'p = n/a';
    elseif pValue < 0.001
        textValue = 'p < 0.001';
    else
        textValue = sprintf('p = %.3f', pValue);
    end
end
