function audit = addDeltaBiasPermutationVisualization(ax, permResult, context)
% Add raw two-sided deltaBias permutation visualization to a merged bias panel.

    if nargin < 3
        context = struct();
    end
    audit = buildEmptyAudit();
    if isempty(permResult.contrast)
        warning('addDeltaBiasPermutationVisualization:NoContrasts', ...
            'No exact con/incon contrasts available for permutation visualization.');
        return;
    end

    yl = ylim(ax);
    annotationY = yl(2) - 0.06 .* diff(yl);
    boxWidth = chooseBoxWidth(permResult.contrast);
    nullHandles = gobjects(numel(permResult.contrast), 1);
    for ii = 1:numel(permResult.contrast)
        x = permResult.contrast(ii);
        lo = permResult.nullLower95(ii);
        hi = permResult.nullUpper95(ii);
        med = permResult.nullMedian(ii);
        nullHandles(ii) = patch(ax, ...
            x + 0.5 .* boxWidth .* [-1 1 1 -1], ...
            [lo lo hi hi], [0.88 0.88 0.88], ...
            'EdgeColor', [0.55 0.55 0.55], ...
            'LineWidth', 1.0, ...
            'FaceAlpha', 1, ...
            'DisplayName', 'Permutation null: central 95%', ...
            'HandleVisibility', ternary(ii == 1, 'on', 'off'));
        plot(ax, x + 0.35 .* boxWidth .* [-1 1], [med med], '-', ...
            'Color', [0.35 0.35 0.35], 'LineWidth', 1.2, ...
            'HandleVisibility', 'off');
    end
    try
        uistack(nullHandles, 'bottom');
    catch
    end

    for ii = 1:numel(permResult.contrast)
        if permResult.significantUncorrected(ii)
            labelText = '*';
            labelFontSize = 16;
            labelFontWeight = 'bold';
        else
            labelText = 'n.s.';
            labelFontSize = 9;
            labelFontWeight = 'normal';
        end
        text(ax, permResult.contrast(ii), annotationY, labelText, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'FontSize', labelFontSize, ...
            'FontWeight', labelFontWeight, ...
            'Clipping', 'off', ...
            'HandleVisibility', 'off');
    end

    addOverallAnnotation(ax, permResult);
    text(ax, 0.02, 0.03, '* raw two-sided p < 0.05; uncorrected', ...
        'Units', 'normalized', 'HorizontalAlignment', 'left', ...
        'VerticalAlignment', 'bottom', 'FontSize', 7, ...
        'Color', [0.25 0.25 0.25], 'HandleVisibility', 'off');

    audit = buildAuditTables(permResult, context);
end

function addOverallAnnotation(ax, permResult)
    text(ax, 0.98, 0.84, 'Overall:', ...
        'Units', 'normalized', 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle', 'FontSize', 9, ...
        'HandleVisibility', 'off');
    if permResult.overallSignificant
        resultText = '*';
        resultFontSize = 16;
        resultFontWeight = 'bold';
    else
        resultText = 'n.s.';
        resultFontSize = 9;
        resultFontWeight = 'normal';
    end
    text(ax, 0.98, 0.78, resultText, ...
        'Units', 'normalized', 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle', 'FontSize', resultFontSize, ...
        'FontWeight', resultFontWeight, 'HandleVisibility', 'off');
    text(ax, 0.98, 0.71, formatP2(permResult.rawOverallTwoSidedP), ...
        'Units', 'normalized', 'HorizontalAlignment', 'right', ...
        'VerticalAlignment', 'middle', 'FontSize', 9, ...
        'HandleVisibility', 'off');
end

function audit = buildAuditTables(permResult, context)
    audit = buildEmptyAudit();
    n = numel(permResult.contrast);
    correction = repmat("none", n, 1);
    if isfield(context, 'type') && strcmp(context.type, 'cluster')
        audit.clusterContrasts = table( ...
            repmat(context.clusterID, n, 1), ...
            permResult.contrast(:), ...
            permResult.nContributingExperiments(:), ...
            permResult.observedDeltaBias(:), ...
            permResult.nullMedian(:), ...
            permResult.nullLower95(:), ...
            permResult.nullUpper95(:), ...
            permResult.rawTwoSidedP(:), ...
            permResult.significantUncorrected(:), ...
            correction, ...
            repmat(permResult.nPermutations, n, 1), ...
            'VariableNames', {'clusterID', 'contrast', ...
            'nContributingExperiments', 'observedAggregateDeltaBias', ...
            'nullMedian', 'nullLower95', 'nullUpper95', 'rawTwoSidedP', ...
            'significantUncorrected', 'multipleComparisonCorrection', ...
            'nPermutations'});
        audit.clusterSummary = table( ...
            context.clusterID, n, permResult.observedMeanDeltaBias, ...
            permResult.nullMeanMedian, permResult.nullMeanLower95, ...
            permResult.nullMeanUpper95, permResult.rawOverallTwoSidedP, ...
            permResult.overallSignificant, permResult.nPermutations, ...
            'VariableNames', {'clusterID', 'nDisplayedContrasts', ...
            'observedMeanDeltaBias', 'nullMeanMedian', 'nullMeanLower95', ...
            'nullMeanUpper95', 'rawOverallTwoSidedP', ...
            'overallSignificant', 'nPermutations'});
    else
        audit.experimentContrasts = table( ...
            repmat(string(context.experimentID), n, 1), ...
            repmat(context.modelRow, n, 1), ...
            repmat(context.powerClusterID, n, 1), ...
            permResult.contrast(:), permResult.conPct(:), permResult.inconPct(:), ...
            permResult.observedDeltaBias(:), permResult.nullMedian(:), ...
            permResult.nullLower95(:), permResult.nullUpper95(:), ...
            permResult.rawTwoSidedP(:), permResult.significantUncorrected(:), ...
            correction, permResult.nCon(:), permResult.nIncon(:), ...
            permResult.conCorrect(:), permResult.inconCorrect(:), ...
            permResult.conReconstructionErrorPct(:), ...
            permResult.inconReconstructionErrorPct(:), ...
            repmat(permResult.nPermutations, n, 1), ...
            'VariableNames', {'experimentID', 'modelRow', 'powerClusterID', ...
            'contrast', 'conPct', 'inconPct', 'observedDeltaBias', ...
            'nullMedian', 'nullLower95', 'nullUpper95', 'rawTwoSidedP', ...
            'significantUncorrected', 'multipleComparisonCorrection', ...
            'nCon', 'nIncon', 'conCorrect', 'inconCorrect', ...
            'conReconstructionErrorPct', 'inconReconstructionErrorPct', ...
            'nPermutations'});
        audit.experimentSummary = table( ...
            string(context.experimentID), context.modelRow, context.powerClusterID, ...
            n, permResult.observedMeanDeltaBias, permResult.nullMeanMedian, ...
            permResult.nullMeanLower95, permResult.nullMeanUpper95, ...
            permResult.rawOverallTwoSidedP, permResult.overallSignificant, ...
            permResult.nPermutations, ...
            'VariableNames', {'experimentID', 'modelRow', 'powerClusterID', ...
            'nMatchedContrasts', 'observedMeanDeltaBias', 'nullMeanMedian', ...
            'nullMeanLower95', 'nullMeanUpper95', 'rawOverallTwoSidedP', ...
            'overallSignificant', 'nPermutations'});
    end
end

function audit = buildEmptyAudit()
    audit = struct('experimentContrasts', table(), ...
        'experimentSummary', table(), ...
        'clusterContrasts', table(), ...
        'clusterSummary', table());
end

function width = chooseBoxWidth(x)
    x = sort(x(:));
    dx = diff(unique(x));
    dx = dx(dx > 0);
    if isempty(dx)
        width = 2.5;
    else
        width = 0.30 .* min(dx);
    end
end

function out = ternary(condition, firstValue, secondValue)
    if condition
        out = firstValue;
    else
        out = secondValue;
    end
end

function textValue = formatP2(pValue)
    if ~isfinite(pValue)
        textValue = 'p_2 = n/a';
    elseif pValue < 0.001
        textValue = 'p_2 < 0.001';
    else
        textValue = sprintf('p_2 = %.3f', pValue);
    end
end
