function audit = auditPowerMetrics(bitmapData, blockIndices, experimentIDs, ...
        powerClusterAssignment, baselineModeByBlock)
% Build one row per experiment with canonical recomputed power values.

    if nargin < 2 || isempty(blockIndices)
        nBlocks = inferNBlocks(bitmapData);
        blockIndices = 1:nBlocks;
    end
    if nargin < 3
        experimentIDs = [];
    end
    if nargin < 4
        powerClusterAssignment = [];
    end
    if nargin < 5
        baselineModeByBlock = [];
    end

    blockIndices = blockIndices(:);
    nRows = numel(blockIndices);
    audit = table( ...
        nan(nRows, 1), strings(nRows, 1), nan(nRows, 1), ...
        strings(nRows, 1), nan(nRows, 1), nan(nRows, 1), ...
        nan(nRows, 1), nan(nRows, 1), nan(nRows, 1), ...
        nan(nRows, 1), nan(nRows, 1), nan(nRows, 1), ...
        nan(nRows, 1), nan(nRows, 1), nan(nRows, 1), ...
        nan(nRows, 1), nan(nRows, 1), nan(nRows, 1), ...
        nan(nRows, 1), nan(nRows, 1), nan(nRows, 1), ...
        nan(nRows, 1), false(nRows, 1), false(nRows, 1), ...
        false(nRows, 1), false(nRows, 1), false(nRows, 1), ...
        false(nRows, 1), ...
        'VariableNames', {'blockIndex', 'experimentID', ...
        'powerClusterAssignment', 'baselineMode', ...
        'PDDMD_stored', 'AreaROI_stored', 'AreaON_stored', ...
        'sDC_storedFraction', 'sDC_fromAreaFraction', ...
        'sDC_difference', 'sDC_relativeError', 'tDC_storedFraction', ...
        'PDROI_stored', 'PDROI_recomputed', ...
        'PDROI_difference', 'PDROI_relativeError', ...
        'Ptotal_stored', 'Ptotal_recomputed', 'Ptotal_fromPDROI', ...
        'Ptotal_difference', 'Ptotal_relativeError', ...
        'Ptotal_identityDifference', 'Ptotal_identityRelativeError', ...
        'sDC_pass', 'PDROI_pass', 'Ptotal_pass', ...
        'Ptotal_identityPass', 'pass'});

    for rowIdx = 1:nRows
        blockIdx = blockIndices(rowIdx);
        metrics = computePowerMetricsFromSource(bitmapData, blockIdx);
        summary = metrics.summary;
        audit.blockIndex(rowIdx) = blockIdx;
        audit.experimentID(rowIdx) = lookupStringByBlock(experimentIDs, blockIdx);
        audit.powerClusterAssignment(rowIdx) = ...
            lookupNumericByBlock(powerClusterAssignment, blockIdx);
        audit.baselineMode(rowIdx) = ...
            lookupStringByBlock(baselineModeByBlock, blockIdx);
        audit.PDDMD_stored(rowIdx) = summary.projectorPowerDensity;
        audit.AreaROI_stored(rowIdx) = summary.areaROI;
        audit.AreaON_stored(rowIdx) = summary.areaON;
        audit.sDC_storedFraction(rowIdx) = summary.spatialDutyCycleStoredFraction;
        audit.sDC_fromAreaFraction(rowIdx) = summary.spatialDutyCycleFraction;
        audit.sDC_difference(rowIdx) = ...
            audit.sDC_storedFraction(rowIdx) - audit.sDC_fromAreaFraction(rowIdx);
        audit.sDC_relativeError(rowIdx) = summary.maxRelSDCError;
        audit.tDC_storedFraction(rowIdx) = summary.temporalDutyCycleFraction;
        audit.PDROI_stored(rowIdx) = summary.roiPowerDensityStored;
        audit.PDROI_recomputed(rowIdx) = summary.roiPowerDensityRecomputed;
        audit.PDROI_difference(rowIdx) = ...
            audit.PDROI_recomputed(rowIdx) - audit.PDROI_stored(rowIdx);
        audit.PDROI_relativeError(rowIdx) = summary.maxRelPDROIError;
        audit.Ptotal_stored(rowIdx) = summary.totalPowerStored;
        audit.Ptotal_recomputed(rowIdx) = summary.totalPowerRecomputed;
        audit.Ptotal_fromPDROI(rowIdx) = summary.totalPowerFromPDROI;
        audit.Ptotal_difference(rowIdx) = ...
            audit.Ptotal_recomputed(rowIdx) - audit.Ptotal_stored(rowIdx);
        audit.Ptotal_relativeError(rowIdx) = summary.maxRelPtotalError;
        audit.Ptotal_identityDifference(rowIdx) = ...
            audit.Ptotal_recomputed(rowIdx) - audit.Ptotal_fromPDROI(rowIdx);
        audit.Ptotal_identityRelativeError(rowIdx) = ...
            summary.maxRelPtotalIdentityError;
        audit.sDC_pass(rowIdx) = summary.sDCPass;
        audit.PDROI_pass(rowIdx) = summary.PDROIPass;
        audit.Ptotal_pass(rowIdx) = summary.PtotalPass;
        audit.Ptotal_identityPass(rowIdx) = summary.PtotalIdentityPass;
        audit.pass(rowIdx) = metrics.pass;
    end

    printPowerAuditSummary(audit);
end

function nBlocks = inferNBlocks(bitmapData)
    nBlocks = 0;
    if isfield(bitmapData, 'nColumns') && ~isempty(bitmapData.nColumns)
        nBlocks = size(bitmapData.nColumns, ndims(bitmapData.nColumns));
    elseif isfield(bitmapData, 'totalPowerToOnPixelsWithinROI_mW') && ...
            ~isempty(bitmapData.totalPowerToOnPixelsWithinROI_mW)
        fieldData = bitmapData.totalPowerToOnPixelsWithinROI_mW;
        nBlocks = size(fieldData, ndims(fieldData));
    end
end

function value = lookupStringByBlock(values, blockIdx)
    value = "";
    if isempty(values) || ~isfinite(blockIdx) || blockIdx < 1
        return;
    end
    if numel(values) >= blockIdx
        value = string(values(blockIdx));
    end
end

function value = lookupNumericByBlock(values, blockIdx)
    value = NaN;
    if isempty(values) || ~isfinite(blockIdx) || blockIdx < 1
        return;
    end
    if numel(values) >= blockIdx
        value = values(blockIdx);
    end
end

function printPowerAuditSummary(audit)
    nRows = height(audit);
    nPass = sum(audit.pass);
    nFail = nRows - nPass;
    fprintf(['Power metrics audit: %d experiments checked | %d pass | ' ...
        '%d fail | max |sDC rel err|=%0.3g | ' ...
        'max |PDROI rel err|=%0.3g | max |Ptotal rel err|=%0.3g | ' ...
        'max |Ptotal identity rel err|=%0.3g\n'], ...
        nRows, nPass, nFail, ...
        max(audit.sDC_relativeError, [], 'omitnan'), ...
        max(audit.PDROI_relativeError, [], 'omitnan'), ...
        max(audit.Ptotal_relativeError, [], 'omitnan'), ...
        max(audit.Ptotal_identityRelativeError, [], 'omitnan'));
    if nFail > 0
        failedRows = audit(~audit.pass, :);
        warning('auditPowerMetrics:FormulaMismatch', ...
            '%d experiments failed canonical power formula checks.', nFail);
        for idx = 1:height(failedRows)
            fprintf(['  Power mismatch block=%g experiment=%s: ' ...
                'PDDMD=%0.6g AreaROI=%0.6g AreaON=%0.6g ' ...
                'sDCstored=%0.6g sDCarea=%0.6g tDC=%0.6g; ' ...
                'PDROI stored=%0.6g recomputed=%0.6g diff=%0.3g; ' ...
                'Ptotal stored=%0.6g recomputed=%0.6g ' ...
                'fromPDROI=%0.6g diff=%0.3g identityDiff=%0.3g\n'], ...
                failedRows.blockIndex(idx), failedRows.experimentID(idx), ...
                failedRows.PDDMD_stored(idx), ...
                failedRows.AreaROI_stored(idx), ...
                failedRows.AreaON_stored(idx), ...
                failedRows.sDC_storedFraction(idx), ...
                failedRows.sDC_fromAreaFraction(idx), ...
                failedRows.tDC_storedFraction(idx), ...
                failedRows.PDROI_stored(idx), ...
                failedRows.PDROI_recomputed(idx), ...
                failedRows.PDROI_difference(idx), ...
                failedRows.Ptotal_stored(idx), ...
                failedRows.Ptotal_recomputed(idx), ...
                failedRows.Ptotal_fromPDROI(idx), ...
                failedRows.Ptotal_difference(idx), ...
                failedRows.Ptotal_identityDifference(idx));
        end
    end
end
