function audit = buildDistributionStatsAuditRows( ...
        item, figureType, panelRow, panelColumn, metricOrParameter, ...
        correctionFamilyID, results, annotationInfo, ...
        sessionRows, blockIndices, experimentIDs)
% Build one statistics-audit row per comparison in a plot panel.

    audit = emptyDistributionStatsAuditTable();
    sessionRows = sessionRows(:);
    blockIndices = blockIndices(:);
    experimentIDs = string(experimentIDs(:));
    if numel(blockIndices) ~= numel(sessionRows) || ...
            numel(experimentIDs) ~= numel(sessionRows)
        error('buildDistributionStatsAuditRows:MetadataSizeMismatch', ...
            'Session, block, and experiment metadata must have equal lengths.');
    end

    datasetLabel = getDatasetLabel(item);
    clusterID = getClusterID(item);
    for resultIdx = 1:numel(results)
        result = results(resultIdx);
        validRows = result.validRows(:);
        if any(validRows < 1 | validRows > numel(sessionRows))
            error('buildDistributionStatsAuditRows:InvalidRows', ...
                'Comparison validRows exceed the supplied session metadata.');
        end

        [annotationDrawn, annotationStatus] = ...
            getAnnotationStatus(annotationInfo, resultIdx);
        [directionApplicable, allExpectedDirection] = ...
            expectedDirectionSummary(result.differences, result.plannedTail);

        newRow = emptyDistributionStatsAuditTable();
        newRow(1, :) = { ...
            datasetLabel, clusterID, string(figureType), ...
            string(panelRow), string(panelColumn), ...
            string(metricOrParameter), string(result.comparison), ...
            string(correctionFamilyID), result.familySize, ...
            "Holm-Bonferroni within panel", string(result.test), ...
            string(result.testDirection), ...
            string(result.alternativeHypothesis), result.n, ...
            result.nWilcoxonNonzero, ...
            numericVectorText(sessionRows(validRows)), ...
            numericVectorText(blockIndices(validRows)), ...
            stringVectorText(experimentIDs(validRows)), ...
            numericVectorText(result.xValues), ...
            numericVectorText(result.yValues), ...
            numericVectorText(result.differences), ...
            result.meanDifference, result.medianDifference, ...
            result.semDifference, result.nPositive, ...
            result.nNegative, result.nZero, ...
            result.rawP, result.adjustedP, ...
            result.minPossibleTwoSidedRawP, ...
            result.minPossibleOneSidedRawP, ...
            result.minPossibleAnnotationRawP, ...
            result.minPossibleAnnotationAdjustedP, ...
            result.pairedTTestRawP, result.pairedTTestAdjustedP, ...
            result.tStatistic, result.pairedTTestN, ...
            string(result.plannedAlternativeHypothesis), ...
            result.plannedRawP, result.plannedAdjustedP, ...
            string(result.plannedStar), directionApplicable, ...
            allExpectedDirection, string(result.star), ...
            annotationDrawn, annotationStatus};
        audit = [audit; newRow]; %#ok<AGROW>
    end
end

function label = getDatasetLabel(item)
    if isfield(item, 'columnTargetLabel') && ...
            ~isempty(item.columnTargetLabel)
        label = string(item.columnTargetLabel);
    else
        label = "unknown";
    end
end

function clusterID = getClusterID(item)
    if isfield(item, 'clusterID') && isscalar(item.clusterID)
        clusterID = double(item.clusterID);
    else
        clusterID = nan;
    end
end

function [drawn, status] = getAnnotationStatus(annotationInfo, resultIdx)
    drawn = false;
    status = "not available";
    if isempty(annotationInfo) || ...
            ~isfield(annotationInfo, 'drawnMask') || ...
            resultIdx > numel(annotationInfo.drawnMask)
        return;
    end
    drawn = logical(annotationInfo.drawnMask(resultIdx));
    if drawn
        status = "drawn";
    elseif isfield(annotationInfo, 'skippedReasons') && ...
            resultIdx <= numel(annotationInfo.skippedReasons)
        status = "skipped: " + ...
            string(annotationInfo.skippedReasons{resultIdx});
    else
        status = "skipped";
    end
end

function [applicable, allExpected] = ...
        expectedDirectionSummary(differences, plannedTail)
    applicable = ~strcmp(plannedTail, 'both');
    allExpected = false;
    if isempty(differences) || ~applicable
        return;
    end
    if strcmp(plannedTail, 'right')
        allExpected = all(differences > 0);
    else
        allExpected = all(differences < 0);
    end
end

function textValue = numericVectorText(values)
    values = values(:)';
    if isempty(values)
        textValue = "[]";
    else
        textValue = string(mat2str(values, 15));
    end
end

function textValue = stringVectorText(values)
    values = string(values(:));
    if isempty(values)
        textValue = "[]";
    else
        textValue = "[" + strjoin(values, ", ") + "]";
    end
end
