function audit = emptyDistributionSourceAuditTable()
% Return an empty source-audit table with stable column types.

    audit = table( ...
        strings(0, 1), ...
        zeros(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        zeros(0, 1), ...
        zeros(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        strings(0, 1), ...
        zeros(0, 1), ...
        false(0, 1), ...
        strings(0, 1), ...
        zeros(0, 1), ...
        'VariableNames', { ...
        'datasetLabel', ...
        'powerClusterID', ...
        'figureType', ...
        'panelColumn', ...
        'panelRow', ...
        'conditionOrMetric', ...
        'sessionRowIndex', ...
        'blockIndex', ...
        'experimentID', ...
        'baselineMode', ...
        'sourceField', ...
        'sourceSubscriptOrColumn', ...
        'plottedValue', ...
        'isValidForPlot', ...
        'reasonExcluded', ...
        'powerClusterAssignment'});
end
