function audit = emptyDeltaPointAuditTable()
% Empty table for side-specific delta contrast-pairing audit rows.

    audit = table( ...
        strings(0, 1), zeros(0, 1), zeros(0, 1), strings(0, 1), ...
        strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
        zeros(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
        zeros(0, 1), zeros(0, 1), false(0, 1), strings(0, 1), ...
        strings(0, 1), zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
        zeros(0, 1), zeros(0, 1), false(0, 1), zeros(0, 1), ...
        'VariableNames', {'experimentID', 'sessionRowIndex', ...
        'blockIndex', 'baselineMode', 'visualSide', 'deltaMetric', ...
        'baselineContrast', 'conContrast', 'inconContrast', ...
        'xDelta', 'deltaValue', 'maxAbsContrastDiff', ...
        'contrastPairTolerance', 'nearMatchTolerance', 'isPlotted', ...
        'pairingMethod', ...
        'reasonExcluded', 'nBaselinePoints', 'nConPoints', ...
        'nInconPoints', 'expectedPointCount', 'plottedPointCount', ...
        'nearMatchOutsideDefaultTolerance', 'nearMatchMaxAbsContrastDiff'});
end
