function audit = emptyDistributionStatsAuditTable()
% Return the stable schema used for distribution statistics audits.

    variableNames = { ...
        'datasetLabel', 'powerClusterID', 'figureType', ...
        'panelRow', 'panelColumn', 'metricOrParameter', ...
        'comparison', 'correctionFamilyID', 'correctionFamilySize', ...
        'correctionMethod', 'testUsedForAnnotation', 'testDirection', ...
        'alternativeHypothesis', 'nPaired', 'nWilcoxonNonzero', ...
        'sessionRowIndices', 'blockIndices', 'experimentIDs', ...
        'xValues', 'yValues', 'pairedDifferences', ...
        'meanDifference', 'medianDifference', 'semDifference', ...
        'nPositive', 'nNegative', 'nZero', ...
        'rawP', 'correctedP', ...
        'minPossibleTwoSidedRawP', 'minPossibleOneSidedRawP', ...
        'minPossibleRawPForAnnotation', ...
        'minPossibleCorrectedPForAnnotation', ...
        'pairedTTestRawP', 'pairedTTestCorrectedP', ...
        'tStatistic', 'pairedTTestN', ...
        'plannedAlternativeHypothesis', 'plannedRawP', ...
        'plannedCorrectedP', 'plannedStarLabel', ...
        'plannedDirectionApplicable', ...
        'allDifferencesInPlannedDirection', ...
        'starLabel', 'annotationDrawn', 'annotationStatus'};
    variableTypes = { ...
        'string', 'double', 'string', ...
        'string', 'string', 'string', ...
        'string', 'string', 'double', ...
        'string', 'string', 'string', ...
        'string', 'double', 'double', ...
        'string', 'string', 'string', ...
        'string', 'string', 'string', ...
        'double', 'double', 'double', ...
        'double', 'double', 'double', ...
        'double', 'double', ...
        'double', 'double', ...
        'double', 'double', ...
        'double', 'double', ...
        'double', 'double', ...
        'string', 'double', ...
        'double', 'string', ...
        'logical', 'logical', ...
        'string', 'logical', 'string'};
    audit = table('Size', [0 numel(variableNames)], ...
        'VariableTypes', variableTypes, ...
        'VariableNames', variableNames);
end
