function summary = plotJitteredGroupWithSummary( ...
        ax, valuesByGroup, colors, labels, opts)
% Plot paired jittered points with mean and SEM summaries.

    if nargin < 5 || isempty(opts)
        opts = struct();
    end
    opts = applyDefaults(opts);
    hold(ax, 'on');

    nRows = size(valuesByGroup, 1);
    nGroups = size(valuesByGroup, 2);
    jitter = deterministicJitter(nRows, opts.jitterWidth);

    if opts.connectPairedValues
        for rowIdx = 1:nRows
            finiteMask = isfinite(valuesByGroup(rowIdx, :));
            if sum(finiteMask) >= 2
                plot(ax, find(finiteMask) + jitter(rowIdx), ...
                    valuesByGroup(rowIdx, finiteMask), '-', ...
                    'Color', opts.pairedLineColor, ...
                    'LineWidth', opts.pairedLineWidth, ...
                    'HandleVisibility', 'off');
            end
        end
    end

    summary = summarizeColumns(valuesByGroup);
    for groupIdx = 1:nGroups
        finiteMask = isfinite(valuesByGroup(:, groupIdx));
        groupValues = valuesByGroup(finiteMask, groupIdx);
        marker = opts.groupMarkers{min(groupIdx, numel(opts.groupMarkers))};
        faceColor = opts.groupFaceColors( ...
            min(groupIdx, size(opts.groupFaceColors, 1)), :);
        edgeColor = opts.groupEdgeColors( ...
            min(groupIdx, size(opts.groupEdgeColors, 1)), :);

        if opts.showIQR && ~isempty(groupValues)
            plotIQRBox(ax, groupIdx, groupValues, colors(groupIdx,:), opts);
        end

        scatter(ax, groupIdx + jitter(finiteMask), groupValues, ...
            opts.pointSize, marker, 'filled', ...
            'MarkerFaceColor', faceColor, ...
            'MarkerEdgeColor', edgeColor, ...
            'MarkerFaceAlpha', opts.pointAlpha, ...
            'MarkerEdgeAlpha', min(1, opts.pointAlpha + 0.20), ...
            'LineWidth', 0.9, 'HandleVisibility', 'off');

        if isfinite(summary.mean(groupIdx))
            errorbar(ax, groupIdx, summary.mean(groupIdx), ...
                summary.sem(groupIdx), ...
                'LineStyle', 'none', ...
                'Color', opts.semColor, ...
                'LineWidth', opts.semLineWidth, ...
                'CapSize', opts.semCapSize, ...
                'HandleVisibility', 'off');
            scatter(ax, groupIdx, summary.mean(groupIdx), ...
                opts.meanPointSize, marker, 'filled', ...
                'MarkerFaceColor', faceColor, ...
                'MarkerEdgeColor', edgeColor, ...
                'LineWidth', opts.meanEdgeWidth, ...
                'HandleVisibility', 'off');
            meanTickColor = colors(groupIdx, :);
            if isfield(opts, 'meanTickColor') && ~isempty(opts.meanTickColor)
                customTickColor = opts.meanTickColor;
                isAutoColor = (ischar(customTickColor) || isstring(customTickColor)) && ...
                    strcmpi(char(string(customTickColor)), 'auto');
                if ~isAutoColor
                    meanTickColor = customTickColor;
                end
            end
            plot(ax, groupIdx + opts.meanTickWidth .* [-0.5 0.5], ...
                summary.mean(groupIdx) .* [1 1], '-', ...
                'Color', meanTickColor, ...
                'LineWidth', opts.meanTickLineWidth, ...
                'HandleVisibility', 'off');
        end
    end

    xlim(ax, [0.5 nGroups + 0.5]);
    xticks(ax, 1:nGroups);
    xticklabels(ax, labels);
end

function opts = applyDefaults(opts)
    defaults = struct( ...
        'jitterWidth', 0.13, ...
        'pointSize', 52, ...
        'meanPointSize', 120, ...
        'pointAlpha', 0.68, ...
        'connectPairedValues', true, ...
        'groupMarkers', {{'s'}}, ...
        'groupFaceColors', [0 0 0], ...
        'groupEdgeColors', [0 0 0], ...
        'pairedLineColor', [0.82 0.82 0.82], ...
        'pairedLineWidth', 0.65, ...
        'showIQR', false, ...
        'iqrWidth', 0.42, ...
        'iqrAlpha', 0.10, ...
        'semColor', [0 0 0], ...
        'semLineWidth', 2.2, ...
        'semCapSize', 11, ...
        'meanEdgeWidth', 1.2, ...
        'meanTickWidth', 0.26, ...
        'meanTickLineWidth', 1.8, ...
        'meanTickColor', 'auto');
    names = fieldnames(defaults);
    for idx = 1:numel(names)
        if ~isfield(opts, names{idx}) || isempty(opts.(names{idx}))
            opts.(names{idx}) = defaults.(names{idx});
        end
    end
end

function summary = summarizeColumns(values)
    summary.mean = mean(values, 1, 'omitnan');
    summary.n = sum(isfinite(values), 1);
    summary.sem = nan(1, size(values, 2));
    summary.median = median(values, 1, 'omitnan');
    for columnIdx = 1:size(values, 2)
        finiteValues = values(isfinite(values(:, columnIdx)), columnIdx);
        if numel(finiteValues) >= 2
            summary.sem(columnIdx) = ...
                std(finiteValues, 0) ./ sqrt(numel(finiteValues));
        elseif numel(finiteValues) == 1
            summary.sem(columnIdx) = 0;
        end
    end
end

function jitter = deterministicJitter(nValues, width)
    if nValues <= 1
        jitter = zeros(nValues, 1);
    else
        jitter = linspace(-width, width, nValues)';
    end
end

function plotIQRBox(ax, xValue, values, color, opts)
    quartiles = percentileLinear(values, [25 50 75]);
    whiskers = [min(values), max(values)];
    halfWidth = opts.iqrWidth ./ 2;
    patch(ax, ...
        [xValue-halfWidth xValue+halfWidth xValue+halfWidth xValue-halfWidth], ...
        [quartiles(1) quartiles(1) quartiles(3) quartiles(3)], ...
        color, 'FaceAlpha', opts.iqrAlpha, ...
        'EdgeColor', color, 'LineWidth', 1, ...
        'HandleVisibility', 'off');
    plot(ax, [xValue-halfWidth xValue+halfWidth], ...
        [quartiles(2) quartiles(2)], '-', ...
        'Color', color, 'LineWidth', 1.5, ...
        'HandleVisibility', 'off');
    plot(ax, [xValue xValue], whiskers, '-', ...
        'Color', color, 'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
end

function percentiles = percentileLinear(values, requestedPercentiles)
    values = sort(values(:));
    if numel(values) == 1
        percentiles = repmat(values, size(requestedPercentiles));
        return;
    end
    positions = 1 + (numel(values) - 1) .* requestedPercentiles ./ 100;
    lowerIdx = floor(positions);
    upperIdx = ceil(positions);
    fraction = positions - lowerIdx;
    percentiles = values(lowerIdx) .* (1 - fraction(:)) + ...
        values(upperIdx) .* fraction(:);
    percentiles = percentiles(:)';
end
