function printDistributionStatsAudit(audit, alpha)
% Print comparison-level statistics and small-sample diagnostics.

    if nargin < 2 || isempty(alpha)
        alpha = 0.05;
    end
    for rowIdx = 1:height(audit)
        row = audit(rowIdx, :);
        fprintf(['  Statistics audit: figure=%s | dataset=%s | C%d | ' ...
            'panel=%s/%s | metric=%s\n'], ...
            row.figureType, row.datasetLabel, row.powerClusterID, ...
            row.panelColumn, row.panelRow, row.metricOrParameter);
        fprintf(['    family=%s | Holm-Bonferroni within panel | ' ...
            'family size=%d\n'], ...
            row.correctionFamilyID, row.correctionFamilySize);
        fprintf(['    %s | annotation test=%s | alternative=%s | ' ...
            'n paired=%d | nonzero Wilcoxon n=%d\n'], ...
            row.comparison, row.testUsedForAnnotation, ...
            row.alternativeHypothesis, row.nPaired, ...
            row.nWilcoxonNonzero);
        fprintf('    session rows=%s | blocks=%s | experiment IDs=%s\n', ...
            row.sessionRowIndices, row.blockIndices, row.experimentIDs);
        fprintf('    x=%s\n    y=%s\n    paired differences=%s\n', ...
            row.xValues, row.yValues, row.pairedDifferences);
        fprintf(['    positive=%d | negative=%d | zero=%d | ' ...
            'mean diff=%0.6g | median diff=%0.6g | SEM diff=%0.6g\n'], ...
            row.nPositive, row.nNegative, row.nZero, ...
            row.meanDifference, row.medianDifference, row.semDifference);
        fprintf(['    Wilcoxon raw p=%0.8g | Holm p=%0.8g | ' ...
            'minimum two-sided raw p=%0.8g | ' ...
            'minimum one-sided raw p=%0.8g | ' ...
            'minimum annotation-tail Holm p=%0.8g\n'], ...
            row.rawP, row.correctedP, ...
            row.minPossibleTwoSidedRawP, ...
            row.minPossibleOneSidedRawP, ...
            row.minPossibleCorrectedPForAnnotation);
        fprintf(['    paired t-test diagnostic: n=%d | t=%0.6g | ' ...
            'raw p=%0.8g | Holm p=%0.8g\n'], ...
            row.pairedTTestN, row.tStatistic, ...
            row.pairedTTestRawP, row.pairedTTestCorrectedP);
        fprintf(['    planned test diagnostic: %s | raw p=%0.8g | ' ...
            'Holm p=%0.8g | %s | all differences expected direction=%s\n'], ...
            row.plannedAlternativeHypothesis, row.plannedRawP, ...
            row.plannedCorrectedP, row.plannedStarLabel, ...
            logicalText(row.plannedDirectionApplicable, ...
            row.allDifferencesInPlannedDirection));
        fprintf('    annotation: %s | %s\n', ...
            row.starLabel, row.annotationStatus);

        if strcmp(row.testDirection, "two-sided") && ...
                isfinite(row.minPossibleTwoSidedRawP) && ...
                row.minPossibleTwoSidedRawP >= alpha
            warning('distributionStats:WilcoxonResolutionLimit', ...
                ['n=%d: two-sided Wilcoxon minimum raw p is ' ...
                'approximately %.4g, so this comparison cannot reach ' ...
                'p<%.3g with a two-sided exact Wilcoxon test. With ' ...
                'Holm correction across %d comparisons, the minimum ' ...
                'adjusted p is approximately %.4g.'], ...
                row.nWilcoxonNonzero, ...
                row.minPossibleTwoSidedRawP, alpha, ...
                row.correctionFamilySize, ...
                min(1, row.correctionFamilySize .* ...
                row.minPossibleTwoSidedRawP));
        end
    end
end

function value = logicalText(applicable, allExpected)
    if ~applicable
        value = 'not directional';
    elseif allExpected
        value = 'yes';
    else
        value = 'no';
    end
end
