function [columnarBayesModel, objectiveFunction] = getBillModelFuncs(common)
    options = struct('nTrials', 50000);
    columnarBayesModel = @(x, params) columnarBayesMdl(x, params, options);
        
    sumAll = @(x) sum(x(:));
    epsilon = 1e-10;
    objectiveFunction = @(params, data) ...
        - sumAll(data.successBaseline .* log(max(columnarBayesModel(data.xBaseline, params).pcntrl/100, epsilon)) + ...
                  (data.sumBaseline - data.successBaseline) .* log(max(1 - columnarBayesModel(data.xBaseline, params).pcntrl/100, epsilon))) ...
        - sumAll(data.successInconOpto .* log(max(columnarBayesModel(data.xInconOpto, params).pic/100, epsilon)) + ...
                  (data.sumInconOpto - data.successInconOpto) .* log(max(1 - columnarBayesModel(data.xInconOpto, params).pic/100, epsilon))) ...
        - sumAll(data.successConOpto .* log(max(columnarBayesModel(data.xConOpto, params).pc/100, epsilon)) + ...
                  (data.sumConOpto - data.successConOpto) .* log(max(1 - columnarBayesModel(data.xConOpto, params).pc/100, epsilon)));

end