function [mdlBaseline, mdlOpto, objectiveFunction] = getWeibullFreeAllModelFuncs(common)
    lowerAsymptoteBL = common.lowerAsymptoteBL;
    epsilon = common.epsilon;
    
    mdlBaseline = @(x, params) 100*((x==0)*lowerAsymptoteBL) + ...
        [fliplr(100-(100 .* ((x>=0) .* (sign(x) .* (1 - exp(-((x) ./ params(3)).^params(4))) * ...
        ((1-lowerAsymptoteBL) - params(1)) + 1 - (1-lowerAsymptoteBL))))) + ...
        ((100 .* (x>=0) .* (sign(x) .* (1 - exp(-((x) ./ params(3)).^params(4))) * ...
        (lowerAsymptoteBL - params(1)) + 1 - lowerAsymptoteBL))-100.* (x>=0))];
    
    mdlOpto = @(x, params) 100*((x==0)*params(6)) + ...
        [fliplr(100-(100 .* ((x>=0) .* (sign(x) .* (1 - exp(-((x) ./ params(7)).^params(8))) * ...
        ((1-params(6)) - params(5)) + 1 - (1-params(6)))))) + ...
        ((100 .* (x>=0) .* (sign(x) .* (1 - exp(-((x) ./ params(11)).^params(12))) * ...
        (params(6) - params(9)) + 1 - params(6)))-100.* (x>=0))];
    
    objectiveFunction = @(params, data) ...
        -sum(data.successBaseline .* log((mdlBaseline(data.xBaseline, params) + epsilon)/100) + ...
        (data.sumBaseline - data.successBaseline) .* log(1 - (mdlBaseline(data.xBaseline, params) + epsilon)/100)) + ...
        -sum(data.successOpto .* log((mdlOpto(data.xOpto, params) + epsilon)/100) + ...
        (data.sumOpto - data.successOpto) .* log(1 - (mdlOpto(data.xOpto, params) + epsilon)/100));
end